# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.108.0-b.2";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.2/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-drFv9KR5FxzkpqLmPfAsjUUM9pDRoLo4gz2KPLvh5aY=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.108.0-b.2";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.2/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-DWX0vQRM8+sepGjbLbN8K8IJq33k0kik3UH/Q/8u8aw=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.108.0-b.2";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.2/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-2G2oR01gunrW7pn1hmQyF5uFv5vH6pbAvOXbUEqFwMA=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.108.0-b.2";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.2/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-7hbTTC8Um5+xvbMTYySl07711ykdT8r1hZl91wXzG1c=";
    };
  };
  adl = {
    pname = "adl";
    version = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
      fetchSubmodules = false;
      sha256 = "sha256-huGpDtkWrhZyKDNKXat8T3qtAyMjBaq8HFd1w1ThUVk=";
    });
  };
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "b3590f4ce1f570be34aa5d132840d4a7122c67b2";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "b3590f4ce1f570be34aa5d132840d4a7122c67b2";
      fetchSubmodules = false;
      sha256 = "sha256-KdxghSvkIsxqADzIZL8aSw8azYvcPF0mpw78uEWG2rs=";
    });
    cargoLock = {
      lockFile = ./age-plugin-yubikey-b3590f4ce1f570be34aa5d132840d4a7122c67b2/Cargo.lock;
      outputHashes = { };
    };
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "5ffac4c9a2f4aaaf87d446f937ee2c7c8499984a";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "5ffac4c9a2f4aaaf87d446f937ee2c7c8499984a";
      fetchSubmodules = false;
      sha256 = "sha256-qfjd2JUCgPM0xF8oeeVYMkWopopEXw3ysl+sSLGm2hw=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "89bee0e3612be471d427cd81540bd54db1955c9d";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "89bee0e3612be471d427cd81540bd54db1955c9d";
      fetchSubmodules = false;
      sha256 = "sha256-erYV8PxwA7eT3ZJTFYRfbfW2T5Cr6ZHaft7BEipU5Oo=";
    });
  };
  avizo = {
    pname = "avizo";
    version = "81b6dcad9b52faf2b87700736ccf5c5dca6c13ec";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "81b6dcad9b52faf2b87700736ccf5c5dca6c13ec";
      fetchSubmodules = false;
      sha256 = "sha256-pS5atxRwl3QfR9GNHawLJTh5lDInXjFvgfCI1s+hPJE=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "cd4008c249ed51869efc3b4677f076605f17d502";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "cd4008c249ed51869efc3b4677f076605f17d502";
      fetchSubmodules = false;
      sha256 = "sha256-osYqXOA5PUK4sAaNgemXgQWQZ0INDHT1/14jCI02oP8=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  bling = {
    pname = "bling";
    version = "718ac6da7a9a6a61b17bef63316ce6978adda318";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "718ac6da7a9a6a61b17bef63316ce6978adda318";
      fetchSubmodules = false;
      sha256 = "sha256-uhV7kK6auO52GTrMtrgtVkm+eDeuJUyb7WjPu7ZfVLk=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "b33241350ba0c7901eb079ca1c162796662cb070";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "b33241350ba0c7901eb079ca1c162796662cb070";
      fetchSubmodules = false;
      sha256 = "sha256-biygl3L8CAdam2O7mVAqQxN38Z2WbRTk1Q0ux0qPf/s=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "599c81d753a1af8ffbb6d733321cc76f170c41e4";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "599c81d753a1af8ffbb6d733321cc76f170c41e4";
      fetchSubmodules = false;
      sha256 = "sha256-IGfxeeA7KLbcrNZ/OPOfzB3fy8qnTQq9YoJppLgzkj8=";
    });
  };
  cinny = {
    pname = "cinny";
    version = "b155d7d1ba3e8bb797ab64c90fb46f79b312da28";
    src = fetchFromGitHub ({
      owner = "ajbura";
      repo = "cinny";
      rev = "b155d7d1ba3e8bb797ab64c90fb46f79b312da28";
      fetchSubmodules = false;
      sha256 = "sha256-gK9oPUZoxQGGQkIRYyFCWjxxtAWMaTuAS01XI5hcee0=";
    });
  };
  conduit = {
    pname = "conduit";
    version = "95ca43e20ff2cb5befeb73612ec4b5d864db160d";
    src = fetchgit {
      url = "https://gitlab.com/famedly/conduit";
      rev = "95ca43e20ff2cb5befeb73612ec4b5d864db160d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-vteRXDkwHy6T9oLZTjIH+89emdqgp0KnVHdEVi0WEdk=";
    };
    cargoLock = {
      lockFile = ./conduit-95ca43e20ff2cb5befeb73612ec4b5d864db160d/Cargo.lock;
      outputHashes = {
        "ruma-0.4.0" = "sha256-Zdoac8DAFLhza2smxQyIvoW7w1QKG2ZQVgOMTDe/1d0=";
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.132";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.132/discord-canary-0.0.132.tar.gz";
      sha256 = "sha256-20NZyd5AQY6GsSfAPML7GxRA+e1UldedvY09SnFqS8o=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "4c67e790f68025ca6822ff1f29002d9166fb5008";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "4c67e790f68025ca6822ff1f29002d9166fb5008";
      fetchSubmodules = false;
      sha256 = "sha256-jOs8OSFGc/HU/pIDd29h8nyX1WDS4UB8cKTqkP5AuWg=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "9ae8b0a3f24489da62291cfee0561ae9cf214c15";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "9ae8b0a3f24489da62291cfee0561ae9cf214c15";
      fetchSubmodules = false;
      sha256 = "sha256-JiBpocumhdPXDx4sYJaelfm/7UheHB08sEkgi6hwTfs=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "eb9a7b1939a6d080897918fd2c1da2e3aaae21d4";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "eb9a7b1939a6d080897918fd2c1da2e3aaae21d4";
      fetchSubmodules = false;
      sha256 = "sha256-RZ3ISQJYDrmbbf0s7xZhmR4AvREOf5ILz3A3mv3m7xg=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "1a8ac86b5941d7784c73300d63654db7296d4319";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "1a8ac86b5941d7784c73300d63654db7296d4319";
      fetchSubmodules = false;
      sha256 = "sha256-3iA7GDTiCx5vHawj8ZBFAK0BIfmxEFuQrVfL7Gi6FhM=";
    });
  };
  duf = {
    pname = "duf";
    version = "0d660c36500629a0bbc1cc56695ad1821d23993c";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "0d660c36500629a0bbc1cc56695ad1821d23993c";
      fetchSubmodules = false;
      sha256 = "sha256-FZ4NplvCc1c+wPy1NSs2qwfWVtCPNHs6JquubGnwiEY=";
    });
  };
  eww = {
    pname = "eww";
    version = "8336bd04d2c7fe301645bb883b140c6415e87556";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "8336bd04d2c7fe301645bb883b140c6415e87556";
      fetchSubmodules = false;
      sha256 = "sha256-4wPtMAn8cexWoLJYQjcBu2yn72/KBdphZX4KmCjQ/J0=";
    });
    cargoLock = {
      lockFile = ./eww-8336bd04d2c7fe301645bb883b140c6415e87556/Cargo.lock;
      outputHashes = { };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "2d920dc04c3cb83689dc9b3e75f931b3e0835753";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "2d920dc04c3cb83689dc9b3e75f931b3e0835753";
      fetchSubmodules = false;
      sha256 = "sha256-LuZKv69jAzoHGDFU3u0ehvYFUQPNyvJLGZQZf6mUA+A=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "42917930ca11646ad5ac71f53f600e752ed713c6";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "42917930ca11646ad5ac71f53f600e752ed713c6";
      fetchSubmodules = false;
      sha256 = "sha256-KJeHTtM+ZqqyUNGE8CmSNNvcwPd+5UPRd3P3DyKCnR0=";
    });
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = { };
    };
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "6fc01736ac93d167b4baed41ae4b2ac482ecc20c";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "6fc01736ac93d167b4baed41ae4b2ac482ecc20c";
      fetchSubmodules = false;
      sha256 = "sha256-0LsZf4WmbRzRVwRLZVBTZYNBEiRp0VoMZpm7mnowvD4=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "5a455b1ead5d72483952356ddfe25b9e3b637e6f";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "5a455b1ead5d72483952356ddfe25b9e3b637e6f";
      fetchSubmodules = false;
      sha256 = "sha256-RknaT4w0lgI3xbwCxzRxXzjByzpwdZMeIcZ+/b7g+Gk=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "a09b2468ea345ae0be6ad191d016bc9b26f57a7c";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "a09b2468ea345ae0be6ad191d016bc9b26f57a7c";
      fetchSubmodules = false;
      sha256 = "sha256-ia2CgJSDfeAvy6EMnyJXbs7PB6tG+0SpOmXMrRUwfi8=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-119-gdcb562a";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-119-gdcb562a-1_all.deb";
      sha256 = "sha256-d3c2NUPYW4byUZvIOgK+mqmqNKpDvDRgjReflTmdICo=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-852";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-852-1_all.deb";
      sha256 = "sha256-wFnDaorhIwY46rUfXs1hwFtkxIxEpNuZOwARREeQJ9w=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.5828";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.5828.tar.bz2";
      sha256 = "sha256-2oZKAURwtOIvJq/C+NQeeBWkBxPygeqvfmIdzOrUhZc=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.5828";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.5828-1_all.deb";
      sha256 = "sha256-fA93Rt/zh5WMdbyJ+ea681UcPxMUahf0Irvbrjh4kks=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.1-618-g0d92d908";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.1-618-g0d92d908-1_all.deb";
      sha256 = "sha256-YLRfjE2DzfTXxuT53HSkFxrRR989fq9stolSsF6fVPc=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "e413822ae1364e9ff182aeec1d149b0ecef22e8c";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "e413822ae1364e9ff182aeec1d149b0ecef22e8c";
      fetchSubmodules = false;
      sha256 = "sha256-FEQQUJcjCuH+FSl2F2sh9xAsDR1o1p+OAjMfkeLh7p0=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
      fetchSubmodules = false;
      sha256 = "sha256-d8iBxfHkryy5lM5myWPo0a3zgUZQrklYazCSCyKKDGs=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  matrix-appservice-discord = {
    pname = "matrix-appservice-discord";
    version = "v1.0.0";
    src = fetchFromGitHub ({
      owner = "Half-Shot";
      repo = "matrix-appservice-discord";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-hZQ+3FDRWNGsnaHblnB2p6Inf9ZMrbB2jmgR2rskil0=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "98.0.1108.39";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_98.0.1108.39-1_amd64.deb";
      sha256 = "sha256-C4BX2lgIik0E6s6m6yHs0TnHRQ24bcbNRjW/8mnojVI=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "99.0.1141.0";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_99.0.1141.0-1_amd64.deb";
      sha256 = "sha256-i2ZdFIj2Iv1PBiC9p0IZmI2yiMwmqAZnGLAjFFh8MU8=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "f1848246d177e17293198b58d1bca67acdfb9fb1";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "f1848246d177e17293198b58d1bca67acdfb9fb1";
      fetchSubmodules = false;
      sha256 = "sha256-v3+G5k2xgt4aGuJ35T52mQCyynVoRmEl4pcx7qsulmg=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.33.0";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.33.0.tar.gz";
      sha256 = "sha256-7uVz7gumQ7fG6Ilc2JuZPRZLchhBnf5edWez/Odd8Nc=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.31.2";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.31.2.tar.gz";
      sha256 = "sha256-LRQpvyOxYKZPUkXHOb85f4BDUU8peyD9/HJJpjIJESo=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
      fetchSubmodules = false;
      sha256 = "sha256-ZJmnUU81hg34JHkA82BfapFGqKrhqFk6wCM2eO2RaVs=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "98efb3661467bd9b1c3c8fccb28143bf86cd206a";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "98efb3661467bd9b1c3c8fccb28143bf86cd206a";
      fetchSubmodules = false;
      sha256 = "sha256-o1KrPosnGhbm5gDK8BtoDDKRafyCqO0mdlVPYzMCenY=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-MAxQkdR40YUDl7z0OYbuwiueOoB2JuYikIu11CqiAto=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "336fc978318d2410b3ddfcf16ebd850b9833fd05";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "336fc978318d2410b3ddfcf16ebd850b9833fd05";
      fetchSubmodules = false;
      sha256 = "sha256-+T7uGgeXuk9WoHDoGyRIb8xI/txZYYgXkkj++F9ENV8=";
    });
    cargoLock = {
      lockFile = ./ouch-336fc978318d2410b3ddfcf16ebd850b9833fd05/Cargo.lock;
      outputHashes = { };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "3b9af145f0275edf6c54286e5f26e8b269835a6b";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "3b9af145f0275edf6c54286e5f26e8b269835a6b";
      fetchSubmodules = false;
      sha256 = "sha256-EwWkFLjvsixRB/WtG7R1PB2pQiS/gU4VuAxpyekE9rA=";
    });
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.41.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.41.0.tar.gz";
      sha256 = "sha256-go3EXmC9Vp0xXi1mH65p85FKsTe0CbyNXw3VVRrnpeQ=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "80c988236fb476985826e85c5fbf6b101a60c39e";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "80c988236fb476985826e85c5fbf6b101a60c39e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oE0WliIKbmH69atQePYQkPRNFx8WG9SjkHHMND008Kc=";
    };
  };
  pure = {
    pname = "pure";
    version = "67a80dc72fb2ae9bebb3cffb3d6f789482c2f933";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "67a80dc72fb2ae9bebb3cffb3d6f789482c2f933";
      fetchSubmodules = false;
      sha256 = "sha256-CI2ontloLNIzUJghZzPZ2UPbIS+cJAfKvKeetwvW6vg=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "908516967acce6d78d02a4b7306f30d09180da6d";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "908516967acce6d78d02a4b7306f30d09180da6d";
      fetchSubmodules = false;
      sha256 = "sha256-ZZ7lut3wYDg4Ry8SE96lCL8gEMf0Btv+cSks/9M6JJs=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "835f9f44e7153a73b96f8c7e8ad91b7ecd2795e8";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "835f9f44e7153a73b96f8c7e8ad91b7ecd2795e8";
      fetchSubmodules = false;
      sha256 = "sha256-4FV0HSgqyWqQhoLEp9uby8/eTPYci3UCfvIqZ45aHTw=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "80cf91417c8a76fe3e1d20fb84bba1be0ec232db";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "80cf91417c8a76fe3e1d20fb84bba1be0ec232db";
      fetchSubmodules = false;
      sha256 = "sha256-pFkvXZVBBLQcaeXCEUSvbz8n7dbBtRXuQeCrhf45U4M=";
    });
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "9efa6504c3b6a9b39d8d423a7fd7f3783e865c03";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "9efa6504c3b6a9b39d8d423a7fd7f3783e865c03";
      fetchSubmodules = true;
      sha256 = "sha256-W/gowO7h++1GnaPGVZQoEygESaBA1CPPPLqdEZid1CM=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "9c6715f95e71f480c23326a21f0b4094185fc3ce";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "9c6715f95e71f480c23326a21f0b4094185fc3ce";
      fetchSubmodules = false;
      sha256 = "sha256-i7Gk8fG8CTPMZm5h43WLgEuXVOTfzJK1cRvoj0YToZA=";
    });
    cargoLock = {
      lockFile = ./rustdesk-9c6715f95e71f480c23326a21f0b4094185fc3ce/Cargo.lock;
      outputHashes = {
        "systray-0.4.1" = "sha256-p1PMr/8oS6zHx4+Ng4zCqt0xZ57cq3wAu6/agyWq5Jw=";
        "parity-tokio-ipc-0.7.3" = "sha256-Ji/q7RQDznFs+m4AHH1IEL1TMqqCtH4Z5DY6sjcu/T0=";
        "libappindicator-0.6.1" = "sha256-JGnnZrcwbh8WJ6+/4bYhfD3HvgF2C7XaaGb6TaMRWdw=";
        "rdev-0.5.0" = "sha256-bkSke7HW2btBCc8+DayeWSTHLRlGNl1+QKTMRUYA4hg=";
        "cpal-0.13.4" = "sha256-Gs1cqYJP92Zy8Fnu3wGQ9+p5oIkCkOp9v++8ocFSNiU=";
        "sciter-rs-0.5.57" = "sha256-pF5Rwav78//oqDAv0Nhb7tawhSMnlSuy4sPUOfPd8NU=";
        "tokio-socks-0.5.1" = "sha256-inmAJk0fAlsVNIwfD/M+htwIdQHwGSTRrEy6N/mspMI=";
        "confy-0.4.1" = "sha256-5QwA4YfEEE6QqEEUJ3+C37UbUf88NYds38kIthVSo5Y=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
        "rust-pulsectl-0.2.11" = "sha256-CZkvii6pQM5jaR9RK9HDrczxIxZwuahpdVM+UsRLw9s=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "2e539cf5bfc60b1463519de2566422464877992d";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "2e539cf5bfc60b1463519de2566422464877992d";
      fetchSubmodules = false;
      sha256 = "sha256-MMPmTEMYghf2A+rQF5pJaLTb2NyXpV3HKx20g7o/deg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "85cbf3f2cda66f8deadea5f1e2e627a466aba885";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "85cbf3f2cda66f8deadea5f1e2e627a466aba885";
      fetchSubmodules = false;
      sha256 = "sha256-QNMm8bB4fxpDbqo0rp33s6xQW8ard51OzZSoloxlLr8=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-uQAY1yMr9SetN/X6UrY2mvfxmIOmNQ0A3IrJQNvi5jM=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-m0eDv1CYCkkm5qgbLioI9+ahf0OXSYh0Gkp61vgMSFk=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-8niJPk3hGfK1USIs9eoxZ6GlM4aZ7ZObmQj2Zomj+Go=";
    };
  };
  snui = {
    pname = "snui";
    version = "ce9642264b0ab8be180f564292c0a7c86357f7c6";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "ce9642264b0ab8be180f564292c0a7c86357f7c6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ywWCZyAEBKJhDCU46LbZLN4DWk1AnDW7kpa7iVu8odE=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "0d72f0f321a6e1a08ff8c2918a9deac38a2ac226";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "0d72f0f321a6e1a08ff8c2918a9deac38a2ac226";
      fetchSubmodules = false;
      sha256 = "sha256-vq2t4C6Aw0VNXPtKqO703bbf+hDWFyKlzmfC3Dr2NtE=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "acaad8c633a7c20f6722e685ae2e948e331a8cb1";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "acaad8c633a7c20f6722e685ae2e948e331a8cb1";
      fetchSubmodules = false;
      sha256 = "sha256-9t+MPQJP1oR7SXUECiUStN+FEUoaZ1Kip7oRfIYnuDU=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.77.643.g3c4c6fc6";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_57.snap";
      sha256 = "sha256-ObuNyewJ55GihMURCPk3jT5llqH+UxsVDlzQ/H/vxak=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "603bcc4d802d2b8f45ac517c0513eb4096252d7b";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "603bcc4d802d2b8f45ac517c0513eb4096252d7b";
      fetchSubmodules = false;
      sha256 = "sha256-zOyRbeaC+wI0MgJeUksSzS9SR+folKAg6aCzc7mgONI=";
    });
    cargoLock = {
      lockFile = ./spotifyd-603bcc4d802d2b8f45ac517c0513eb4096252d7b/Cargo.lock;
      outputHashes = { };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "bc3564dbe4dc17e3d8b36bd3b47c314d80dcb38c";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "bc3564dbe4dc17e3d8b36bd3b47c314d80dcb38c";
      fetchSubmodules = false;
      sha256 = "sha256-wi/9wV4WvBJH301r/l4Z+8rOSMu2A+STmrIsykMe2zk=";
    });
  };
  sway-borders = {
    pname = "sway-borders";
    version = "5f4162f449b19f6d198b365fc6d3dd0febc065e2";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "5f4162f449b19f6d198b365fc6d3dd0febc065e2";
      fetchSubmodules = false;
      sha256 = "sha256-gCdnim7excF11GEoni5YbIGTWSIx+wjHc8NO8lVNFts=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  tailscale = {
    pname = "tailscale";
    version = "fa612c28cf02afdf0031c432f4f0b782e741acb0";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "fa612c28cf02afdf0031c432f4f0b782e741acb0";
      fetchSubmodules = false;
      sha256 = "sha256-Jwp2ItT1HesqdYXUJXvX9TbWk9hC81gPfOCJLFz78uE=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "c805d62f50e7fad36edb834997ebab251843fe21";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "c805d62f50e7fad36edb834997ebab251843fe21";
      fetchSubmodules = false;
      sha256 = "sha256-qhulHwpryWOBKPXhbFlTAQs29gxOU8lwLX701Kw28Y4=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.4.00.26453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.26453_amd64.deb";
      sha256 = "sha256-7hW1d5Oqa3nM2nRNUjLaZwM1q9kxuuKgIPUEOhKauFk=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "2422c23228efc9b72872b69f22f7d25c1d337264";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-ML1pCEnK+DDHsUmFneqsHrSl05ZLHz1GPydPcurOFbY=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "43b6c878e9f280b771f6c8a8baa9a374489f2ae1";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "43b6c878e9f280b771f6c8a8baa9a374489f2ae1";
      fetchSubmodules = false;
      sha256 = "sha256-2mHWbRfunBcUnHf9GWuFovno+3cZaELMw5MVgXWwcC4=";
    });
  };
  ultimmc = {
    pname = "ultimmc";
    version = "66bb7105db93e0977bb64a59a12b001f780e0566";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "66bb7105db93e0977bb64a59a12b001f780e0566";
      fetchSubmodules = true;
      sha256 = "sha256-t/R3BBRy2orzUuh537xMPwORHmhQy4aGe96e77CVzZs=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.24.0";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.24.0";
      fetchSubmodules = false;
      sha256 = "sha256-zeMVdsTSp1z8cwebU2N6w7436N8CcI7PzNedDOSvEx4=";
    });
    cargoLock = {
      lockFile = ./vaultwarden-1.24.0/Cargo.lock;
      outputHashes = {
        "rocket-0.5.0-dev" = "sha256-sZL6GtLrfDy0ePix2UxZTdpFQvvc0G/Q+7qbCLGknqY=";
        "job_scheduler-1.2.1" = "sha256-b0jIKAHVrQNdZdlq+5kfGAOsi8bHu20QDtQaWTuJYtU=";
        "devise-0.3.0" = "sha256-crnEOKK7FiuIs55mOKgNfb3mNzr3QLI0icPPuG+xKVI=";
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2.25.1";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2.25.1/bw_web_v2.25.1.tar.gz";
      sha256 = "sha256-Kg9LzwL8DKZxy4NvaYbXkJcVUqKLHKwfmYyiotDS2Hw=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  waydroid = {
    pname = "waydroid";
    version = "8c20d0c10907d330a56c335d086831759822f63f";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "8c20d0c10907d330a56c335d086831759822f63f";
      fetchSubmodules = false;
      sha256 = "sha256-cSCGrqK3MPIhvRlP/o7dRGX1yZZqjECXf2a2VZxYy0A=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "ecf3b62ea61eabe483625fd1cbd476a8fd994952";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "ecf3b62ea61eabe483625fd1cbd476a8fd994952";
      fetchSubmodules = false;
      sha256 = "sha256-Dz19SlBTTCn73rnnU4PpZUbwcIpA6j2ODFYVAwTn7wI=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "b9ac43c30c7ed214704a8a52336ecee30d74bfc2";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "b9ac43c30c7ed214704a8a52336ecee30d74bfc2";
      fetchSubmodules = false;
      sha256 = "sha256-BEkQ8mp9hrEDeIpO+H49KimPbTVeHHARPKmImzoGdXw=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "aff25879da41842f75e27e383990540f6342d3a6";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "aff25879da41842f75e27e383990540f6342d3a6";
      fetchSubmodules = false;
      sha256 = "sha256-N4nQoHbID7UM4HPCbm5I/1UWjsAn7PRMlo6osMVxsS4=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2391.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2391.0-linux-x64.zip";
      sha256 = "sha256-7gH808C67m/s09e4rQUQHb/t+iGVdzW+YzrB1ZxGIdo=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xdg-desktop-portal = {
    pname = "xdg-desktop-portal";
    version = "f29d6b106cfb21ac0b1ce3c207cd32d5164136b9";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal";
      rev = "f29d6b106cfb21ac0b1ce3c207cd32d5164136b9";
      fetchSubmodules = false;
      sha256 = "sha256-SdoYFpW+7Lf2x9GF/1TmI64lwCchudj4jnJ5jzaK9o8=";
    });
  };
  xdg-desktop-portal-gtk = {
    pname = "xdg-desktop-portal-gtk";
    version = "347fcd1f61e126ae77950b5d4b66ad9522aec1f2";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal-gtk";
      rev = "347fcd1f61e126ae77950b5d4b66ad9522aec1f2";
      fetchSubmodules = false;
      sha256 = "sha256-pIeC+dj+VKBCbGU98ITkmPi7BGSjkPnyDMO2KlJOEgI=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qKKb/i67QY/NxZFkJaVRc3hGPjjnRfgpMqGqZ0YNQE8=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "914d8f5e0f469cd0416364dd008e9eea752bf703";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "914d8f5e0f469cd0416364dd008e9eea752bf703";
      fetchSubmodules = false;
      sha256 = "sha256-XJtYZYbmwCrkbB7a533kkI/CcawkmHHSEu4zSznVvEY=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "2e6edeb56911d594cc0d9afec07d70f58961a25d";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "2e6edeb56911d594cc0d9afec07d70f58961a25d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3e1S1Xhf/M2EygyhIvu/HaEjroUx58DdMOqA4t6UgYc=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "226b8af730c739966f31066e2ee6253c7263059d";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "226b8af730c739966f31066e2ee6253c7263059d";
      fetchSubmodules = false;
      sha256 = "sha256-JlfUQnP+mxnCFDYgBkK5wt/nn4rL55NJaV+WvkVSEmw=";
    });
  };
  yubikey-guide = {
    pname = "yubikey-guide";
    version = "fe6434577bce964aefd33d5e085d6ac0008e17ce";
    src = fetchFromGitHub ({
      owner = "drduh";
      repo = "YubiKey-Guide";
      rev = "fe6434577bce964aefd33d5e085d6ac0008e17ce";
      fetchSubmodules = false;
      sha256 = "sha256-HQrS2+yvSXi/XCOzWRIV4S/riKpCvnHTSGZfbYXEmrg=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.9.3.1911";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.9.3.1911/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-RH+e2GfzBX3huKRiX1P7DHh95tem7N+TBN+kiQSwVV0=";
    };
  };
}
