# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.108.0-b.7";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.7/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-0t2OkyxfezzStsVI+5qYJ6wTl7wmwbJa2IIfe63cAuE=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.108.0-b.7";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.7/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-RM9Dnw+ZOaBvzVQRXczLS+HUPgBz9XVbrE8bVeLhwbw=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.108.0-b.7";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.7/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-vxNG4Puz4L6iQwekm1s3t5anL9vy+cYuhPcN9daxG8o=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.108.0-b.7";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.7/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-Bb20SE1pk73m3/5lRVoYhqC8I7odgnBmWRVaJdeFxvg=";
    };
  };
  adl = {
    pname = "adl";
    version = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
      fetchSubmodules = false;
      sha256 = "sha256-huGpDtkWrhZyKDNKXat8T3qtAyMjBaq8HFd1w1ThUVk=";
    });
  };
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
      fetchSubmodules = false;
      sha256 = "sha256-KXqicTZ9GZlNj1AH3tMmOrC8zjXoEnqo4JJJTBdiI4E=";
    });
    cargoLock = {
      lockFile = ./age-plugin-yubikey-08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb/Cargo.lock;
      outputHashes = { };
    };
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "941eef9d5435b38775911d5c773a7dfda8adfea8";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "941eef9d5435b38775911d5c773a7dfda8adfea8";
      fetchSubmodules = false;
      sha256 = "sha256-k9zwrmXRG93BVExtJkZe7w8H1oOiI2aAHEkllqsv2jw=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  argonone-fancontrold = {
    pname = "argonone-fancontrold";
    version = "b6b960eb492224012680f56e3c6fba13502e542c";
    src = fetchFromGitHub ({
      owner = "mgdm";
      repo = "argonone-utils";
      rev = "b6b960eb492224012680f56e3c6fba13502e542c";
      fetchSubmodules = false;
      sha256 = "sha256-v098KH8TgzGgCc7+59SVWy19xW456eXX/BDdt9zzVhk=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "ea139e3ef8810149d90df8637984f2444282745e";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "ea139e3ef8810149d90df8637984f2444282745e";
      fetchSubmodules = false;
      sha256 = "sha256-Ypd/awDTLgKwxfUQsDOPj0/V6QfPKmoMgOkGoO+FZwQ=";
    });
  };
  asusctl = {
    pname = "asusctl";
    version = "b6934bbf63ee57b0b9f38fdcf0da3dffeaca0928";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl";
      rev = "b6934bbf63ee57b0b9f38fdcf0da3dffeaca0928";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-sA/ZbqPsctMd5sCjWd0i22KCA/TqSMMVAEVKWFlZyWM=";
    };
    cargoLock = {
      lockFile = ./asusctl-b6934bbf63ee57b0b9f38fdcf0da3dffeaca0928/Cargo.lock;
      outputHashes = { };
    };
  };
  avizo = {
    pname = "avizo";
    version = "ef80131cb73fa90225aaccb3cae63e281c534f56";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "ef80131cb73fa90225aaccb3cae63e281c534f56";
      fetchSubmodules = false;
      sha256 = "sha256-Q2AnMzbmZVp7LHSmhxaHSestAaL0eOb0r3IPwaZqUzE=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "c539e0e4350a42f813952fc28dd8490f42d934b3";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "c539e0e4350a42f813952fc28dd8490f42d934b3";
      fetchSubmodules = false;
      sha256 = "sha256-EDAL7NnLF2BiVI8DAlEciiZtDmwXOzCPypGTrlN/OoQ=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  bling = {
    pname = "bling";
    version = "6e4ecb334c3764483d04b4e6bfc15abf98043bef";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "6e4ecb334c3764483d04b4e6bfc15abf98043bef";
      fetchSubmodules = false;
      sha256 = "sha256-TBEaxHRYtEyOVxtym/IaXuq0CVbizWTx8mAqIRww/r4=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "9db34f67f0f8baad366fb05bcfc522809dbd56ae";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "9db34f67f0f8baad366fb05bcfc522809dbd56ae";
      fetchSubmodules = false;
      sha256 = "sha256-tg+PqtFxptaJgKh4jF0EK8FcdPkDxdIJZ1p/Z0uAI9o=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "741b0502ee7cb0ecbd6dd0517c4f186729f52718";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "741b0502ee7cb0ecbd6dd0517c4f186729f52718";
      fetchSubmodules = false;
      sha256 = "sha256-4hNQ2z31nLY4RNPX1GX9QOFSYPGU358RfcWrTVujSXM=";
    });
  };
  cinny = {
    pname = "cinny";
    version = "2.0.3";
    src = fetchurl {
      url = "https://github.com/ajbura/cinny/releases/download/v2.0.3/cinny-v2.0.3.tar.gz";
      sha256 = "sha256-rbuEc4IxfYwohbzWpnF+4T5l8ZpxG6YfN/3c6xsST44=";
    };
  };
  conduit = {
    pname = "conduit";
    version = "8bb58061fdc709f38b264c30d83c050477a89f9a";
    src = fetchgit {
      url = "https://gitlab.com/famedly/conduit";
      rev = "8bb58061fdc709f38b264c30d83c050477a89f9a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-MZ5EI5kJ5bSm2jiArWt5NunIaevLWc0AsN41otJl8YQ=";
    };
    cargoLock = {
      lockFile = ./conduit-8bb58061fdc709f38b264c30d83c050477a89f9a/Cargo.lock;
      outputHashes = {
        "reqwest-0.11.9" = "sha256-wH/q7REnkz30ENBIK5Rlxnc1F6vOyuEANMHFmiVPaGw=";
        "ruma-0.5.0" = "sha256-srmybII7j3xkSDVFvIiWUQnZsW+vEKKagSZhA5MRRQc=";
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  conduit-toolbox = {
    pname = "conduit-toolbox";
    version = "805baa070528e6db7161ef35b75180e70d896541";
    src = fetchFromGitHub ({
      owner = "ShadowJonathan";
      repo = "conduit_toolbox";
      rev = "805baa070528e6db7161ef35b75180e70d896541";
      fetchSubmodules = false;
      sha256 = "sha256-vQ4r2Cvf2okeJ5qGIQ8mHoUmmrbUbY+bIEpee7XH6zA=";
    });
    cargoLock = {
      lockFile = ./conduit-toolbox-805baa070528e6db7161ef35b75180e70d896541/Cargo.lock;
      outputHashes = {
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.135";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.135/discord-canary-0.0.135.tar.gz";
      sha256 = "sha256-dmG+3BWS1BMHHQAv4fsXuObVeAJBeD+TqnyQz69AMac=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "74fb5dabb942b9445a3a91c9fd299ead6837822a";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "74fb5dabb942b9445a3a91c9fd299ead6837822a";
      fetchSubmodules = false;
      sha256 = "sha256-sJUw0x8PotxiBmWE90tn5bCwFgbRPvsIQJKIlMESO2I=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "53f7b70af45844a27db2e9fe99626cad1980f295";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "53f7b70af45844a27db2e9fe99626cad1980f295";
      fetchSubmodules = false;
      sha256 = "sha256-yoA3ViHRB5zVZhq+WADp1R5aSuQxU9SS1WmEAMUNQ28=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
      fetchSubmodules = false;
      sha256 = "sha256-70wtFxJOY9h4moT4hCTs4yfp2wGM39i5qnJerBVkpV4=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
      fetchSubmodules = false;
      sha256 = "sha256-5m+btrwhlk/nIZSasu+fTK1NhK0KdugVeD0KYOt0vE4=";
    });
  };
  duf = {
    pname = "duf";
    version = "67895e4565a694404489e8e23ffecb5d679b2e68";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "67895e4565a694404489e8e23ffecb5d679b2e68";
      fetchSubmodules = false;
      sha256 = "sha256-K1dWqcwKSxcGkoMsuMeCdkxzKM6QPw5oc8Yoj7lX/Oc=";
    });
  };
  eww = {
    pname = "eww";
    version = "c0dcc433363ee20553fda9bbd08ec523393438d8";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "c0dcc433363ee20553fda9bbd08ec523393438d8";
      fetchSubmodules = false;
      sha256 = "sha256-20VHvOEdsBOh45icgiDM7NuaGV73nRGMPYmFf+hUbik=";
    });
    cargoLock = {
      lockFile = ./eww-c0dcc433363ee20553fda9bbd08ec523393438d8/Cargo.lock;
      outputHashes = { };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "2d920dc04c3cb83689dc9b3e75f931b3e0835753";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "2d920dc04c3cb83689dc9b3e75f931b3e0835753";
      fetchSubmodules = false;
      sha256 = "sha256-LuZKv69jAzoHGDFU3u0ehvYFUQPNyvJLGZQZf6mUA+A=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "0870eca81f61f233e3c96b2d7f9a7f2b9ad7a145";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "0870eca81f61f233e3c96b2d7f9a7f2b9ad7a145";
      fetchSubmodules = false;
      sha256 = "sha256-2n0yeoba4AhXxUVziqIymBayBCFJJVhZoRyZal5zD8c=";
    });
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = { };
    };
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "97c0bcdb1d8c9e56609036fc5b9a36136aa433c8";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "97c0bcdb1d8c9e56609036fc5b9a36136aa433c8";
      fetchSubmodules = false;
      sha256 = "sha256-R0V8N9NH2e3yWzni3T5v+Kd0ZxCVwBSp9gC3g6gmbes=";
    });
  };
  hyprland = {
    pname = "hyprland";
    version = "e225d949e7f6db926d80ed50a74da2436ac28b85";
    src = fetchFromGitHub ({
      owner = "vaxerski";
      repo = "hyprland";
      rev = "e225d949e7f6db926d80ed50a74da2436ac28b85";
      fetchSubmodules = false;
      sha256 = "sha256-Ae6Kes+NT4tnlz/midP15HN5SxCUhqwowFyVRo8o6ck=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "f3d7aa960b29dda7a5ace7a22ae6de33e2acdcaa";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "f3d7aa960b29dda7a5ace7a22ae6de33e2acdcaa";
      fetchSubmodules = false;
      sha256 = "sha256-SWeo/j220itdFISfumdtuTp+mPKN2FqLmaBBgWy3SCk=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "e6eb470935c5ade6e4b48dd0b678cee32497798e";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "e6eb470935c5ade6e4b48dd0b678cee32497798e";
      fetchSubmodules = false;
      sha256 = "sha256-IkmNNYyV3eRAqTdh19d1hgNWtENmlMD5qYAGs34T3ZU=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-133-gd4563ce";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-133-gd4563ce-1_all.deb";
      sha256 = "sha256-EaixtvVxHD67Pz5dp4erTx/WPBjM4o+SQsekEjf9QN4=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-880";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-880-1_all.deb";
      sha256 = "sha256-mqEY7ssVURwOib5I/nTun0t4EqaJYURbUjrLrKv7R/g=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.6189";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.6189.tar.bz2";
      sha256 = "sha256-AvQ+P5qJXtEjeJUXlwOJw/mVKHqBWLV1aendEDNadRk=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.6189";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.6189-1_all.deb";
      sha256 = "sha256-Odr1OgMl2gET6FDV4Gam9L50TAMwkUPMqA1K7TWEnt8=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.1-686-gbfcd5d47";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.1-686-gbfcd5d47-1_all.deb";
      sha256 = "sha256-9RRfw2wreCebLbPj3xPTOdD4vDQ4Qa3ku34l1EYBXNU=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "e413822ae1364e9ff182aeec1d149b0ecef22e8c";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "e413822ae1364e9ff182aeec1d149b0ecef22e8c";
      fetchSubmodules = false;
      sha256 = "sha256-FEQQUJcjCuH+FSl2F2sh9xAsDR1o1p+OAjMfkeLh7p0=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
      fetchSubmodules = false;
      sha256 = "sha256-8v9ytywv2+/qqN94g44vHMGsbKueYSDXq76wo95pSFE=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  matrix-appservice-discord = {
    pname = "matrix-appservice-discord";
    version = "v1.0.0";
    src = fetchFromGitHub ({
      owner = "Half-Shot";
      repo = "matrix-appservice-discord";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-hZQ+3FDRWNGsnaHblnB2p6Inf9ZMrbB2jmgR2rskil0=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "102.0.1245.14";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_102.0.1245.14-1_amd64.deb";
      sha256 = "sha256-NPIGT0bl380tCS+Q1thhSqzczqwebZShFyGkv+bfSYE=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "103.0.1255.0";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_103.0.1255.0-1_amd64.deb";
      sha256 = "sha256-WMxnwtwHDxfJAKM/GLHKBGEEtXUQls93lY5TJdXAJ5Y=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "086b2457e8b769d6af44917759403f76b8b3b90e";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "086b2457e8b769d6af44917759403f76b8b3b90e";
      fetchSubmodules = false;
      sha256 = "sha256-WvDS1z33/j8uXMNFGqZ8D0kRnCqhKzgtXdMVOoo9vxg=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.34.1";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.34.1.tar.gz";
      sha256 = "sha256-9uVYRaUke9BbTrT4PTbc1NksywAAbDNge36ZVV9AEP8=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.32.3";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.32.3.tar.gz";
      sha256 = "sha256-GyYNcUXSNOsM+NYgOZxGXlescCUAAZgd6fRpX6XWENA=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "2ccac2afd1f3b28f573ec314e61be034858fedc2";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "2ccac2afd1f3b28f573ec314e61be034858fedc2";
      fetchSubmodules = false;
      sha256 = "sha256-v51No7tILsbwj3yMuonjiyw4gxUpdLRh0brADswM3Mk=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "d8e7e0f6c2eac98d91572217b6dfcabd1b473adc";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "d8e7e0f6c2eac98d91572217b6dfcabd1b473adc";
      fetchSubmodules = false;
      sha256 = "sha256-otk7KFW3XC0g+6sDEL7kOpH2w/YDbireicFSBTe8hg0=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-fk7863uhJAdbBGOjfcdbXFiznDpUPX49ZEB57bhdCUY=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "35481bdb4d8120991cbf95dfea68f8b4373d9bd5";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "35481bdb4d8120991cbf95dfea68f8b4373d9bd5";
      fetchSubmodules = false;
      sha256 = "sha256-vlpOEeE/mTOSAFEzOj/z/JzdJhdz0GYZ3/GdkjdukOw=";
    });
    cargoLock = {
      lockFile = ./ouch-35481bdb4d8120991cbf95dfea68f8b4373d9bd5/Cargo.lock;
      outputHashes = { };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "cd50596f0ed81c0aa28cefed62176bd6f050a1c6";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "cd50596f0ed81c0aa28cefed62176bd6f050a1c6";
      fetchSubmodules = false;
      sha256 = "sha256-e0Zd/kVqRiYUL6afsp4+JHKSe0qtNLyBE2s6Nem4A1I=";
    });
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.43.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.43.1.tar.gz";
      sha256 = "sha256-80YzAryzGTyy2GTbfYaLBlRWEnJX+/ECjTNz2vv01uU=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "8c7e99acd942bcda8563cad4eac03961a322a3da";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "8c7e99acd942bcda8563cad4eac03961a322a3da";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dS4cbF628RnxaNvLLsMSuC5wOm5ccTg72IjiTfSU7zQ=";
    };
  };
  pure = {
    pname = "pure";
    version = "5b458ba5b75f49a8071d53c343f1a23631f7bced";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "5b458ba5b75f49a8071d53c343f1a23631f7bced";
      fetchSubmodules = false;
      sha256 = "sha256-iuLi0o++e0PqK81AKWfIbCV0CTIxq2Oki6U2oEYsr68=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "908516967acce6d78d02a4b7306f30d09180da6d";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "908516967acce6d78d02a4b7306f30d09180da6d";
      fetchSubmodules = false;
      sha256 = "sha256-ZZ7lut3wYDg4Ry8SE96lCL8gEMf0Btv+cSks/9M6JJs=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
      fetchSubmodules = false;
      sha256 = "sha256-muDz1rFTvWOZGrEzql+VZbs42bS09BREjKS5OpBu2g8=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "011e371e4299abd64f65fe9e8d70c05857090646";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "011e371e4299abd64f65fe9e8d70c05857090646";
      fetchSubmodules = false;
      sha256 = "sha256-pD9bMXEfebjQ7dBzL0lccfhwjuy1M0VYHSdGbHFgCvI=";
    });
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "1e8c22b4a05c7602aa9e51509274ce5ac36a5099";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "1e8c22b4a05c7602aa9e51509274ce5ac36a5099";
      fetchSubmodules = true;
      sha256 = "sha256-RcTwv+DGS+niuGYSQWAoTk9HAg/WnFV8r6VM0vEc9h4=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "31a40538dc2c2bb5868c786677343e405feeccb0";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "31a40538dc2c2bb5868c786677343e405feeccb0";
      fetchSubmodules = false;
      sha256 = "sha256-mbn0sNS+SC0w/42Z5Ioo8OQWFpY9NdCyEnnjLC9y9OI=";
    });
    cargoLock = {
      lockFile = ./rustdesk-31a40538dc2c2bb5868c786677343e405feeccb0/Cargo.lock;
      outputHashes = {
        "parity-tokio-ipc-0.7.3" = "sha256-Ji/q7RQDznFs+m4AHH1IEL1TMqqCtH4Z5DY6sjcu/T0=";
        "rdev-0.5.0" = "sha256-O+jbA8GS9KVZR/i840+mfQ9LZ3Qtf/XBbV/Mkqn5C/g=";
        "sciter-rs-0.5.57" = "sha256-ZZnZDhMjK0LjgmK0da1yvB0uoKueLhhhQtzmjoN+1R0=";
        "confy-0.4.0" = "sha256-e91cvEixhpPzIthAxzTa3fDY6eCsHUy/eZQAqs7QTDo=";
        "rust-pulsectl-0.2.12" = "sha256-8jXTspWvjONFcvw9/Z8C43g4BuGZ3rsG32tvLMQbtbM=";
        "tokio-socks-0.5.1" = "sha256-inmAJk0fAlsVNIwfD/M+htwIdQHwGSTRrEy6N/mspMI=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "2e539cf5bfc60b1463519de2566422464877992d";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "2e539cf5bfc60b1463519de2566422464877992d";
      fetchSubmodules = false;
      sha256 = "sha256-MMPmTEMYghf2A+rQF5pJaLTb2NyXpV3HKx20g7o/deg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
      fetchSubmodules = false;
      sha256 = "sha256-FfbYQrHndU7rtI8CKK7wtn3pdufBSiXUgefozCja4Do=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-lXCITuDQmwNHj9vq6Wumwh8sdrFp95AGXujVP/Q9rNY=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-4ITyRyc8kVE+tNOSeniu5fm/xo2vebszszCvy+f/t9w=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-ZXGWbBH3SqZKRu83dPyDdvgi5Y0beFv1wsiZIOdbDZQ=";
    };
  };
  snui = {
    pname = "snui";
    version = "8f6fe4980f70686f61be904c4501187de67366ff";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "8f6fe4980f70686f61be904c4501187de67366ff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-F7NIaeRUdnNEBS3tMwoaXxk2cTGoydyMcWKeR2lGojQ=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "1e413dd572207a80611628fd5c1a836a89fac1e5";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "1e413dd572207a80611628fd5c1a836a89fac1e5";
      fetchSubmodules = false;
      sha256 = "sha256-uxDEl9yLvx98r+NEysxJEGk42gGZYw3GXMjUZMPW+2Y=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "f532263e90922bf53af7ecdd107e14e003992de6";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "f532263e90922bf53af7ecdd107e14e003992de6";
      fetchSubmodules = false;
      sha256 = "sha256-E2RsYmAAgvLvuJaJ81jDstdwiTnhxQBDvK9fRn8/4XE=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.84.716.gc5f8b819";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_60.snap";
      sha256 = "sha256-ho3WjGNjmHsERzC3FLgliuVSQWK2F5ec0ddQSfq6oyI=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "ae6dac7a54f899316674ba57ce4a0f9890cd2b1c";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "ae6dac7a54f899316674ba57ce4a0f9890cd2b1c";
      fetchSubmodules = false;
      sha256 = "sha256-UYQ5XiG18bQO4UfLDa7Nn2BQGk0jo0+tSP1lL79cY8k=";
    });
    cargoLock = {
      lockFile = ./spotifyd-ae6dac7a54f899316674ba57ce4a0f9890cd2b1c/Cargo.lock;
      outputHashes = { };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "7c0011cf91e87c30c2a630fee915ead58ef9dcf5";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "7c0011cf91e87c30c2a630fee915ead58ef9dcf5";
      fetchSubmodules = false;
      sha256 = "sha256-7RVyjbBZ4svHXKJV9Ljh6Lf5+Ry/VUUcChwEvk4oVK4=";
    });
  };
  supergfxctl = {
    pname = "supergfxctl";
    version = "7eabe91507764927768d2f48bac78b03fa8c77a9";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl";
      rev = "7eabe91507764927768d2f48bac78b03fa8c77a9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-EqwUsSk/Rq60q3wWzR3ONNlfisdURHVqFHNiXAJ2yi0=";
    };
    cargoLock = {
      lockFile = ./supergfxctl-7eabe91507764927768d2f48bac78b03fa8c77a9/Cargo.lock;
      outputHashes = { };
    };
  };
  sway-borders = {
    pname = "sway-borders";
    version = "5734188fd623f4088892ac3ee6a178d98a6db633";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "5734188fd623f4088892ac3ee6a178d98a6db633";
      fetchSubmodules = false;
      sha256 = "sha256-DXr8+x98eogx0UhuRG1SQwKI7FL1tJPymsUokFaIjNc=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  tailscale = {
    pname = "tailscale";
    version = "3222bce02d02251b1e6b62c7df411d94b0baf39e";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "3222bce02d02251b1e6b62c7df411d94b0baf39e";
      fetchSubmodules = false;
      sha256 = "sha256-kNbzctq7UIbUpQkSRDCGLiMb/4yxqST0lfx2Lzam3GQ=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "64347899f5c60ccc3a7c5ebfa193364b918a38ef";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "64347899f5c60ccc3a7c5ebfa193364b918a38ef";
      fetchSubmodules = false;
      sha256 = "sha256-o4Tyh0qQe9nLl8C5mt9ltnsNqCHjr2TLc78joS+pLsA=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.5.00.10453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.10453_amd64.deb";
      sha256 = "sha256-fLVw2axSMetuaoRzjg+x4DRYY8WP5TQbL7LbfF6LFfA=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "44fcf582fc94ff5d5f4c24cfa0429540e3fe4164";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-i+ySCz3gkQ7y1K+LxbfvZooPL1uWb/k6VOW50YH35h8=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "247b5d791f1a9dfb011f13ed99ff7a61d838a0d7";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "247b5d791f1a9dfb011f13ed99ff7a61d838a0d7";
      fetchSubmodules = false;
      sha256 = "sha256-ayrNAwt9LSX0tzYlQHMmdalA1nI4pgehlPl2Ou3JbWc=";
    });
  };
  ultimmc = {
    pname = "ultimmc";
    version = "66bb7105db93e0977bb64a59a12b001f780e0566";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "66bb7105db93e0977bb64a59a12b001f780e0566";
      fetchSubmodules = true;
      sha256 = "sha256-t/R3BBRy2orzUuh537xMPwORHmhQy4aGe96e77CVzZs=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.24.0";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.24.0";
      fetchSubmodules = false;
      sha256 = "sha256-zeMVdsTSp1z8cwebU2N6w7436N8CcI7PzNedDOSvEx4=";
    });
    cargoLock = {
      lockFile = ./vaultwarden-1.24.0/Cargo.lock;
      outputHashes = {
        "rocket-0.5.0-dev" = "sha256-sZL6GtLrfDy0ePix2UxZTdpFQvvc0G/Q+7qbCLGknqY=";
        "job_scheduler-1.2.1" = "sha256-b0jIKAHVrQNdZdlq+5kfGAOsi8bHu20QDtQaWTuJYtU=";
        "devise-0.3.0" = "sha256-crnEOKK7FiuIs55mOKgNfb3mNzr3QLI0icPPuG+xKVI=";
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2.28.1";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2.28.1/bw_web_v2.28.1.tar.gz";
      sha256 = "sha256-xHf+lIoHRp5wkmwZSs4MfRmIKI0Yy3mf6/Ot8qvpLCQ=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  waydroid = {
    pname = "waydroid";
    version = "d0f96e44cc60f7fee2d338e28a44961984f45c89";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "d0f96e44cc60f7fee2d338e28a44961984f45c89";
      fetchSubmodules = false;
      sha256 = "sha256-jxv+rWApuIR5l+YN1KMguUKAjzwOTP7nafEgUSUC+Wk=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "5a3455aec186fa69dfd05b03bebe7141af209967";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "5a3455aec186fa69dfd05b03bebe7141af209967";
      fetchSubmodules = false;
      sha256 = "sha256-6V4fIoFB0fuCEu1Rj8QWGDNdgystrD/gefjbshvxVsw=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "e31ad8ac62aff5382f0c3b930547e862cba18066";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "e31ad8ac62aff5382f0c3b930547e862cba18066";
      fetchSubmodules = false;
      sha256 = "sha256-ivr5LSbU521MSsiqPOHb+ykhtdLyyol+/L8ko0ZAu/E=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "ec2f88b8ef7ee47f8544f6dd420cf755bad03d2b";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "ec2f88b8ef7ee47f8544f6dd420cf755bad03d2b";
      fetchSubmodules = false;
      sha256 = "sha256-gq8sI9M86mEfLdOr5TjXiZI38Va5VcplBrXNpgFpW3M=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2449.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2449.0-linux-x64.zip";
      sha256 = "sha256-vsr6eymKqU2Y6HM4DPHnUfVkB2BQ1HSSWvk1tNhUA5Y=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xdg-desktop-portal = {
    pname = "xdg-desktop-portal";
    version = "9de515017f3273b7ec6adf458e8d10dd2b61bb51";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal";
      rev = "9de515017f3273b7ec6adf458e8d10dd2b61bb51";
      fetchSubmodules = false;
      sha256 = "sha256-s5JW9/UN7jg6+ogedC++UGTVXr1kngokFiB0Ri0nRm4=";
    });
  };
  xdg-desktop-portal-gtk = {
    pname = "xdg-desktop-portal-gtk";
    version = "7c7bbf922b63b9d536a2293c0587cb20df01eb2d";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal-gtk";
      rev = "7c7bbf922b63b9d536a2293c0587cb20df01eb2d";
      fetchSubmodules = false;
      sha256 = "sha256-I9xQgiE3lNb2vRodO5R1y40lqoOKzALskrVePidant4=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "d3468537b9748756350c9ab89d2b639cebeeccbc";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "d3468537b9748756350c9ab89d2b639cebeeccbc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wK0+asG9oOuZmDn2EIvL/EBcazHG05KgoUGUHPju+sk=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "8c8bbb903410e39140727867a26bbe501f77de8f";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "8c8bbb903410e39140727867a26bbe501f77de8f";
      fetchSubmodules = false;
      sha256 = "sha256-csOGWw8o+0adUzFOrczaynNnuhr0S0gSLTFP7fRlkdg=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "7cdcdfea08ad9d63466286a6f94783cbf5fc3717";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "7cdcdfea08ad9d63466286a6f94783cbf5fc3717";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Q/y0egweDnd3mmu7WewS84XSnyAL19lU1dE+oFHbwxo=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
      fetchSubmodules = false;
      sha256 = "sha256-maXXGCqB8dkGO8956hsKSwM4HQdYn6z1jBFENQ9sKcA=";
    });
  };
  yubikey-agent = {
    pname = "yubikey-agent";
    version = "6d9db9c29100daacbe83e74653c79c94acc5958d";
    src = fetchFromGitHub ({
      owner = "FiloSottile";
      repo = "yubikey-agent";
      rev = "6d9db9c29100daacbe83e74653c79c94acc5958d";
      fetchSubmodules = false;
      sha256 = "sha256-mrdZcKD61S94ZkVH93SJhozmsXW/22ho08WMCrDEwhs=";
    });
  };
  yubikey-guide = {
    pname = "yubikey-guide";
    version = "dc29279197bbf866b63976395d2c69b1a95ad088";
    src = fetchFromGitHub ({
      owner = "drduh";
      repo = "YubiKey-Guide";
      rev = "dc29279197bbf866b63976395d2c69b1a95ad088";
      fetchSubmodules = false;
      sha256 = "sha256-MMcfiJ31SsrJdPCYn+5MuUxqLJzhY4VeqOS02T9AlL8=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.10.4.2845";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.10.4.2845/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-9gspydrGaEjzAM0nK1u0XNm07HTupJ2wnPxCFWy+Nts=";
    };
  };
}
