# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.108.0-b.3";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.3/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-TtY02wSwi5VT5U9xrwyWgWNN+ueCRv4OaUayzhAPy0A=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.108.0-b.3";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.3/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-g0kcAwm7DPDqMIEYdNNdlDZd2SAM2b3Vap/NPhVBaTs=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.108.0-b.3";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.3/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-932yIcanN0KIqs6za3J6utFO5W5Ao9KPdMZYVqBTF9M=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.108.0-b.3";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.3/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-LizZkEEVEi5iUv6omVMzJEMmOVoNiVDmbO2rAIs5hss=";
    };
  };
  adl = {
    pname = "adl";
    version = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
      fetchSubmodules = false;
      sha256 = "sha256-huGpDtkWrhZyKDNKXat8T3qtAyMjBaq8HFd1w1ThUVk=";
    });
  };
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "b3590f4ce1f570be34aa5d132840d4a7122c67b2";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "b3590f4ce1f570be34aa5d132840d4a7122c67b2";
      fetchSubmodules = false;
      sha256 = "sha256-KdxghSvkIsxqADzIZL8aSw8azYvcPF0mpw78uEWG2rs=";
    });
    cargoLock = {
      lockFile = ./age-plugin-yubikey-b3590f4ce1f570be34aa5d132840d4a7122c67b2/Cargo.lock;
      outputHashes = { };
    };
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "941eef9d5435b38775911d5c773a7dfda8adfea8";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "941eef9d5435b38775911d5c773a7dfda8adfea8";
      fetchSubmodules = false;
      sha256 = "sha256-k9zwrmXRG93BVExtJkZe7w8H1oOiI2aAHEkllqsv2jw=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  argonone-fancontrold = {
    pname = "argonone-fancontrold";
    version = "b6b960eb492224012680f56e3c6fba13502e542c";
    src = fetchFromGitHub ({
      owner = "mgdm";
      repo = "argonone-utils";
      rev = "b6b960eb492224012680f56e3c6fba13502e542c";
      fetchSubmodules = false;
      sha256 = "sha256-v098KH8TgzGgCc7+59SVWy19xW456eXX/BDdt9zzVhk=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "0d83307b14760c9231f67e6f1e99bfbd7b586650";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "0d83307b14760c9231f67e6f1e99bfbd7b586650";
      fetchSubmodules = false;
      sha256 = "sha256-Df2D2eBifkZpFklPBbE94AvgAUM/NUAAiuqUzp67Hdo=";
    });
  };
  avizo = {
    pname = "avizo";
    version = "d5c416aa7ac46660cd943f01ecfab6e29cb5e8c3";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "d5c416aa7ac46660cd943f01ecfab6e29cb5e8c3";
      fetchSubmodules = false;
      sha256 = "sha256-BRtdCOBFsKkJif/AlnF7N9ZDcmA+878M9lDQld+SAgo=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "9895aeb0d58f1f9bdf460fe88c43828851f48c6e";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "9895aeb0d58f1f9bdf460fe88c43828851f48c6e";
      fetchSubmodules = false;
      sha256 = "sha256-vi9sdDXTMsjUZNtNyaayw8YUFUjT7+2+BIAEewEJy7Q=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  bling = {
    pname = "bling";
    version = "718ac6da7a9a6a61b17bef63316ce6978adda318";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "718ac6da7a9a6a61b17bef63316ce6978adda318";
      fetchSubmodules = false;
      sha256 = "sha256-uhV7kK6auO52GTrMtrgtVkm+eDeuJUyb7WjPu7ZfVLk=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "8f5e166287e60062df7a07411a5659ddef04f7ae";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "8f5e166287e60062df7a07411a5659ddef04f7ae";
      fetchSubmodules = false;
      sha256 = "sha256-X4AQMwpjECG2Wo5lZUGaWH4yJqEAqUN/kz/AsV8bsEA=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "741b0502ee7cb0ecbd6dd0517c4f186729f52718";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "741b0502ee7cb0ecbd6dd0517c4f186729f52718";
      fetchSubmodules = false;
      sha256 = "sha256-4hNQ2z31nLY4RNPX1GX9QOFSYPGU358RfcWrTVujSXM=";
    });
  };
  cinny = {
    pname = "cinny";
    version = "1.7.0";
    src = fetchurl {
      url = "https://github.com/ajbura/cinny/releases/download/v1.7.0/cinny-v1.7.0.tar.gz";
      sha256 = "sha256-MyVchLYLgqF5J7sm/Wdydqk7x+h0XGGXicAC3/9qYwQ=";
    };
  };
  conduit = {
    pname = "conduit";
    version = "36a6d724fe00a8da3219ea42d0776be7a9694e8a";
    src = fetchgit {
      url = "https://gitlab.com/famedly/conduit";
      rev = "36a6d724fe00a8da3219ea42d0776be7a9694e8a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Porzo24bUA0XxfOKV2GxCFU3Rm5dzzPgPn8pg9tQ664=";
    };
    cargoLock = {
      lockFile = ./conduit-36a6d724fe00a8da3219ea42d0776be7a9694e8a/Cargo.lock;
      outputHashes = {
        "reqwest-0.11.9" = "sha256-wH/q7REnkz30ENBIK5Rlxnc1F6vOyuEANMHFmiVPaGw=";
        "ruma-0.4.0" = "sha256-gRhhGWpMiLeA8TNgBMsFEBky1TISr/GXNxLpTXLgUQE=";
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  conduit-toolbox = {
    pname = "conduit-toolbox";
    version = "0e0a025c37f2c07f284eaf85d20acf2dc91c46d7";
    src = fetchFromGitHub ({
      owner = "ShadowJonathan";
      repo = "conduit_toolbox";
      rev = "0e0a025c37f2c07f284eaf85d20acf2dc91c46d7";
      fetchSubmodules = false;
      sha256 = "sha256-uXV+djqXe6u+ah+VbOIHQoZ2DSXlIVuQxItHZkK5GqU=";
    });
    cargoLock = {
      lockFile = ./conduit-toolbox-0e0a025c37f2c07f284eaf85d20acf2dc91c46d7/Cargo.lock;
      outputHashes = {
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.134";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.134/discord-canary-0.0.134.tar.gz";
      sha256 = "sha256-HyJa6lGcKMPKWffO/pnNcn8fDTJj6O4J8Y5RA23a1kM=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "d30c44a6a8d1eb49ffff773f12e08855cf585f41";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "d30c44a6a8d1eb49ffff773f12e08855cf585f41";
      fetchSubmodules = false;
      sha256 = "sha256-vwZDvwLYvbGkYezxQRKEX1+JuFrVMAaLl/j2c7VSjsE=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "9ae8b0a3f24489da62291cfee0561ae9cf214c15";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "9ae8b0a3f24489da62291cfee0561ae9cf214c15";
      fetchSubmodules = false;
      sha256 = "sha256-JiBpocumhdPXDx4sYJaelfm/7UheHB08sEkgi6hwTfs=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "9f5a988eca3f5cc9863c05405b90b45603eb08e7";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "9f5a988eca3f5cc9863c05405b90b45603eb08e7";
      fetchSubmodules = false;
      sha256 = "sha256-yzKIx9LNMRsjSUSvjt0Xn+HNuMqNRr12/bf+6ACnNTU=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "00846d3b1547aa80877c42108b7950d94c2aa8b4";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "00846d3b1547aa80877c42108b7950d94c2aa8b4";
      fetchSubmodules = false;
      sha256 = "sha256-AxJBpoiBnb+5Pq/h4giOYAeLlvOtAJT5sCwzPEKo7w4=";
    });
  };
  duf = {
    pname = "duf";
    version = "e58ecb8b739c0fdd6a362a17b00a20f4f2f654a8";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "e58ecb8b739c0fdd6a362a17b00a20f4f2f654a8";
      fetchSubmodules = false;
      sha256 = "sha256-wpw45laxYLc+0hjHjpEMKYlh22JbH0GbT8nN2L3R18s=";
    });
  };
  eww = {
    pname = "eww";
    version = "fb0e57a0149904e76fb33807a2804d4af82350de";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "fb0e57a0149904e76fb33807a2804d4af82350de";
      fetchSubmodules = false;
      sha256 = "sha256-oAbB9aW/nqg02peqGEfETOGgeXarI6ZcAZ6DzDXbOSE=";
    });
    cargoLock = {
      lockFile = ./eww-fb0e57a0149904e76fb33807a2804d4af82350de/Cargo.lock;
      outputHashes = { };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "2d920dc04c3cb83689dc9b3e75f931b3e0835753";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "2d920dc04c3cb83689dc9b3e75f931b3e0835753";
      fetchSubmodules = false;
      sha256 = "sha256-LuZKv69jAzoHGDFU3u0ehvYFUQPNyvJLGZQZf6mUA+A=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "a6144df367bbb7ba6174d45e00164ac79080f9c7";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "a6144df367bbb7ba6174d45e00164ac79080f9c7";
      fetchSubmodules = false;
      sha256 = "sha256-BOaIALkKVF6BxSJUqR3B049up8DvAXQrk1bAeT40YAo=";
    });
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = { };
    };
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "369c53c51013f8166182c81e43b37365c3b63a11";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "369c53c51013f8166182c81e43b37365c3b63a11";
      fetchSubmodules = false;
      sha256 = "sha256-cpKCC7x3ssRIcmWibyktbtaftFk2vGxS8k+yUWGjEIo=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "df664b1f18a9c630ccd884f8ff698abf6cbb1578";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "df664b1f18a9c630ccd884f8ff698abf6cbb1578";
      fetchSubmodules = false;
      sha256 = "sha256-7OB6JnKjeZm8oVtLoNOFByazIOc8dYeWlWlBoazRDLg=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "96ba9f9ae00d4e3df028f8312f55ef50d8bcf738";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "96ba9f9ae00d4e3df028f8312f55ef50d8bcf738";
      fetchSubmodules = false;
      sha256 = "sha256-0hIHnc3fVYlKxuQMYiEFV6FQwCJfbLeliZ4GmVc4/2I=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-121-g27323fe";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-121-g27323fe-1_all.deb";
      sha256 = "sha256-/1BEXPJkBSNvXpHJZS1G+nzhofxQ1XcWYPcj9xJ5wD0=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-864";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-864-1_all.deb";
      sha256 = "sha256-RYUFQPm7KqFZcDCGU+sSm8SuikLbofIbh9usyva7l2I=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.5917";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.5917.tar.bz2";
      sha256 = "sha256-yC776hWQrt1k9S4gGzYT/EplDRlV8Qzd1pYzIkhSZnU=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.5917";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.5917-1_all.deb";
      sha256 = "sha256-+hFXWx23yNOjg0ouK6Om46ZJ8gpKR7+/g9umQP5+HRY=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.1-636-g5842a75f";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.1-636-g5842a75f-1_all.deb";
      sha256 = "sha256-SujT2j2Usvphdc7Cq4O83i81gtBRHiNY+9ex4MTsGRE=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "e413822ae1364e9ff182aeec1d149b0ecef22e8c";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "e413822ae1364e9ff182aeec1d149b0ecef22e8c";
      fetchSubmodules = false;
      sha256 = "sha256-FEQQUJcjCuH+FSl2F2sh9xAsDR1o1p+OAjMfkeLh7p0=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
      fetchSubmodules = false;
      sha256 = "sha256-d8iBxfHkryy5lM5myWPo0a3zgUZQrklYazCSCyKKDGs=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  matrix-appservice-discord = {
    pname = "matrix-appservice-discord";
    version = "v1.0.0";
    src = fetchFromGitHub ({
      owner = "Half-Shot";
      repo = "matrix-appservice-discord";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-hZQ+3FDRWNGsnaHblnB2p6Inf9ZMrbB2jmgR2rskil0=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "99.0.1150.30";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_99.0.1150.30-1_amd64.deb";
      sha256 = "sha256-civyzOBn5dbeYyXiyioZkGkc37ZTjN+G1p+d2I3zK24=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "100.0.1181.0";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_100.0.1181.0-1_amd64.deb";
      sha256 = "sha256-5gdynFtvGJrsBgQVu+JTDjotic6IgpYdizoAW6xh3Js=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "647d760db351370bc795521c0a3b07a14cf74eea";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "647d760db351370bc795521c0a3b07a14cf74eea";
      fetchSubmodules = false;
      sha256 = "sha256-mCIavioX+R6DkER3Hsjrgz+WL7qhsKcLsk9oh8DUvZk=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.33.1";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.33.1.tar.gz";
      sha256 = "sha256-+ui6PYjFVf1/s935HDToJxY4I/Jp2EaeAmJ99Q9Lp20=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.31.2";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.31.2.tar.gz";
      sha256 = "sha256-LRQpvyOxYKZPUkXHOb85f4BDUU8peyD9/HJJpjIJESo=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
      fetchSubmodules = false;
      sha256 = "sha256-ZJmnUU81hg34JHkA82BfapFGqKrhqFk6wCM2eO2RaVs=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "d05059808656b727851c01dfd4ea56ca46151a75";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "d05059808656b727851c01dfd4ea56ca46151a75";
      fetchSubmodules = false;
      sha256 = "sha256-YhCMOktfsSb7GrKA8reZb+QHcNS/Lpd0hCaPqnWvL7w=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-MAxQkdR40YUDl7z0OYbuwiueOoB2JuYikIu11CqiAto=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "4649bbc5d38848e78908be7503494946b434fb13";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "4649bbc5d38848e78908be7503494946b434fb13";
      fetchSubmodules = false;
      sha256 = "sha256-iUq2zwWR+F6Dgf5ZDXSpUV7KtXMezMPpmfz9E6ABzn4=";
    });
    cargoLock = {
      lockFile = ./ouch-4649bbc5d38848e78908be7503494946b434fb13/Cargo.lock;
      outputHashes = { };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "aa316aa3601a4f3ce9c1ca79932218ab574e61a7";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "aa316aa3601a4f3ce9c1ca79932218ab574e61a7";
      fetchSubmodules = false;
      sha256 = "sha256-Yb69LTu45HxBWoD/T9Uj6b1lNn7hHzIEjcn73PMMEz0=";
    });
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.42.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.42.0.tar.gz";
      sha256 = "sha256-qpq8nsNQTGUvAh6TQtqj4SJZjye99+ZTyjEFgU4LANY=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "2e39912790e54bb18acd4fe25dbd017052ef5aff";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "2e39912790e54bb18acd4fe25dbd017052ef5aff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-hPlHUBSyXaYqL5ffRteTLFCwRxeBwvvdrdhUyAEeGkc=";
    };
  };
  pure = {
    pname = "pure";
    version = "5b458ba5b75f49a8071d53c343f1a23631f7bced";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "5b458ba5b75f49a8071d53c343f1a23631f7bced";
      fetchSubmodules = false;
      sha256 = "sha256-iuLi0o++e0PqK81AKWfIbCV0CTIxq2Oki6U2oEYsr68=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "908516967acce6d78d02a4b7306f30d09180da6d";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "908516967acce6d78d02a4b7306f30d09180da6d";
      fetchSubmodules = false;
      sha256 = "sha256-ZZ7lut3wYDg4Ry8SE96lCL8gEMf0Btv+cSks/9M6JJs=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
      fetchSubmodules = false;
      sha256 = "sha256-muDz1rFTvWOZGrEzql+VZbs42bS09BREjKS5OpBu2g8=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "35312feab67b54f29ccfe2c59c82a276f6896616";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "35312feab67b54f29ccfe2c59c82a276f6896616";
      fetchSubmodules = false;
      sha256 = "sha256-z2lPddNHItURMO8va1HGY5pBtvQirxhJMErJ/rpVnwM=";
    });
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "396b13f5a83bfc4c54a8fccdcf3fb4ab4e2cfd0c";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "396b13f5a83bfc4c54a8fccdcf3fb4ab4e2cfd0c";
      fetchSubmodules = true;
      sha256 = "sha256-KhRvUC2vD11D800+CUJFQs9qFiwt9TU9/kVOT4gcVM8=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "bf0270323c3565297d8306397c2b03bc092c1bc6";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "bf0270323c3565297d8306397c2b03bc092c1bc6";
      fetchSubmodules = false;
      sha256 = "sha256-OZNVyhQQQ4sRdUkaerHPCeyBSRIy/kMQwQkkC1j2mtg=";
    });
    cargoLock = {
      lockFile = ./rustdesk-bf0270323c3565297d8306397c2b03bc092c1bc6/Cargo.lock;
      outputHashes = {
        "systray-0.4.1" = "sha256-p1PMr/8oS6zHx4+Ng4zCqt0xZ57cq3wAu6/agyWq5Jw=";
        "parity-tokio-ipc-0.7.3" = "sha256-Ji/q7RQDznFs+m4AHH1IEL1TMqqCtH4Z5DY6sjcu/T0=";
        "libappindicator-0.6.1" = "sha256-JGnnZrcwbh8WJ6+/4bYhfD3HvgF2C7XaaGb6TaMRWdw=";
        "rdev-0.5.0" = "sha256-bkSke7HW2btBCc8+DayeWSTHLRlGNl1+QKTMRUYA4hg=";
        "cpal-0.13.4" = "sha256-Gs1cqYJP92Zy8Fnu3wGQ9+p5oIkCkOp9v++8ocFSNiU=";
        "sciter-rs-0.5.57" = "sha256-ZZnZDhMjK0LjgmK0da1yvB0uoKueLhhhQtzmjoN+1R0=";
        "tokio-socks-0.5.1" = "sha256-inmAJk0fAlsVNIwfD/M+htwIdQHwGSTRrEy6N/mspMI=";
        "confy-0.4.1" = "sha256-5QwA4YfEEE6QqEEUJ3+C37UbUf88NYds38kIthVSo5Y=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
        "rust-pulsectl-0.2.11" = "sha256-CZkvii6pQM5jaR9RK9HDrczxIxZwuahpdVM+UsRLw9s=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "2e539cf5bfc60b1463519de2566422464877992d";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "2e539cf5bfc60b1463519de2566422464877992d";
      fetchSubmodules = false;
      sha256 = "sha256-MMPmTEMYghf2A+rQF5pJaLTb2NyXpV3HKx20g7o/deg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "c257a40ba95f56b5f3830b923b1c56aa055cf8ea";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "c257a40ba95f56b5f3830b923b1c56aa055cf8ea";
      fetchSubmodules = false;
      sha256 = "sha256-OcHVg5iLEcnQlaOrgVOTuK2WRredRG3H9XIArR6aABs=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-uQAY1yMr9SetN/X6UrY2mvfxmIOmNQ0A3IrJQNvi5jM=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-m0eDv1CYCkkm5qgbLioI9+ahf0OXSYh0Gkp61vgMSFk=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-8niJPk3hGfK1USIs9eoxZ6GlM4aZ7ZObmQj2Zomj+Go=";
    };
  };
  snui = {
    pname = "snui";
    version = "ce9642264b0ab8be180f564292c0a7c86357f7c6";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "ce9642264b0ab8be180f564292c0a7c86357f7c6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ywWCZyAEBKJhDCU46LbZLN4DWk1AnDW7kpa7iVu8odE=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "2746629ecb18866a56072223824c762076db19b1";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "2746629ecb18866a56072223824c762076db19b1";
      fetchSubmodules = false;
      sha256 = "sha256-6b90C81zU27ucShcSWOy93KGu7yUq0tOuOzRYH59Nx4=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "07596ca4b2b0798add2d76e4fee7a696f9faf86b";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "07596ca4b2b0798add2d76e4fee7a696f9faf86b";
      fetchSubmodules = false;
      sha256 = "sha256-/PqvH/m7H+s+1qBRvdAvQVRnleuDzLbwUHqtc2qDnB8=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.80.699.gc3dac750";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_58.snap";
      sha256 = "sha256-/gTU2KW2x1o35GN/IKyrRwNrQbkyncBP+omOK1MJCrY=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "85a36961958061fc1571219a0bb916390c239670";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "85a36961958061fc1571219a0bb916390c239670";
      fetchSubmodules = false;
      sha256 = "sha256-dMk5R4vyJdZvOduYkqBqK/xxlBqFbZ6ln6JZ4zF39oQ=";
    });
    cargoLock = {
      lockFile = ./spotifyd-85a36961958061fc1571219a0bb916390c239670/Cargo.lock;
      outputHashes = { };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "343714fbc31210a0c73b7c877081b903952f3402";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "343714fbc31210a0c73b7c877081b903952f3402";
      fetchSubmodules = false;
      sha256 = "sha256-AWK67jN99MeShB1bdwcASsU2Uo0QNL3S8DG3gHQheis=";
    });
  };
  sway-borders = {
    pname = "sway-borders";
    version = "a137ee487f246568f6e67d5799b27abdaa5dca4e";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "a137ee487f246568f6e67d5799b27abdaa5dca4e";
      fetchSubmodules = false;
      sha256 = "sha256-ZS8QXoQ1NDpQd6MyXWgJzPZruhJUvKB+xD4otuWoD6M=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  tailscale = {
    pname = "tailscale";
    version = "f18bb6397be81ad316fbc2905ab315cc1644bb3d";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "f18bb6397be81ad316fbc2905ab315cc1644bb3d";
      fetchSubmodules = false;
      sha256 = "sha256-PLrUfuCJj10eJ7m377CCgD0zo+r4yXeRgQ1gbjf1Z/g=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "64347899f5c60ccc3a7c5ebfa193364b918a38ef";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "64347899f5c60ccc3a7c5ebfa193364b918a38ef";
      fetchSubmodules = false;
      sha256 = "sha256-o4Tyh0qQe9nLl8C5mt9ltnsNqCHjr2TLc78joS+pLsA=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.4.00.26453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.26453_amd64.deb";
      sha256 = "sha256-7hW1d5Oqa3nM2nRNUjLaZwM1q9kxuuKgIPUEOhKauFk=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "ead8010a062db7b2f9bbde1bf81db1d462d991a0";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-igjamulpcD7akYdNniz3ObCnjpPBPeU4rePHcBRLXLw=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "f6a6c23cdede199e076629b641be179a5464f0fc";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "f6a6c23cdede199e076629b641be179a5464f0fc";
      fetchSubmodules = false;
      sha256 = "sha256-n5WKJ6DT38gunnKxTir/GnLtHohCrbeanefZtEI5OeM=";
    });
  };
  ultimmc = {
    pname = "ultimmc";
    version = "66bb7105db93e0977bb64a59a12b001f780e0566";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "66bb7105db93e0977bb64a59a12b001f780e0566";
      fetchSubmodules = true;
      sha256 = "sha256-t/R3BBRy2orzUuh537xMPwORHmhQy4aGe96e77CVzZs=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.24.0";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.24.0";
      fetchSubmodules = false;
      sha256 = "sha256-zeMVdsTSp1z8cwebU2N6w7436N8CcI7PzNedDOSvEx4=";
    });
    cargoLock = {
      lockFile = ./vaultwarden-1.24.0/Cargo.lock;
      outputHashes = {
        "rocket-0.5.0-dev" = "sha256-sZL6GtLrfDy0ePix2UxZTdpFQvvc0G/Q+7qbCLGknqY=";
        "job_scheduler-1.2.1" = "sha256-b0jIKAHVrQNdZdlq+5kfGAOsi8bHu20QDtQaWTuJYtU=";
        "devise-0.3.0" = "sha256-crnEOKK7FiuIs55mOKgNfb3mNzr3QLI0icPPuG+xKVI=";
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2.26.1";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2.26.1/bw_web_v2.26.1.tar.gz";
      sha256 = "sha256-kPeEUZeyoxZ8AGBanUHpT3FS0naIrVCKd9DOEXW7KOI=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  waydroid = {
    pname = "waydroid";
    version = "c2c1ccb39c313e3689735f7c725f28b9f22d0154";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "c2c1ccb39c313e3689735f7c725f28b9f22d0154";
      fetchSubmodules = false;
      sha256 = "sha256-bRDv7WvVf0rLSVZpTKTiP5wuuQSiHorii1Mvxlqrv+g=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "ecf3b62ea61eabe483625fd1cbd476a8fd994952";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "ecf3b62ea61eabe483625fd1cbd476a8fd994952";
      fetchSubmodules = false;
      sha256 = "sha256-Dz19SlBTTCn73rnnU4PpZUbwcIpA6j2ODFYVAwTn7wI=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "73e6e81b81cebbe70bfa8fce071eea8a335d05f8";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "73e6e81b81cebbe70bfa8fce071eea8a335d05f8";
      fetchSubmodules = false;
      sha256 = "sha256-rz8KNwQ8NyVxy3PMtQBKrn1cTHRiYwj7KdTokNAu+Yk=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "081a4b7ffa10b0ad6756ba6c391533357a2725cf";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "081a4b7ffa10b0ad6756ba6c391533357a2725cf";
      fetchSubmodules = false;
      sha256 = "sha256-Kw3Dr7pcwHLhmHEqvtX6bz0rX5f1tWVlcWTZ9ELr0os=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2391.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2391.0-linux-x64.zip";
      sha256 = "sha256-7gH808C67m/s09e4rQUQHb/t+iGVdzW+YzrB1ZxGIdo=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xdg-desktop-portal = {
    pname = "xdg-desktop-portal";
    version = "1cad7379e4d7e502f2cbf742b3d48738ad59a2e6";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal";
      rev = "1cad7379e4d7e502f2cbf742b3d48738ad59a2e6";
      fetchSubmodules = false;
      sha256 = "sha256-LNuXvAGwPq5Daf3M8rCymDbHiMBGvm9C9y0G8Ovh42k=";
    });
  };
  xdg-desktop-portal-gtk = {
    pname = "xdg-desktop-portal-gtk";
    version = "347fcd1f61e126ae77950b5d4b66ad9522aec1f2";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal-gtk";
      rev = "347fcd1f61e126ae77950b5d4b66ad9522aec1f2";
      fetchSubmodules = false;
      sha256 = "sha256-pIeC+dj+VKBCbGU98ITkmPi7BGSjkPnyDMO2KlJOEgI=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qKKb/i67QY/NxZFkJaVRc3hGPjjnRfgpMqGqZ0YNQE8=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "914d8f5e0f469cd0416364dd008e9eea752bf703";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "914d8f5e0f469cd0416364dd008e9eea752bf703";
      fetchSubmodules = false;
      sha256 = "sha256-XJtYZYbmwCrkbB7a533kkI/CcawkmHHSEu4zSznVvEY=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "7d2014e7d523e10623203582b9f573303750f087";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "7d2014e7d523e10623203582b9f573303750f087";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-uErVF/FgbXU4iDyn7boYoly3mF4dMqnZhj7FL4VN4yY=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
      fetchSubmodules = false;
      sha256 = "sha256-maXXGCqB8dkGO8956hsKSwM4HQdYn6z1jBFENQ9sKcA=";
    });
  };
  yubikey-agent = {
    pname = "yubikey-agent";
    version = "205a7ef2554625c7494038600d963123d6311873";
    src = fetchFromGitHub ({
      owner = "FiloSottile";
      repo = "yubikey-agent";
      rev = "205a7ef2554625c7494038600d963123d6311873";
      fetchSubmodules = false;
      sha256 = "sha256-wJpN63KY5scmez6yYFsIr3JLEUB+YSl/XvoatIIeRI0=";
    });
  };
  yubikey-guide = {
    pname = "yubikey-guide";
    version = "fe6434577bce964aefd33d5e085d6ac0008e17ce";
    src = fetchFromGitHub ({
      owner = "drduh";
      repo = "YubiKey-Guide";
      rev = "fe6434577bce964aefd33d5e085d6ac0008e17ce";
      fetchSubmodules = false;
      sha256 = "sha256-HQrS2+yvSXi/XCOzWRIV4S/riKpCvnHTSGZfbYXEmrg=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.9.6.2225";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.9.6.2225/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-o8xC9rMRw9NZHypAXv/7/vNk8ctgZjJcOTJZ6QS/1mc=";
    };
  };
}
