# nvfetcher.toml

[adguardhome-darwin-amd64]
src.github_tag = "AdguardTeam/AdGuardHome"
src.prefix = "v"
fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v$ver/AdGuardHome_darwin_amd64.zip"

[adguardhome-linux-386]
src.github_tag = "AdguardTeam/AdGuardHome"
src.prefix = "v"
fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v$ver/AdGuardHome_linux_386.tar.gz"

[adguardhome-linux-amd64]
src.github_tag = "AdguardTeam/AdGuardHome"
src.prefix = "v"
fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v$ver/AdGuardHome_linux_amd64.tar.gz"

[adguardhome-linux-arm64]
src.github_tag = "AdguardTeam/AdGuardHome"
src.prefix = "v"
fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v$ver/AdGuardHome_linux_arm64.tar.gz"

[adl]
src.git = "https://github.com/RaitaroH/adl"
fetch.github = "RaitaroH/adl"

[age-plugin-yubikey]
src.git = "https://github.com/str4d/age-plugin-yubikey"
fetch.github = "str4d/age-plugin-yubikey"
cargo_lock = "Cargo.lock"

[anbox]
src.git = "https://github.com/anbox/anbox"
fetch.github = "anbox/anbox"
git.fetchSubmodules = true

[anime-downloader]
src.git = "https://github.com/anime-dl/anime-downloader"
fetch.github = "anime-dl/anime-downloader"

[any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
fetch.github = "haslersn/any-nix-shell"

[arkenfox-userjs]
src.git = "https://github.com/arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[avizo]
src.git = "https://github.com/misterdanb/avizo"
fetch.github = "misterdanb/avizo"

[awesome]
src.git = "https://github.com/awesomeWM/awesome"
fetch.github = "awesomeWM/awesome"

[awestore]
src.git = "https://github.com/K4rakara/awestore"
fetch.github = "K4rakara/awestore"

[bling]
src.git = "https://github.com/BlingCorp/bling"
fetch.github = "BlingCorp/bling"

[bottles]
src.git = "https://github.com/bottlesdevs/Bottles"
fetch.github = "bottlesdevs/Bottles"

[caddy]
src.git = "https://github.com/caddyserver/caddy"
fetch.github = "caddyserver/caddy"

[cinny]
src.git = "https://github.com/ajbura/cinny"
fetch.github = "ajbura/cinny"

[conduit]
src.git = "https://gitlab.com/famedly/conduit"
fetch.git = "https://gitlab.com/famedly/conduit"
cargo_lock = "Cargo.lock"

[cups-pdf]
src.webpage = "https://www.cups-pdf.de/src"
src.regex = "cups-pdf_(.*)\\.tar\\.gz\">cups-pdf_"
fetch.url = "https://www.cups-pdf.de/src/cups-pdf_$ver.tar.gz"

[discord-canary]
src.httpheader = "https://discordapp.com/api/download/canary?platform=linux&format=tar.gz"
src.regex = "https://dl-canary.discordapp.net/apps/linux/(\\d+.\\d+.\\d+)/discord-canary-\\d+.\\d+.\\d+.tar.gz"
fetch.url = "https://dl-canary.discordapp.net/apps/linux/$ver/discord-canary-$ver.tar.gz"

[dnscrypt-proxy2]
src.git = "https://github.com/DNSCrypt/dnscrypt-proxy"
fetch.github = "DNSCrypt/dnscrypt-proxy"

[doggo]
src.git = "https://github.com/mr-karan/doggo"
fetch.github = "mr-karan/doggo"

[dribbblish-dynamic-theme]
src.git = "https://github.com/JulienMaille/dribbblish-dynamic-theme"
fetch.github = "JulienMaille/dribbblish-dynamic-theme"

[droidcam]
src.git = "https://github.com/aramg/droidcam"
fetch.github = "aramg/droidcam"

[duf]
src.git = "https://github.com/muesli/duf"
fetch.github = "muesli/duf"

[eww]
src.git = "https://github.com/elkowar/eww"
fetch.github = "elkowar/eww"
cargo_lock = "Cargo.lock"

[fake-background-webcam]
src.git = "https://github.com/fangfufu/Linux-Fake-Background-Webcam"
fetch.github = "fangfufu/Linux-Fake-Background-Webcam"

[flameshot]
src.git = "https://github.com/flameshot-org/flameshot"
fetch.github = "flameshot-org/flameshot"

[flyingfox]
src.git = "https://github.com/akshat46/FlyingFox"
fetch.github = "akshat46/FlyingFox"

[frece]
src.git = "https://github.com/YodaEmbedding/frece"
fetch.github = "YodaEmbedding/frece"
cargo_lock = "Cargo.lock"

[guiscrcpy]
src.git = "https://github.com/srevinsaju/guiscrcpy"
fetch.github = "srevinsaju/guiscrcpy"

[ibus]
src.git = "https://github.com/ibus/ibus/"
fetch.github = "ibus/ibus"

[ibus-bamboo]
src.git = "https://github.com/BambooEngine/ibus-bamboo"
fetch.github = "BambooEngine/ibus-bamboo"

[jibri]
src.webpage = "https://download.jitsi.org/unstable"
src.regex = ".*jibri_(.*)-1_all.*"
fetch.url = "https://download.jitsi.org/unstable/jibri_$ver-1_all.deb"

[jicofo]
src.webpage = "https://download.jitsi.org/unstable"
src.regex = ".*jicofo_(.*)-1_all.*"
fetch.url = "https://download.jitsi.org/unstable/jicofo_$ver-1_all.deb"

[jitsi-meet]
src.webpage = "https://download.jitsi.org/unstable"
src.regex = ".*jitsi-meet-web_(.*)-1_all.*"
fetch.url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-$ver.tar.bz2"

[jitsi-meet-prosody]
src.webpage = "https://download.jitsi.org/unstable"
src.regex = ".*jitsi-meet-prosody_(.*)-1_all.*"
fetch.url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_$ver-1_all.deb"

[jitsi-videobridge2]
src.webpage = "https://download.jitsi.org/unstable"
src.regex = ".*jitsi-videobridge2_(.*)-1_all.*"
fetch.url = "https://download.jitsi.org/unstable/jitsi-videobridge2_$ver-1_all.deb"

[layout-machi]
src.git = "https://github.com/xinhaoyuan/layout-machi"
fetch.github = "xinhaoyuan/layout-machi"

[leonflix]
src.manual = "1.5.50"
fetch.url = "https://leonflix.net/downloads/Leonflix.AppImage"

[libinih]
src.manual = "r53"
fetch.github = "benhoyt/inih"

[light]
src.git = "https://github.com/haikarainen/light"
fetch.github = "haikarainen/light"

[lightcord]
src.git = "https://github.com/Lightcord/Lightcord"
fetch.github = "Lightcord/Lightcord"

[lua-pam]
src.git = "https://github.com/RMTT/lua-pam"
fetch.github = "RMTT/lua-pam"

[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[matrix-appservice-discord]
src.github = "Half-Shot/matrix-appservice-discord"
fetch.github = "Half-Shot/matrix-appservice-discord"

[microsoft-edge-beta]
src.webpage = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/"
src.regex = "microsoft-edge-beta_(.*)-1_amd64\\.deb\">microsoft-edge-beta_"
fetch.url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_$ver-1_amd64.deb"

[microsoft-edge-dev]
src.webpage = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/"
src.regex = "microsoft-edge-dev_(.*)-1_amd64\\.deb\">microsoft-edge-dev_"
fetch.url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_$ver-1_amd64.deb"

[minecraft-wayland]
src.git = "https://github.com/Admicos/minecraft-wayland"
fetch.github = "Admicos/minecraft-wayland"

[netdata]
src.github_tag = "netdata/netdata"
src.prefix = "v"
fetch.url = "https://github.com/netdata/netdata/archive/refs/tags/v$ver.tar.gz"

[netdata-go-d-plugin]
src.github_tag = "netdata/go.d.plugin"
src.prefix = "v"
fetch.url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v$ver.tar.gz"

[nix-zsh-completions]
src.git = "https://github.com/Ma27/nix-zsh-completions"
fetch.github = "Ma27/nix-zsh-completions"

[ntfs2btrfs]
src.git = "https://github.com/maharmstone/ntfs2btrfs"
fetch.github = "maharmstone/ntfs2btrfs"

[nwg-drawer]
src.git = "https://github.com/nwg-piotr/nwg-drawer/"
fetch.github = "nwg-piotr/nwg-drawer"

[ouch]
src.git = "https://github.com/ouch-org/ouch"
fetch.github = "ouch-org/ouch"
cargo_lock = "Cargo.lock"

[paper]
src.git = "https://gitlab.com/snakedye/paper"
fetch.git = "https://gitlab.com/snakedye/paper"
cargo_lock = "Cargo.lock"

[picom]
src.git = "https://github.com/yshui/picom"
fetch.github = "yshui/picom"

[plymouth-themes]
src.git = "https://github.com/adi1090x/plymouth-themes"
fetch.github = "adi1090x/plymouth-themes"

[pmbootstrap]
src.pypi = "pmbootstrap"
fetch.pypi = "pmbootstrap"

[pmbootstrap-test]
src.git = "https://gitlab.com/postmarketOS/pmbootstrap"
fetch.git = "https://gitlab.com/postmarketOS/pmbootstrap"

[pure]
src.git = "https://github.com/sindresorhus/pure"
fetch.github = "sindresorhus/pure"

[pywalfox]
src.pypi = "pywalfox"
fetch.pypi = "pywalfox"

[quibble]
src.git = "https://github.com/maharmstone/quibble"
fetch.github = "maharmstone/quibble"

[rainfox]
src.git = "https://github.com/1280px/rainfox"
fetch.github = "1280px/rainfox"

[redshift]
src.git = "https://github.com/minus7/redshift"
fetch.github = "minus7/redshift"

[retroarch]
src.git = "https://github.com/libretro/retroarch"
fetch.github = "libretro/retroarch"

[rofi-wayland]
src.git = "https://github.com/lbonn/rofi"
fetch.github = "lbonn/rofi"
git.fetchSubmodules = true

[rustdesk]
src.git = "https://github.com/rustdesk/rustdesk"
fetch.github = "rustdesk/rustdesk"
cargo_lock = "Cargo.lock"

[rustdesk-server-oss]
src.git = "https://github.com/rustdesk/rustdesk-server-demo"
fetch.github = "rustdesk/rustdesk-server-demo"

[sddm]
src.git = "https://github.com/sddm/sddm"
fetch.github = "sddm/sddm"

[sddm-chili]
src.git = "https://github.com/MarianArlt/sddm-chili"
fetch.github = "MarianArlt/sddm-chili"

[segue-ui-linux]
src.git = "https://github.com/mrbvrz/segoe-ui-linux"
fetch.github = "mrbvrz/segoe-ui-linux"

[sf-font-compact]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg"

[sf-font-pro]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg"

[sf-mono]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg"

[ny-font]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg"

[snui]
src.git = "https://gitlab.com/snakedye/snui"
fetch.git = "https://gitlab.com/snakedye/snui"

[spicetify-cli]
src.git = "https://github.com/khanhas/spicetify-cli"
fetch.github = "khanhas/spicetify-cli"

[spicetify-themes]
src.git = "https://github.com/morpheusthewhite/spicetify-themes"
fetch.github = "morpheusthewhite/spicetify-themes"

## spotify

[spotify]
src.manual = "1.1.72.439.gc253025e"
fetch.url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_56.snap"

## spotify

[spotifyd]
src.git = "https://github.com/Spotifyd/spotifyd"
fetch.github = "Spotifyd/spotifyd"
cargo_lock = "Cargo.lock"

[steamcompmgr]
src.git = "https://github.com/ChimeraOS/steamos-compositor-plus"
fetch.github = "ChimeraOS/steamos-compositor-plus"

[sway-borders]
src.git = "https://github.com/fluix-dev/sway-borders"
fetch.github = "fluix-dev/sway-borders"

[swaylock-effects]
src.git = "https://github.com/mortie/swaylock-effects"
fetch.github = "mortie/swaylock-effects"

[teams]
src.webpage = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams"
src.regex = "teams_(.*)_amd64\\.deb\">teams_"
fetch.url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_$ver_amd64.deb"

[tailscale]
src.git = "https://github.com/tailscale/tailscale"
fetch.github = "tailscale/tailscale"

[tailscale-systray]
src.git = "https://github.com/mattn/tailscale-systray"
fetch.github = "mattn/tailscale-systray"

[trackma]
src.git = "https://github.com/z411/trackma"
fetch.url = "https://github.com/z411/trackma/archive/master.tar.gz"

[ulauncher]
src.git = "https://github.com/Ulauncher/Ulauncher"
fetch.github = "Ulauncher/Ulauncher"

[ultimmc]
src.manual = "66bb7105db93e0977bb64a59a12b001f780e0566"
fetch.github = "AfoninZ/MultiMC5-Cracked"
git.fetchSubmodules = true

[uniemoji]
src.git = "https://github.com/salty-horse/ibus-uniemoji"
fetch.github = "salty-horse/ibus-uniemoji"

[vaultwarden]
src.github_tag = "dani-garcia/vaultwarden"
fetch.github = "dani-garcia/vaultwarden"
cargo_lock = "Cargo.lock"

[vaultwarden-vault]
src.github_tag = "dani-garcia/bw_web_builds"
src.prefix = "v"
fetch.url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v$ver/bw_web_v$ver.tar.gz"

[ventoy]
src.manual = "1.0.46"
fetch.url = "https://github.com/ventoy/Ventoy/releases/download/v$ver/ventoy-$ver-linux.tar.gz"

[waydroid]
src.git = "https://github.com/waydroid/waydroid"
fetch.github = "waydroid/waydroid"

[wgcf]
src.git = "https://github.com/ViRb3/wgcf"
fetch.github = "ViRb3/wgcf"

[whitesur-gtk-theme]
src.git = "https://github.com/vinceliuice/whitesur-gtk-theme"
fetch.github = "vinceliuice/whitesur-gtk-theme"

[whitesur-icon-theme]
src.git = "https://github.com/vinceliuice/whitesur-icon-theme"
fetch.github = "vinceliuice/whitesur-icon-theme"

[widevine-cdm]
src.webpage = "https://dl.google.com/widevine-cdm/versions.txt"
src.regex = "(.*)"
fetch.url = "https://dl.google.com/widevine-cdm/$ver-linux-x64.zip"

[wii-u-gc-adapter]
src.git = "https://github.com/ToadKing/wii-u-gc-adapter"
fetch.github = "ToadKing/wii-u-gc-adapter"

[xdg-desktop-portal]
src.git = "https://github.com/flatpak/xdg-desktop-portal"
fetch.github = "flatpak/xdg-desktop-portal"

[xdg-desktop-portal-gtk]
src.git = "https://github.com/flatpak/xdg-desktop-portal-gtk"
fetch.github = "flatpak/xdg-desktop-portal-gtk"

[xorg-libxcvt]
src.git = "https://gitlab.freedesktop.org/xorg/lib/libxcvt"
fetch.git = "https://gitlab.freedesktop.org/xorg/lib/libxcvt"

[xorgproto]
src.git = "https://github.com/freedesktop/xorg-xorgproto"
fetch.github = "freedesktop/xorg-xorgproto"

[xwayland]
src.git = "git://anongit.freedesktop.org/xorg/xserver"
fetch.git = "git://anongit.freedesktop.org/xorg/xserver"

[ydotool]
src.git = "https://github.com/ReimuNotMoe/ydotool"
fetch.github = "ReimuNotMoe/ydotool"

[yubikey-guide]
src.git = "https://github.com/drduh/YubiKey-Guide"
fetch.github = "drduh/YubiKey-Guide"

[zoom-us]
src.webpage = "https://zoom.us/download?os=linux"
src.regex = "Version (.*)<.*"
src.from_pattern = "(.*) \\((.*)\\)"
src.to_pattern = "\\1.\\2"
fetch.url = "https://cdn.zoom.us/prod/$ver/zoom_x86_64.pkg.tar.xz"

### Python extensions

[pythonPackages-cfscrape]
src.git = "https://github.com/Anorov/cloudflare-scrape"
fetch.url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz"

[pythonPackages-cmapy]
src.pypi = "cmapy"
fetch.pypi = "cmapy"

[pythonPackages-mediapipe]
src.manual = "0.8.8"
fetch.url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-$ver-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"

[pythonPackages-pySmartDL]
src.git = "https://github.com/iTaybb/pySmartDL"
fetch.url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz"

### Vim Plugins

[vimPlugins-yuck]
src.git = "https://github.com/elkowar/yuck.vim"
fetch.github = "elkowar/yuck.vim"
