# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  papermc-1_10_2 = {
    pname = "papermc-1_10_2";
    version = "918";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.10.2/builds/918/downloads/paper-1.10.2-918.jar";
      sha256 = "sha256-gzVNJKIrYmXnbAibPRelaKu0RsDM0SwkUvXhSEErFsI=";
    };
    mcVer = "1.10.2";
  };
  papermc-1_11_2 = {
    pname = "papermc-1_11_2";
    version = "1106";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.11.2/builds/1106/downloads/paper-1.11.2-1106.jar";
      sha256 = "sha256-PQ9A7B+WMN/br6YmzCDCZtf7kPwiWD3BuZXn+/t2gw0=";
    };
    mcVer = "1.11.2";
  };
  papermc-1_12 = {
    pname = "papermc-1_12";
    version = "1169";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.12/builds/1169/downloads/paper-1.12-1169.jar";
      sha256 = "sha256-Hn6Iou1vK3D6P27GYRNzRYxdcrKocH5gkh32AceR5g4=";
    };
    mcVer = "1.12";
  };
  papermc-1_12_1 = {
    pname = "papermc-1_12_1";
    version = "1204";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.12.1/builds/1204/downloads/paper-1.12.1-1204.jar";
      sha256 = "sha256-26IhnWdK2F5O8sQZMdNLb6S+daiHlz7KryhnJ6A4Eto=";
    };
    mcVer = "1.12.1";
  };
  papermc-1_12_2 = {
    pname = "papermc-1_12_2";
    version = "1620";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.12.2/builds/1620/downloads/paper-1.12.2-1620.jar";
      sha256 = "sha256-OiBBgH9JLc3DTrsySih0FJRuPgXsPfb9A/W199mvwhA=";
    };
    mcVer = "1.12.2";
  };
  papermc-1_13 = {
    pname = "papermc-1_13";
    version = "173";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13/builds/173/downloads/paper-1.13-173.jar";
      sha256 = "sha256-ANuC0hQkLJNFJm1E/40RqOhXoaAu33y1/MLR2XMoMSk=";
    };
    mcVer = "1.13";
  };
  papermc-1_13-pre7 = {
    pname = "papermc-1_13-pre7";
    version = "12";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13-pre7/builds/12/downloads/paper-1.13-pre7-12.jar";
      sha256 = "sha256-jCxNvDooQr6EVLTEswYma8Yi4ttoEjNVj+34IwgAlAw=";
    };
    mcVer = "1.13-pre7";
  };
  papermc-1_13_1 = {
    pname = "papermc-1_13_1";
    version = "386";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13.1/builds/386/downloads/paper-1.13.1-386.jar";
      sha256 = "sha256-ZjdAHYfQ9dtarukNcQP1LF4bqva21GQ6V5PnsCtXdcs=";
    };
    mcVer = "1.13.1";
  };
  papermc-1_13_2 = {
    pname = "papermc-1_13_2";
    version = "657";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13.2/builds/657/downloads/paper-1.13.2-657.jar";
      sha256 = "sha256-Eego0FZat2oKDhgMBWNkqV3kSVjP1qavP5sdxwsD6c0=";
    };
    mcVer = "1.13.2";
  };
  papermc-1_14 = {
    pname = "papermc-1_14";
    version = "17";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14/builds/17/downloads/paper-1.14-17.jar";
      sha256 = "sha256-M4vnf1I5xEz/P4D1wQe15hrEj7OTSLznJJMDIJIBByo=";
    };
    mcVer = "1.14";
  };
  papermc-1_14_1 = {
    pname = "papermc-1_14_1";
    version = "50";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.1/builds/50/downloads/paper-1.14.1-50.jar";
      sha256 = "sha256-K8+AF0hcxBs+ctqnKFpG8mqF0FW51ji8mgf3djIWitc=";
    };
    mcVer = "1.14.1";
  };
  papermc-1_14_2 = {
    pname = "papermc-1_14_2";
    version = "107";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.2/builds/107/downloads/paper-1.14.2-107.jar";
      sha256 = "sha256-EgNOV44BTrNp4pKfNyW9QJhYv5QSjkbR8obVvjbDyw4=";
    };
    mcVer = "1.14.2";
  };
  papermc-1_14_3 = {
    pname = "papermc-1_14_3";
    version = "134";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.3/builds/134/downloads/paper-1.14.3-134.jar";
      sha256 = "sha256-ttLYrGfWhRQWl6jOzZnEe69gSQAAfrDicP1uqGy7xUA=";
    };
    mcVer = "1.14.3";
  };
  papermc-1_14_4 = {
    pname = "papermc-1_14_4";
    version = "245";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.4/builds/245/downloads/paper-1.14.4-245.jar";
      sha256 = "sha256-vY7FzbIjcNN4FqbeJnmN89Kw1vnHyWyIykWhMD/qUOg=";
    };
    mcVer = "1.14.4";
  };
  papermc-1_15 = {
    pname = "papermc-1_15";
    version = "21";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.15/builds/21/downloads/paper-1.15-21.jar";
      sha256 = "sha256-i3JsDetsOiZdZ5o9OiwPjlJD+8bdz8r0LiQgnLH4KbQ=";
    };
    mcVer = "1.15";
  };
  papermc-1_15_1 = {
    pname = "papermc-1_15_1";
    version = "62";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.15.1/builds/62/downloads/paper-1.15.1-62.jar";
      sha256 = "sha256-IqehnzeNuO35LNulfZHO6n5PpkcLZ35rvlfo9+HZpN0=";
    };
    mcVer = "1.15.1";
  };
  papermc-1_15_2 = {
    pname = "papermc-1_15_2";
    version = "393";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.15.2/builds/393/downloads/paper-1.15.2-393.jar";
      sha256 = "sha256-vS3W8sxInPniu4AMtPttY+nSk5RdOsELCd2cYJj6nzQ=";
    };
    mcVer = "1.15.2";
  };
  papermc-1_16_1 = {
    pname = "papermc-1_16_1";
    version = "138";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.1/builds/138/downloads/paper-1.16.1-138.jar";
      sha256 = "sha256-kpVZuh38beKQThcon7PRrJXwq0jHVAz1uMLwVf6p1Zw=";
    };
    mcVer = "1.16.1";
  };
  papermc-1_16_2 = {
    pname = "papermc-1_16_2";
    version = "189";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.2/builds/189/downloads/paper-1.16.2-189.jar";
      sha256 = "sha256-5eEFF9qqm9bVSooNIthm4x2nwbR8ueQl/6rCNv3nXsk=";
    };
    mcVer = "1.16.2";
  };
  papermc-1_16_3 = {
    pname = "papermc-1_16_3";
    version = "253";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.3/builds/253/downloads/paper-1.16.3-253.jar";
      sha256 = "sha256-lAMD7l9bzAg3fjiOocHaoQnBrIxNGJ3GfeEQaFPy/CM=";
    };
    mcVer = "1.16.3";
  };
  papermc-1_16_4 = {
    pname = "papermc-1_16_4";
    version = "416";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/416/downloads/paper-1.16.4-416.jar";
      sha256 = "sha256-ljJo7VZKx9LsB2Rj6SH/oJVwI19Ye70aTZGiPKQmS2Y=";
    };
    mcVer = "1.16.4";
  };
  papermc-1_16_5 = {
    pname = "papermc-1_16_5";
    version = "794";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/794/downloads/paper-1.16.5-794.jar";
      sha256 = "sha256-5n2khR0IzeN4qyuJvliEkjjDAzUe0kghgamcLCtIknY=";
    };
    mcVer = "1.16.5";
  };
  papermc-1_17 = {
    pname = "papermc-1_17";
    version = "79";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.17/builds/79/downloads/paper-1.17-79.jar";
      sha256 = "sha256-dgqTuUpY1hm9ZH1xr4RohhfQRE0itxZQC8azQ4WNyHE=";
    };
    mcVer = "1.17";
  };
  papermc-1_17_1 = {
    pname = "papermc-1_17_1";
    version = "409";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/409/downloads/paper-1.17.1-409.jar";
      sha256 = "sha256-WlhS7uNF4ctKBA6aoqHVZieaBI9cofm+UrVc9VWkJek=";
    };
    mcVer = "1.17.1";
  };
  papermc-1_18 = {
    pname = "papermc-1_18";
    version = "66";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.18/builds/66/downloads/paper-1.18-66.jar";
      sha256 = "sha256-PJlfINrk5OIdVVT6yVegqKXIW9W/NJFfrEtPFuDvEBs=";
    };
    mcVer = "1.18";
  };
  papermc-1_18_1 = {
    pname = "papermc-1_18_1";
    version = "216";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/216/downloads/paper-1.18.1-216.jar";
      sha256 = "sha256-qUkXpEcsLLyZB6FcZmu7eE+V7Ne1PHe8CP5xED5Uh/U=";
    };
    mcVer = "1.18.1";
  };
  papermc-1_18_2 = {
    pname = "papermc-1_18_2";
    version = "271";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.18.2/builds/271/downloads/paper-1.18.2-271.jar";
      sha256 = "sha256-r6Ru0JFyTxYEj3s2AB4OWHVr/7fHFRSlpaGuCiShQjY=";
    };
    mcVer = "1.18.2";
  };
  papermc-1_8_8 = {
    pname = "papermc-1_8_8";
    version = "445";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar";
      sha256 = "sha256-f/bSzsZx7w2Vs3I7XJKJARj7iC1zt/j6CizTHZfFX4Y=";
    };
    mcVer = "1.8.8";
  };
  papermc-1_9_4 = {
    pname = "papermc-1_9_4";
    version = "775";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.9.4/builds/775/downloads/paper-1.9.4-775.jar";
      sha256 = "sha256-FaWCHd6sxZZDLD+/JCYqLSZPVWBg7Nbxg4+wGrVimoE=";
    };
    mcVer = "1.9.4";
  };
}
