# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.108.0-b.9";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.9/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-9RtDTiD5vECV1Ieo6hYfMz24Bj2ctyuq81b8ZiawPQ4=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.108.0-b.9";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.9/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-Tlp+83stkwuiYTDQWl0gEt4X2+prnMIYBa4zFo83h8M=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.108.0-b.9";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.9/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-ylcsa6m6eaGVKHmyyZIseMHMmbRSUjW0tXw1c8EYu6s=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.108.0-b.9";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.9/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-U7yySjBDu7oseox+n+bzSG/KUJZVYNgvLzNx+Dzc4P4=";
    };
  };
  adl = {
    pname = "adl";
    version = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
      fetchSubmodules = false;
      sha256 = "sha256-huGpDtkWrhZyKDNKXat8T3qtAyMjBaq8HFd1w1ThUVk=";
    });
  };
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
      fetchSubmodules = false;
      sha256 = "sha256-KXqicTZ9GZlNj1AH3tMmOrC8zjXoEnqo4JJJTBdiI4E=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./age-plugin-yubikey-08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "941eef9d5435b38775911d5c773a7dfda8adfea8";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "941eef9d5435b38775911d5c773a7dfda8adfea8";
      fetchSubmodules = false;
      sha256 = "sha256-k9zwrmXRG93BVExtJkZe7w8H1oOiI2aAHEkllqsv2jw=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  argonone-fancontrold = {
    pname = "argonone-fancontrold";
    version = "b6b960eb492224012680f56e3c6fba13502e542c";
    src = fetchFromGitHub ({
      owner = "mgdm";
      repo = "argonone-utils";
      rev = "b6b960eb492224012680f56e3c6fba13502e542c";
      fetchSubmodules = false;
      sha256 = "sha256-v098KH8TgzGgCc7+59SVWy19xW456eXX/BDdt9zzVhk=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "c21b9faefc0d99ab4f91836ceddc68a2a52ff9cb";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "c21b9faefc0d99ab4f91836ceddc68a2a52ff9cb";
      fetchSubmodules = false;
      sha256 = "sha256-3bN/T4vCaIqkoz1AfZvczTXQup9B4Myq1cIRy/CyCgo=";
    });
  };
  asusctl = {
    pname = "asusctl";
    version = "9a50278b98eab856f9fd9a6abaca48868a33a543";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl";
      rev = "9a50278b98eab856f9fd9a6abaca48868a33a543";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6kBRJqXY72kRVKYkxewe/vDjgKhFKMbbDtvnmpHtKAI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./asusctl-9a50278b98eab856f9fd9a6abaca48868a33a543/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  avizo = {
    pname = "avizo";
    version = "b1a271d0562c1feadfdd24a9f2fc03634c6eb0de";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "b1a271d0562c1feadfdd24a9f2fc03634c6eb0de";
      fetchSubmodules = false;
      sha256 = "sha256-ainU4nXWFp1udVujPHZUeWIfJE4RrjU1hn9J17UuuzU=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "3a542219f3bf129546ae79eb20e384ea28fa9798";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "3a542219f3bf129546ae79eb20e384ea28fa9798";
      fetchSubmodules = false;
      sha256 = "sha256-4z3w6iuv+Gw2xRvhv2AX4suO6dl82woJn0p1nkEx3uM=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  betterdiscord-installer = {
    pname = "betterdiscord-installer";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/BetterDiscord/Installer/releases/download/v1.1.1/BetterDiscord-Linux.AppImage";
      sha256 = "sha256-EZj8vRyWbEfCagy/x3QTFADvE6Z76fqnDVRQZhD0S2k=";
    };
  };
  betterdiscordctl = {
    pname = "betterdiscordctl";
    version = "49a26fe82d441fbb8e51b0511969929f05cb2057";
    src = fetchFromGitHub ({
      owner = "bb010g";
      repo = "betterdiscordctl";
      rev = "49a26fe82d441fbb8e51b0511969929f05cb2057";
      fetchSubmodules = false;
      sha256 = "sha256-aBJDQAKmsBGoFaurADBTDqL9L/4+bWBk2y26vQ0LFx4=";
    });
  };
  bling = {
    pname = "bling";
    version = "e384951c321420dcaada7ad4381a644f2c7eea83";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "e384951c321420dcaada7ad4381a644f2c7eea83";
      fetchSubmodules = false;
      sha256 = "sha256-P725jMxPK7TOhLvvwQyyJBSOU48EDQeXIfcuweq6TUw=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "a9edbe6e4aeb9378e2d775dcd0d21dbcd8aed67a";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "a9edbe6e4aeb9378e2d775dcd0d21dbcd8aed67a";
      fetchSubmodules = false;
      sha256 = "sha256-RmQouwv1aJ4cS89q0NNir2CknwwbKCloXyCigdXd+Sg=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "741b0502ee7cb0ecbd6dd0517c4f186729f52718";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "741b0502ee7cb0ecbd6dd0517c4f186729f52718";
      fetchSubmodules = false;
      sha256 = "sha256-4hNQ2z31nLY4RNPX1GX9QOFSYPGU358RfcWrTVujSXM=";
    });
  };
  cinny = {
    pname = "cinny";
    version = "2.0.4";
    src = fetchurl {
      url = "https://github.com/ajbura/cinny/releases/download/v2.0.4/cinny-v2.0.4.tar.gz";
      sha256 = "sha256-D4vA4Fldg+/TicuaXUlwxW50KqDzMBMUCSVpOW0Rulw=";
    };
  };
  conduit = {
    pname = "conduit";
    version = "ba682fa3b41687eb4f45346046c21e695f6d840e";
    src = fetchgit {
      url = "https://gitlab.com/famedly/conduit";
      rev = "ba682fa3b41687eb4f45346046c21e695f6d840e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D6r3Fx/SMB9o2mI/ws6ooh3g1pRSoJL2FN97bfRXSyc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./conduit-ba682fa3b41687eb4f45346046c21e695f6d840e/Cargo.lock;
      outputHashes = {
        "ruma-0.5.0" = "sha256-srmybII7j3xkSDVFvIiWUQnZsW+vEKKagSZhA5MRRQc=";
        "reqwest-0.11.9" = "sha256-wH/q7REnkz30ENBIK5Rlxnc1F6vOyuEANMHFmiVPaGw=";
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  conduit-toolbox = {
    pname = "conduit-toolbox";
    version = "805baa070528e6db7161ef35b75180e70d896541";
    src = fetchFromGitHub ({
      owner = "ShadowJonathan";
      repo = "conduit_toolbox";
      rev = "805baa070528e6db7161ef35b75180e70d896541";
      fetchSubmodules = false;
      sha256 = "sha256-vQ4r2Cvf2okeJ5qGIQ8mHoUmmrbUbY+bIEpee7XH6zA=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./conduit-toolbox-805baa070528e6db7161ef35b75180e70d896541/Cargo.lock;
      outputHashes = {
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.135";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.135/discord-canary-0.0.135.tar.gz";
      sha256 = "sha256-dmG+3BWS1BMHHQAv4fsXuObVeAJBeD+TqnyQz69AMac=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "7177a0ec744ad5f6faeb69cf278fe99473350d71";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "7177a0ec744ad5f6faeb69cf278fe99473350d71";
      fetchSubmodules = false;
      sha256 = "sha256-fBSp6wj2/R4zNaep8d21UflpVtSwiaxwcYU1AXc2olo=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "ea7cb3c6cd0467a7db783fbd30aa8599604a76d8";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "ea7cb3c6cd0467a7db783fbd30aa8599604a76d8";
      fetchSubmodules = false;
      sha256 = "sha256-K9UtHppqo+QzNTxTd9C7B97N8Nd79lR9ytj17M3QLaM=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
      fetchSubmodules = false;
      sha256 = "sha256-70wtFxJOY9h4moT4hCTs4yfp2wGM39i5qnJerBVkpV4=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
      fetchSubmodules = false;
      sha256 = "sha256-5m+btrwhlk/nIZSasu+fTK1NhK0KdugVeD0KYOt0vE4=";
    });
  };
  duf = {
    pname = "duf";
    version = "4f4bce983562c3edc40161a44de19a2e258e38b1";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "4f4bce983562c3edc40161a44de19a2e258e38b1";
      fetchSubmodules = false;
      sha256 = "sha256-Wg7b31nm/p/0rHYwLKoI6/1iQH2qmWWKX9knFxf5T3Q=";
    });
  };
  eww = {
    pname = "eww";
    version = "0b0715fd505200db5954432b8a27ed57e3e6a72a";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "0b0715fd505200db5954432b8a27ed57e3e6a72a";
      fetchSubmodules = false;
      sha256 = "sha256-wtrq8crcN7fdNAkCqKHrPpptP4FOEQwReUnSFcCMQzs=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./eww-0b0715fd505200db5954432b8a27ed57e3e6a72a/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "29d4c43dc9d827a11be724b867d23be35dba30ec";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "29d4c43dc9d827a11be724b867d23be35dba30ec";
      fetchSubmodules = false;
      sha256 = "sha256-Jlfb9gL2yJgNq862Vcr35b+Rl6qYU5pupG7C7+bqC2I=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "55ba195fa35bce7296e63b7e4a3a1f792659e3b9";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "55ba195fa35bce7296e63b7e4a3a1f792659e3b9";
      fetchSubmodules = false;
      sha256 = "sha256-F2tjgW/3gHCpyvQVXmK/umioDrsWeXR7qYAJQ1VoYwA=";
    });
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  fx_cast = {
    pname = "fx_cast";
    version = "c6d32293de552c66f4af0576a746720e9ef12c31";
    src = fetchFromGitHub ({
      owner = "hensm";
      repo = "fx_cast";
      rev = "c6d32293de552c66f4af0576a746720e9ef12c31";
      fetchSubmodules = false;
      sha256 = "sha256-YzImmunlOeHJ5CaP8LE6lXR6v+hDJHvexWJYzi8Z1KU=";
    });
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "97c0bcdb1d8c9e56609036fc5b9a36136aa433c8";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "97c0bcdb1d8c9e56609036fc5b9a36136aa433c8";
      fetchSubmodules = false;
      sha256 = "sha256-R0V8N9NH2e3yWzni3T5v+Kd0ZxCVwBSp9gC3g6gmbes=";
    });
  };
  hyprland = {
    pname = "hyprland";
    version = "354e2651289861bf7027fd02be41088e45fc1c99";
    src = fetchFromGitHub ({
      owner = "vaxerski";
      repo = "hyprland";
      rev = "354e2651289861bf7027fd02be41088e45fc1c99";
      fetchSubmodules = false;
      sha256 = "sha256-yhlNWRnEfCAJYTqAPZawmgdt0rufmyTllbbqvoEhzm0=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "9f62a40b0ddf4413c4e2d5f7346a6ef09bc2f44e";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "9f62a40b0ddf4413c4e2d5f7346a6ef09bc2f44e";
      fetchSubmodules = false;
      sha256 = "sha256-1t5iSuCE8AbNlEBkti7LHtyvyy4LwtCy+6CXrAe4tqg=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "3380c09d5812cec18ff7ed80e7e6d69d6afd3ab2";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "3380c09d5812cec18ff7ed80e7e6d69d6afd3ab2";
      fetchSubmodules = false;
      sha256 = "sha256-IkmNNYyV3eRAqTdh19d1hgNWtENmlMD5qYAGs34T3ZU=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-135-ge169253";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-135-ge169253-1_all.deb";
      sha256 = "sha256-oLutygWypl/JvsM3N2vJq6QS8Fc1dWUx/HDV2Ur8tow=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-900";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-900-1_all.deb";
      sha256 = "sha256-tAuWhu1DdasOuLIz9/Ox1n1XcFWm5qnTVr6FpdKpwbE=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.6260";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.6260.tar.bz2";
      sha256 = "sha256-Y1ELKdFdbnq20yUt4XoXmstJm8uI8EBGIFOvFWf+5Uw=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.6260";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.6260-1_all.deb";
      sha256 = "sha256-ZUfyEYAU4YEYXBoM+tEZ6SAhqlNcsmxnKw8WEv0gy7M=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.2-9-g8cded16e";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.2-9-g8cded16e-1_all.deb";
      sha256 = "sha256-L9h+qYV/W2wPzycfDGC4AXpTl7wlulyt2KryA+Tb/YU=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "3b3fcd82d7758f92acc601ed5e0b9d7612e318c7";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "3b3fcd82d7758f92acc601ed5e0b9d7612e318c7";
      fetchSubmodules = false;
      sha256 = "sha256-7FbO6iPi+h2dKOHqldHa8ZcAH4zI48BVgcq1/Mza+T8=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
      fetchSubmodules = false;
      sha256 = "sha256-8v9ytywv2+/qqN94g44vHMGsbKueYSDXq76wo95pSFE=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  matrix-appservice-discord = {
    pname = "matrix-appservice-discord";
    version = "v1.0.0";
    src = fetchFromGitHub ({
      owner = "Half-Shot";
      repo = "matrix-appservice-discord";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-hZQ+3FDRWNGsnaHblnB2p6Inf9ZMrbB2jmgR2rskil0=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "103.0.1264.21";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_103.0.1264.21-1_amd64.deb";
      sha256 = "sha256-jhiZ+GFLlDHM811BSX+IO1YIdVdQbRIvUNT24yGIZow=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "104.0.1287.1";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_104.0.1287.1-1_amd64.deb";
      sha256 = "sha256-wXBY4dUUSkD5bXDMdaMBJQUBGnK73WqiIBQ77TYwA4I=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "086b2457e8b769d6af44917759403f76b8b3b90e";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "086b2457e8b769d6af44917759403f76b8b3b90e";
      fetchSubmodules = false;
      sha256 = "sha256-WvDS1z33/j8uXMNFGqZ8D0kRnCqhKzgtXdMVOoo9vxg=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.35.1";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.35.1.tar.gz";
      sha256 = "sha256-yR1ew5VDQz7elr7hJRxI/iF0xupM4tD8+eOSJd9GoVM=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.32.3";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.32.3.tar.gz";
      sha256 = "sha256-GyYNcUXSNOsM+NYgOZxGXlescCUAAZgd6fRpX6XWENA=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "2ccac2afd1f3b28f573ec314e61be034858fedc2";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "2ccac2afd1f3b28f573ec314e61be034858fedc2";
      fetchSubmodules = false;
      sha256 = "sha256-v51No7tILsbwj3yMuonjiyw4gxUpdLRh0brADswM3Mk=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "383869906ab0f29ca86b0604a4f2fcfd1c4162e0";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "383869906ab0f29ca86b0604a4f2fcfd1c4162e0";
      fetchSubmodules = false;
      sha256 = "sha256-V6veYh6ygR6PMg8RoItkGiF4IDjeiW6kRTMlIJk91GY=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-Rr0UpJa7kemczCqNn6b8HNtW6PiWO/Ez1LUh/WNk8S8=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "dd3a57fbfa73bceb0ce6e41715afb9f8d954f1cf";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "dd3a57fbfa73bceb0ce6e41715afb9f8d954f1cf";
      fetchSubmodules = false;
      sha256 = "sha256-5XC2exNo1HlTNGjYioB/KCErSSikjTrTQWL4vjfrrJU=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./ouch-dd3a57fbfa73bceb0ce6e41715afb9f8d954f1cf/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "cd50596f0ed81c0aa28cefed62176bd6f050a1c6";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "cd50596f0ed81c0aa28cefed62176bd6f050a1c6";
      fetchSubmodules = false;
      sha256 = "sha256-e0Zd/kVqRiYUL6afsp4+JHKSe0qtNLyBE2s6Nem4A1I=";
    });
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.44.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.44.1.tar.gz";
      sha256 = "sha256-8MMKI0XbbURsPF2eQ0M9QiXcdRF9urfqFZCsgoB77kM=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "c0cec06df85a17dcbadcadda83c2866865167c79";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "c0cec06df85a17dcbadcadda83c2866865167c79";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-QjAeFqBrvgAlCZ5e7RQIYomiSdcWCsvuw4SR9zoPkMM=";
    };
  };
  polymc-cracked = {
    pname = "polymc-cracked";
    version = "6000f5de6742bf825ed56477b16be559f5cfe227";
    src = fetchFromGitHub ({
      owner = "thecountrox";
      repo = "PolyMC-Cracked";
      rev = "6000f5de6742bf825ed56477b16be559f5cfe227";
      fetchSubmodules = false;
      sha256 = "sha256-7N/H+mpYl/v522b+D3HI8zw9oLqj2yFJ0WGVDzLQC4w=";
    });
  };
  pure = {
    pname = "pure";
    version = "3b2606db2e7eb6f05c67b229b5e3c68a1c3947a6";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "3b2606db2e7eb6f05c67b229b5e3c68a1c3947a6";
      fetchSubmodules = false;
      sha256 = "sha256-shiBRF2DeLVWFcla6DuATtmc4vc+xoChzOS70Rd8NAM=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "908516967acce6d78d02a4b7306f30d09180da6d";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "908516967acce6d78d02a4b7306f30d09180da6d";
      fetchSubmodules = false;
      sha256 = "sha256-ZZ7lut3wYDg4Ry8SE96lCL8gEMf0Btv+cSks/9M6JJs=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
      fetchSubmodules = false;
      sha256 = "sha256-muDz1rFTvWOZGrEzql+VZbs42bS09BREjKS5OpBu2g8=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "0fe694665ccc750b21344b4565429cca1ec0943d";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "0fe694665ccc750b21344b4565429cca1ec0943d";
      fetchSubmodules = false;
      sha256 = "sha256-fede0e12ewH4ioTFqTkuYKd6cERWRbdn3bnQ8IFacb8=";
    });
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "1e8c22b4a05c7602aa9e51509274ce5ac36a5099";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "1e8c22b4a05c7602aa9e51509274ce5ac36a5099";
      fetchSubmodules = true;
      sha256 = "sha256-RcTwv+DGS+niuGYSQWAoTk9HAg/WnFV8r6VM0vEc9h4=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "05e269a0bb0f6f67e63c33d1aadaf9cb875af7d1";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "05e269a0bb0f6f67e63c33d1aadaf9cb875af7d1";
      fetchSubmodules = false;
      sha256 = "sha256-Xg4EPnhYc5aBGSUgS2/wfoYc83qaKm9r0qwmnWopQes=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./rustdesk-05e269a0bb0f6f67e63c33d1aadaf9cb875af7d1/Cargo.lock;
      outputHashes = {
        "rust-pulsectl-0.2.12" = "sha256-8jXTspWvjONFcvw9/Z8C43g4BuGZ3rsG32tvLMQbtbM=";
        "confy-0.4.0" = "sha256-e91cvEixhpPzIthAxzTa3fDY6eCsHUy/eZQAqs7QTDo=";
        "sciter-rs-0.5.57" = "sha256-ZZnZDhMjK0LjgmK0da1yvB0uoKueLhhhQtzmjoN+1R0=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
        "parity-tokio-ipc-0.7.3" = "sha256-9m9YQoJ3Vaet25TL40Yb76zHRlnnsreW/EOMb/R7cRk=";
        "tokio-socks-0.5.1" = "sha256-inmAJk0fAlsVNIwfD/M+htwIdQHwGSTRrEy6N/mspMI=";
        "rdev-0.5.0" = "sha256-O+jbA8GS9KVZR/i840+mfQ9LZ3Qtf/XBbV/Mkqn5C/g=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "2e539cf5bfc60b1463519de2566422464877992d";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "2e539cf5bfc60b1463519de2566422464877992d";
      fetchSubmodules = false;
      sha256 = "sha256-MMPmTEMYghf2A+rQF5pJaLTb2NyXpV3HKx20g7o/deg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
      fetchSubmodules = false;
      sha256 = "sha256-FfbYQrHndU7rtI8CKK7wtn3pdufBSiXUgefozCja4Do=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-SIht9sqmeijEeU4uLwm+tlZtFlTnD/G5GH8haUL6dlU=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-g/SzgU3vOzm8uRuA6AN/N8Tnrl2Vpya58hx99dGfecI=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-jnhTTmSy5J8MJotbsI8g5hxotgjvyDbccymjABwajYw=";
    };
  };
  snui = {
    pname = "snui";
    version = "f0bfd13b73dc4fdc76a35083b08299a7267c0e10";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "f0bfd13b73dc4fdc76a35083b08299a7267c0e10";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-4ffkLAvUzXmSo9LdN/GUP1WVyQ0YyAEbi1ULiI++KqA=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "131c55bccb0fa0476a9975893ba0ee597290f483";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "131c55bccb0fa0476a9975893ba0ee597290f483";
      fetchSubmodules = false;
      sha256 = "sha256-o9nC27ZjM0pDiSu2U6u5f7vockhsgPGjrQFKTkR2nrk=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "dd7a7e13e0dc7a717cc06bba9ea04ed29d70a30e";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "dd7a7e13e0dc7a717cc06bba9ea04ed29d70a30e";
      fetchSubmodules = false;
      sha256 = "sha256-v6KRTeXYgsL6bVSAY7qRjBCnKKELe9SSx7FVNRkbiRU=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.84.716.gc5f8b819";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_60.snap";
      sha256 = "sha256-ho3WjGNjmHsERzC3FLgliuVSQWK2F5ec0ddQSfq6oyI=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "ae6dac7a54f899316674ba57ce4a0f9890cd2b1c";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "ae6dac7a54f899316674ba57ce4a0f9890cd2b1c";
      fetchSubmodules = false;
      sha256 = "sha256-UYQ5XiG18bQO4UfLDa7Nn2BQGk0jo0+tSP1lL79cY8k=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./spotifyd-ae6dac7a54f899316674ba57ce4a0f9890cd2b1c/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "7c0011cf91e87c30c2a630fee915ead58ef9dcf5";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "7c0011cf91e87c30c2a630fee915ead58ef9dcf5";
      fetchSubmodules = false;
      sha256 = "sha256-7RVyjbBZ4svHXKJV9Ljh6Lf5+Ry/VUUcChwEvk4oVK4=";
    });
  };
  supergfxctl = {
    pname = "supergfxctl";
    version = "de0f8219c245708d472f4a77dcb4ddd574060a9e";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl";
      rev = "de0f8219c245708d472f4a77dcb4ddd574060a9e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nr4KvI4hfyRTqyOjaeBcL22HqH5Dw3YX5I/ZVaApUiM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./supergfxctl-de0f8219c245708d472f4a77dcb4ddd574060a9e/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  sway-borders = {
    pname = "sway-borders";
    version = "55702663b87499096c02a6586217b2447e5bcfce";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "55702663b87499096c02a6586217b2447e5bcfce";
      fetchSubmodules = false;
      sha256 = "sha256-g1spYIb23DWhyfqvIujHW+FBaqlmvNkV72cGklT4vWo=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  tailscale = {
    pname = "tailscale";
    version = "757ecf7e8066301f582fc77cc806ebcb9c4ba3ed";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "757ecf7e8066301f582fc77cc806ebcb9c4ba3ed";
      fetchSubmodules = false;
      sha256 = "sha256-y76pdb9p5DEIfCNlDm0URMPcLpgs66YEV74sfV74c8g=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "64347899f5c60ccc3a7c5ebfa193364b918a38ef";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "64347899f5c60ccc3a7c5ebfa193364b918a38ef";
      fetchSubmodules = false;
      sha256 = "sha256-o4Tyh0qQe9nLl8C5mt9ltnsNqCHjr2TLc78joS+pLsA=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.5.00.10453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.10453_amd64.deb";
      sha256 = "sha256-fLVw2axSMetuaoRzjg+x4DRYY8WP5TQbL7LbfF6LFfA=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "934c567096bbe5104d6ad7a21014d04b1b198052";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-x8D5XrvMjNV2R5CXs/ficOhwXNTRglsQxPhfvuUF4nM=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "9cedb6fd42e4b07f83aa278c83fdb50f52c30e63";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "9cedb6fd42e4b07f83aa278c83fdb50f52c30e63";
      fetchSubmodules = false;
      sha256 = "sha256-dIso85Kvf7HUsDa7ypfU7WYPGrS/qZb8coNlUcB4MD0=";
    });
  };
  ultimmc = {
    pname = "ultimmc";
    version = "66bb7105db93e0977bb64a59a12b001f780e0566";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "66bb7105db93e0977bb64a59a12b001f780e0566";
      fetchSubmodules = true;
      sha256 = "sha256-t/R3BBRy2orzUuh537xMPwORHmhQy4aGe96e77CVzZs=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.25.0";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.25.0";
      fetchSubmodules = false;
      sha256 = "sha256-s7ouCEwpI61lpxBHtzFFy7PmFGrnGSi25K75rRnox6M=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./vaultwarden-1.25.0/Cargo.lock;
      outputHashes = {
        "job_scheduler-1.2.1" = "sha256-v3Q3e6rAOmEm81pd6GkapbWoUP/Q4KCM75TEEAoEcUs=";
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2022.05.0";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2022.05.0/bw_web_v2022.05.0.tar.gz";
      sha256 = "sha256-YbEnPh7eaGCs9Ly5fUccRQeCohjr06vGKocFQkbyJiA=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  waydroid = {
    pname = "waydroid";
    version = "facf2b713da1038bbc960bb7e094bdb80213485e";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "facf2b713da1038bbc960bb7e094bdb80213485e";
      fetchSubmodules = false;
      sha256 = "sha256-+qHYyKvoPhzGmDpYHEtxx/Zyjw/6oia2fT1S7NcvUpw=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "140f9832314247e5a122ca252d139449255ad7c3";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "140f9832314247e5a122ca252d139449255ad7c3";
      fetchSubmodules = false;
      sha256 = "sha256-tUEeczs3J//2ZrZkAsSn3C+GScRPaIgheRM2wByS8p4=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "bef774bd0fe74aa29338ab0757a58e3831138295";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "bef774bd0fe74aa29338ab0757a58e3831138295";
      fetchSubmodules = false;
      sha256 = "sha256-MAE8XwvhIFFqGp/lZH4UILrvWyseTSArrZUc+OYWh3Q=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "c4da749e54993a4b50e1427616d1009ddd36c933";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "c4da749e54993a4b50e1427616d1009ddd36c933";
      fetchSubmodules = false;
      sha256 = "sha256-acLaoW09vvsB2cd7eQt4DnAM+dDmMB7jGPYZJwGkjqg=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2449.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2449.0-linux-x64.zip";
      sha256 = "sha256-vsr6eymKqU2Y6HM4DPHnUfVkB2BQ1HSSWvk1tNhUA5Y=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xdg-desktop-portal = {
    pname = "xdg-desktop-portal";
    version = "fe9c5a11a199c966b32f6b7327136782544b845e";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal";
      rev = "fe9c5a11a199c966b32f6b7327136782544b845e";
      fetchSubmodules = false;
      sha256 = "sha256-b4hgu2HhAmKOXYw/S6pNESuTp2TKDQsw3K9MwAh8vWs=";
    });
  };
  xdg-desktop-portal-gtk = {
    pname = "xdg-desktop-portal-gtk";
    version = "7c7bbf922b63b9d536a2293c0587cb20df01eb2d";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal-gtk";
      rev = "7c7bbf922b63b9d536a2293c0587cb20df01eb2d";
      fetchSubmodules = false;
      sha256 = "sha256-I9xQgiE3lNb2vRodO5R1y40lqoOKzALskrVePidant4=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "d3468537b9748756350c9ab89d2b639cebeeccbc";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "d3468537b9748756350c9ab89d2b639cebeeccbc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wK0+asG9oOuZmDn2EIvL/EBcazHG05KgoUGUHPju+sk=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "912e050d8df0fc3d034c8b03d8afe37b9ce15402";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "912e050d8df0fc3d034c8b03d8afe37b9ce15402";
      fetchSubmodules = false;
      sha256 = "sha256-vlmrIM9iloxXJFefN1ErsML6AeRWLc/pW9TvFcR3O2w=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "4532b696c644cb7f21e96cf76d3e6b21ccc0e309";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "4532b696c644cb7f21e96cf76d3e6b21ccc0e309";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xKYg6DiL9aaH0B2l1a+a5kEj3WyRyNwBU/XUTcScT4o=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
      fetchSubmodules = false;
      sha256 = "sha256-maXXGCqB8dkGO8956hsKSwM4HQdYn6z1jBFENQ9sKcA=";
    });
  };
  yubikey-agent = {
    pname = "yubikey-agent";
    version = "6d9db9c29100daacbe83e74653c79c94acc5958d";
    src = fetchFromGitHub ({
      owner = "FiloSottile";
      repo = "yubikey-agent";
      rev = "6d9db9c29100daacbe83e74653c79c94acc5958d";
      fetchSubmodules = false;
      sha256 = "sha256-mrdZcKD61S94ZkVH93SJhozmsXW/22ho08WMCrDEwhs=";
    });
  };
  yubikey-guide = {
    pname = "yubikey-guide";
    version = "dc29279197bbf866b63976395d2c69b1a95ad088";
    src = fetchFromGitHub ({
      owner = "drduh";
      repo = "YubiKey-Guide";
      rev = "dc29279197bbf866b63976395d2c69b1a95ad088";
      fetchSubmodules = false;
      sha256 = "sha256-MMcfiJ31SsrJdPCYn+5MuUxqLJzhY4VeqOS02T9AlL8=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.10.7.3311";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.10.7.3311/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-CVaUxVOUifsu1wyxwwoU7IwY7qocFLBQ4acHrTvNMx4=";
    };
  };
}
