# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.108.0-b.11";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.11/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-39GkJYPqvZXw+Esrmu1VvncwX6PAAGtdNTlXxRu001Y=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.108.0-b.11";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.11/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-6sl+Wn87qEji9n8n3JbEsYvkVsofKLz82k3i5wY1mq8=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.108.0-b.11";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.11/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-COknfV9Kk7VkKgUNfIgrrLg536w8jCfht+8eh93lU7Y=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.108.0-b.11";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.11/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-AD8Cxx4jGP6dQ/oGVBLR0si/Sc3EE0rmeUi3uXMWSmE=";
    };
  };
  adl = {
    pname = "adl";
    version = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
      fetchSubmodules = false;
      sha256 = "sha256-huGpDtkWrhZyKDNKXat8T3qtAyMjBaq8HFd1w1ThUVk=";
    });
  };
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
      fetchSubmodules = false;
      sha256 = "sha256-KXqicTZ9GZlNj1AH3tMmOrC8zjXoEnqo4JJJTBdiI4E=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./age-plugin-yubikey-08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "941eef9d5435b38775911d5c773a7dfda8adfea8";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "941eef9d5435b38775911d5c773a7dfda8adfea8";
      fetchSubmodules = false;
      sha256 = "sha256-k9zwrmXRG93BVExtJkZe7w8H1oOiI2aAHEkllqsv2jw=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "6e53e841f78c512f4d1eedb6a2409df746eea979";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "6e53e841f78c512f4d1eedb6a2409df746eea979";
      fetchSubmodules = false;
      sha256 = "sha256-iONF1YbWlW99k71lIUA/hw5+Rv1kf5M3mCItW6JmjbI=";
    });
  };
  asusctl = {
    pname = "asusctl";
    version = "45268bfb2bdabca8f1262b323047677135c4123f";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl";
      rev = "45268bfb2bdabca8f1262b323047677135c4123f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xSEMmcTCnUGmb1QJm924eOiS1aPj9LK0nwI1H1SELuE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./asusctl-45268bfb2bdabca8f1262b323047677135c4123f/Cargo.lock;
      outputHashes = {
        "eframe-0.18.0" = "sha256-7tRHLzUN78YA861slm3QfOluO8OXEyrNRkW4UZzn1kQ=";
      };
    };
  };
  avizo = {
    pname = "avizo";
    version = "67af5fd55279c25546d79cebdb4cb73440093082";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "67af5fd55279c25546d79cebdb4cb73440093082";
      fetchSubmodules = false;
      sha256 = "sha256-bZE9uTAaKUFP3zw6pJB8xpZjN00vM7lntn5zG3+2CYc=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "b7bac1dc761f7e231355e76351500a97b27b6803";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "b7bac1dc761f7e231355e76351500a97b27b6803";
      fetchSubmodules = false;
      sha256 = "sha256-SxydaQScu0kvBn3VOnT29/Sji0Y+7my+tO46mpMggAQ=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  betterdiscord-installer = {
    pname = "betterdiscord-installer";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/BetterDiscord/Installer/releases/download/v1.1.1/BetterDiscord-Linux.AppImage";
      sha256 = "sha256-EZj8vRyWbEfCagy/x3QTFADvE6Z76fqnDVRQZhD0S2k=";
    };
  };
  betterdiscordctl = {
    pname = "betterdiscordctl";
    version = "49a26fe82d441fbb8e51b0511969929f05cb2057";
    src = fetchFromGitHub ({
      owner = "bb010g";
      repo = "betterdiscordctl";
      rev = "49a26fe82d441fbb8e51b0511969929f05cb2057";
      fetchSubmodules = false;
      sha256 = "sha256-aBJDQAKmsBGoFaurADBTDqL9L/4+bWBk2y26vQ0LFx4=";
    });
  };
  bling = {
    pname = "bling";
    version = "70c894e58bb88dea55e9799ad373fdaea309da9e";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "70c894e58bb88dea55e9799ad373fdaea309da9e";
      fetchSubmodules = false;
      sha256 = "sha256-sUUMgdAmXAB/2ocwoo2OTZlWRbSRLdKi1oZB20qRNWU=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "8461496c083e0848815d3ab20185bf07a70c1d62";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "8461496c083e0848815d3ab20185bf07a70c1d62";
      fetchSubmodules = false;
      sha256 = "sha256-fU8ZbQUNU9JfcgWIQPl9SHUjmJ/lAEr/IcqBPLkmugs=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "v2.5.2";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "v2.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-Z9A2DRdX0LWjIKdHAHk2IRxsUzvC90Gf5ohFLXNHcsw=";
    });
  };
  caddy-dist = {
    pname = "caddy-dist";
    version = "v2.5.2";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "dist";
      rev = "v2.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-wzW0eb+O7JqQJkWtpMwV4G56uqLd1U2NduNAMPGvD3o=";
    });
  };
  caddy-git = {
    pname = "caddy-git";
    version = "2642bd72b7ca35b8622824fdffced2aefe1aaf11";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "2642bd72b7ca35b8622824fdffced2aefe1aaf11";
      fetchSubmodules = false;
      sha256 = "sha256-KGoOfpn7H+FPtJUk6zVC0SqB/F0NlU86vogHhXTRIBk=";
    });
  };
  cinny = {
    pname = "cinny";
    version = "c6812b5b116966e51ce677094acac86b5bb22618";
    src = fetchFromGitHub ({
      owner = "cinnyapp";
      repo = "cinny";
      rev = "c6812b5b116966e51ce677094acac86b5bb22618";
      fetchSubmodules = false;
      sha256 = "sha256-1XWynjuznNg6F/BZ3BRnTU2Jhbl6iKI+CQ5jP1V8Lyo=";
    });
  };
  cinny-bin = {
    pname = "cinny-bin";
    version = "2.0.4";
    src = fetchurl {
      url = "https://github.com/cinnyapp/cinny/releases/download/v2.0.4/cinny-v2.0.4.tar.gz";
      sha256 = "sha256-D4vA4Fldg+/TicuaXUlwxW50KqDzMBMUCSVpOW0Rulw=";
    };
  };
  cinny-desktop = {
    pname = "cinny-desktop";
    version = "84826aec5e6b692083eb376d5f76749d3c195263";
    src = fetchFromGitHub ({
      owner = "cinnyapp";
      repo = "cinny-desktop";
      rev = "84826aec5e6b692083eb376d5f76749d3c195263";
      fetchSubmodules = true;
      sha256 = "sha256-cpQzEIqZpYsgWS1cUvqxlVZetw+bOJgHGBlsGhtIGCE=";
    });
    cargoLock."src-tauri/Cargo.lock" = {
      lockFile = ./cinny-desktop-84826aec5e6b692083eb376d5f76749d3c195263/src-tauri/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  cinny-desktop-bin = {
    pname = "cinny-desktop-bin";
    version = "2.0.4";
    src = fetchurl {
      url = "https://github.com/cinnyapp/cinny-desktop/releases/download/v2.0.4/cinny_2.0.4_amd64.AppImage";
      sha256 = "sha256-9ZQyVcTsHja67DhuIyniTK/xr0C6qN7fiCmjt8enUd8=";
    };
  };
  conduit = {
    pname = "conduit";
    version = "0b926c2a31deff57a3526dd75d8c08775b02241a";
    src = fetchgit {
      url = "https://gitlab.com/famedly/conduit";
      rev = "0b926c2a31deff57a3526dd75d8c08775b02241a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-UQpMM4GDNcRKaYime1VyzyeTiAwvFDn79So1XibdD7U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./conduit-0b926c2a31deff57a3526dd75d8c08775b02241a/Cargo.lock;
      outputHashes = {
        "ruma-0.5.0" = "sha256-srmybII7j3xkSDVFvIiWUQnZsW+vEKKagSZhA5MRRQc=";
        "reqwest-0.11.9" = "sha256-wH/q7REnkz30ENBIK5Rlxnc1F6vOyuEANMHFmiVPaGw=";
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  conduit-toolbox = {
    pname = "conduit-toolbox";
    version = "805baa070528e6db7161ef35b75180e70d896541";
    src = fetchFromGitHub ({
      owner = "ShadowJonathan";
      repo = "conduit_toolbox";
      rev = "805baa070528e6db7161ef35b75180e70d896541";
      fetchSubmodules = false;
      sha256 = "sha256-vQ4r2Cvf2okeJ5qGIQ8mHoUmmrbUbY+bIEpee7XH6zA=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./conduit-toolbox-805baa070528e6db7161ef35b75180e70d896541/Cargo.lock;
      outputHashes = {
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.136";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.136/discord-canary-0.0.136.tar.gz";
      sha256 = "sha256-OrGg4jXziesHBhQORxREN/wq776RgNGaTyjJNV4pSAU=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "e124623ffced33c372f257071aa0949af03b37a5";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "e124623ffced33c372f257071aa0949af03b37a5";
      fetchSubmodules = false;
      sha256 = "sha256-yVu2/c9lqoAn2cIDud1JoVRRV6ZaC++HO1KVXvFJ8Z4=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "711cb96d9dbd5c79ea35e83cc1a75aa36125b841";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "711cb96d9dbd5c79ea35e83cc1a75aa36125b841";
      fetchSubmodules = false;
      sha256 = "sha256-Ir5uTB4ko6fdEGH2WiQHdA3dxiUbq1YsCF2vLz9Vyy4=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
      fetchSubmodules = false;
      sha256 = "sha256-70wtFxJOY9h4moT4hCTs4yfp2wGM39i5qnJerBVkpV4=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
      fetchSubmodules = false;
      sha256 = "sha256-5m+btrwhlk/nIZSasu+fTK1NhK0KdugVeD0KYOt0vE4=";
    });
  };
  duf = {
    pname = "duf";
    version = "ef60745b0ef94ea8abbbe54985a6550547c4e764";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "ef60745b0ef94ea8abbbe54985a6550547c4e764";
      fetchSubmodules = false;
      sha256 = "sha256-6IcvPbsk+dG/vlroD7L5me4YFwXtGeM+ZWNywBjBco4=";
    });
  };
  eww = {
    pname = "eww";
    version = "aac4c3aef4fa7dd42b3464be86d26debad66d7c1";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "aac4c3aef4fa7dd42b3464be86d26debad66d7c1";
      fetchSubmodules = false;
      sha256 = "sha256-h5NoiiLolTjpeX73qU1j5fxscTIjN+BIo2bsaJY+Pts=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./eww-aac4c3aef4fa7dd42b3464be86d26debad66d7c1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "29d4c43dc9d827a11be724b867d23be35dba30ec";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "29d4c43dc9d827a11be724b867d23be35dba30ec";
      fetchSubmodules = false;
      sha256 = "sha256-Jlfb9gL2yJgNq862Vcr35b+Rl6qYU5pupG7C7+bqC2I=";
    });
  };
  firefox-sidebar = {
    pname = "firefox-sidebar";
    version = "586c9ea4612b302ef85081e35b7368d2f7d5defd";
    src = fetchFromGitHub ({
      owner = "drannex42";
      repo = "FirefoxSidebar";
      rev = "586c9ea4612b302ef85081e35b7368d2f7d5defd";
      fetchSubmodules = false;
      sha256 = "sha256-wExL88eRr+5wTQ6NP08f1mPq9/+2Xu1SIsJv1WdTVuU=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "001726a565049ebfeb237a3a39b77104899b970e";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "001726a565049ebfeb237a3a39b77104899b970e";
      fetchSubmodules = false;
      sha256 = "sha256-lHVxvC/kxLLg9Ev9bpFGdiDLaFrT08Um44fWTmEIiDQ=";
    });
  };
  fluffychat = {
    pname = "fluffychat";
    version = "20596a2c5d17e3d7c7e1f70174297080790190f6";
    src = fetchgit {
      url = "https://gitlab.com/famedly/fluffychat";
      rev = "20596a2c5d17e3d7c7e1f70174297080790190f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-V5bHa8B6Fn+WFomaSVd/0yLRLJlNO6+1HTuooXVcotQ=";
    };
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  fx_cast = {
    pname = "fx_cast";
    version = "3709df869b0ccecd917e3fee22dbe54e95d4bdb9";
    src = fetchFromGitHub ({
      owner = "hensm";
      repo = "fx_cast";
      rev = "3709df869b0ccecd917e3fee22dbe54e95d4bdb9";
      fetchSubmodules = false;
      sha256 = "sha256-CDYOJlr5ucH9cpASzSgpHRbAAq7njRFqfmY5sgSx6yI=";
    });
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "bb2bf8e2cf998fc4403b995fd993b175663dfec3";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "bb2bf8e2cf998fc4403b995fd993b175663dfec3";
      fetchSubmodules = false;
      sha256 = "sha256-c6Tg8G5w3Hu3K6rB08cDCz+1CkzVxb+tVpoNqAyOPQ0=";
    });
  };
  hyprland = {
    pname = "hyprland";
    version = "ccd68049f727a52b59f8a432b132a16e683986e4";
    src = fetchFromGitHub ({
      owner = "hyprwm";
      repo = "hyprland";
      rev = "ccd68049f727a52b59f8a432b132a16e683986e4";
      fetchSubmodules = false;
      sha256 = "sha256-EiUkmG+6iwab3UEMcMBgd90OAsqk28vOdn/U0wUcElk=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "d47dbfada41aa4fb5df9f7cffe873786fc4849cc";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "d47dbfada41aa4fb5df9f7cffe873786fc4849cc";
      fetchSubmodules = false;
      sha256 = "sha256-Fq4K18v9Kf2sNuFn0EJGRI3GkaIuTu9m7PZnAbujfmE=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "3380c09d5812cec18ff7ed80e7e6d69d6afd3ab2";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "3380c09d5812cec18ff7ed80e7e6d69d6afd3ab2";
      fetchSubmodules = false;
      sha256 = "sha256-IkmNNYyV3eRAqTdh19d1hgNWtENmlMD5qYAGs34T3ZU=";
    });
  };
  inih = {
    pname = "inih";
    version = "r56";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r56";
      fetchSubmodules = false;
      sha256 = "sha256-7k3i3pElihastUDrdf9DyRZMe2UNFckfLUFGb4rbWLo=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-137-g260cee3";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-137-g260cee3-1_all.deb";
      sha256 = "sha256-jfp8rwVFcbCuVNW/yWcqxLXcn9YG26SYwwfh0JjGgdw=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-911";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-911-1_all.deb";
      sha256 = "sha256-YB66NYmonbVgKpzv2pyQv7r0hYKDeBAngxrE4yWPp0o=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.6436";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.6436.tar.bz2";
      sha256 = "sha256-Ht2PBmUxmlU6jNWKiyTrt9aoTOely+w8/1Yj6MMWoHQ=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.6436";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.6436-1_all.deb";
      sha256 = "sha256-57zDcH7w937fMKDtSbm+fWAA+gZ3aok7WU25+lGOnXE=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.2-21-g915593c5";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.2-21-g915593c5-1_all.deb";
      sha256 = "sha256-7B6010G1S8Tsqog4HeNlEyAjcXhMbzpZJx+Ot9XuAtA=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "d15b877fb5b0a5f90f010871c7dbfb163b874fe4";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "d15b877fb5b0a5f90f010871c7dbfb163b874fe4";
      fetchSubmodules = false;
      sha256 = "sha256-3oC2DOqxp/Kpcrt2g+KxpfQkh9XSrTVSHZ7yxQblNeI=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "0.7.0";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  light = {
    pname = "light";
    version = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
      fetchSubmodules = false;
      sha256 = "sha256-8v9ytywv2+/qqN94g44vHMGsbKueYSDXq76wo95pSFE=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  mapcidr = {
    pname = "mapcidr";
    version = "v1.0.1";
    src = fetchFromGitHub ({
      owner = "projectdiscovery";
      repo = "mapcidr";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-lSAA1lWHGQr1tguBdBePdkN+CNKkxmLweI6oqzzOG6A=";
    });
  };
  matrix-appservice-discord = {
    pname = "matrix-appservice-discord";
    version = "7d77e6d6080ecd31aba9f2f6098b388eea771685";
    src = fetchFromGitHub ({
      owner = "matrix-org";
      repo = "matrix-appservice-discord";
      rev = "7d77e6d6080ecd31aba9f2f6098b388eea771685";
      fetchSubmodules = false;
      sha256 = "sha256-RbyVtI33ofeQ195JOO8TutrgZ3hzLlP30Xvevd0MwdE=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "104.0.1293.44";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_104.0.1293.44-1_amd64.deb";
      sha256 = "sha256-m1zktD5oxGLdlCk2GzNItmYbeOm0WJ220DrpaadmTAU=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "105.0.1336.2";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_105.0.1336.2-1_amd64.deb";
      sha256 = "sha256-Sm8j41poy1iXfov5vvlrEcK0FZ8KWvlN6G1ADUjfJUE=";
    };
  };
  microsoft-edge-stable = {
    pname = "microsoft-edge-stable";
    version = "104.0.1293.47";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_104.0.1293.47-1_amd64.deb";
      sha256 = "sha256-lhvuzwz1Fqsrtzw3yigwD7HPu+wGFLVX2G4/bh+0pnI=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "086b2457e8b769d6af44917759403f76b8b3b90e";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "086b2457e8b769d6af44917759403f76b8b3b90e";
      fetchSubmodules = false;
      sha256 = "sha256-WvDS1z33/j8uXMNFGqZ8D0kRnCqhKzgtXdMVOoo9vxg=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.35.1";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.35.1.tar.gz";
      sha256 = "sha256-yR1ew5VDQz7elr7hJRxI/iF0xupM4tD8+eOSJd9GoVM=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.34.0";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.34.0.tar.gz";
      sha256 = "sha256-+i4MgMDunCoJjDLLdp1r0y2CxVuDqw/Ed7aNg0+FtmA=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "spwhitt";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "97987692deb6ab09816f40972fe5b04c1ddebd7e";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "97987692deb6ab09816f40972fe5b04c1ddebd7e";
      fetchSubmodules = false;
      sha256 = "sha256-zeQ+ValEtCZjvC9S8hADzigqdzikiXeEEOCUAaXtLXI=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "583ddfde0bd3ebc93e03f047d6419f696826803e";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "583ddfde0bd3ebc93e03f047d6419f696826803e";
      fetchSubmodules = false;
      sha256 = "sha256-eC9wLJvd3iXd2oeY+0lShnEfKYkgi4QT4D7fSG6NzE8=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-Rr0UpJa7kemczCqNn6b8HNtW6PiWO/Ez1LUh/WNk8S8=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "f6a4c9ffbe4f5761202a1678720323c72adfed2b";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "f6a4c9ffbe4f5761202a1678720323c72adfed2b";
      fetchSubmodules = false;
      sha256 = "sha256-nrVeuEERRxTk/ATCd0x371RVFxY9BxbHFOHMDO+bpzI=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./ouch-f6a4c9ffbe4f5761202a1678720323c72adfed2b/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "896acabab11e977a5a07e2a59d9b35bfeb167263";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "896acabab11e977a5a07e2a59d9b35bfeb167263";
      fetchSubmodules = false;
      sha256 = "sha256-QaEuewhAbaBW+rYt0eFwV1hD466ydI6ihGWasFICurI=";
    });
  };
  playit-agent = {
    pname = "playit-agent";
    version = "18e692e513437c792c4b56977b72db33342a22c4";
    src = fetchFromGitHub ({
      owner = "playit-cloud";
      repo = "playit-agent";
      rev = "18e692e513437c792c4b56977b72db33342a22c4";
      fetchSubmodules = false;
      sha256 = "sha256-/7zWL3LNoT99T9o9Ozr07zoFnpjnnXBWJseUUmAx3zw=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./playit-agent-18e692e513437c792c4b56977b72db33342a22c4/Cargo.lock;
      outputHashes = {
        "webbrowser-0.5.5" = "sha256-9LhheWDmQKUdKLsYo5Uo+Z3PlKeMMnZvfWyXOMvEf7M=";
      };
    };
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.45.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.45.0.tar.gz";
      sha256 = "sha256-75ZFzhRsczkwhiUl1upKjSvmqN0RkXaM8cKr4zLgi4w=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "bd4a7d5d3f2c6fcdc7d42abeee1fd69d505db835";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "bd4a7d5d3f2c6fcdc7d42abeee1fd69d505db835";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2ZOLTzv8/33LoEAdosrOa8rfGolyuP2RUAmtPnaI2T4=";
    };
  };
  pure = {
    pname = "pure";
    version = "2d89ef1d06f76997790b45df5ac447f0c3ffd34c";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "2d89ef1d06f76997790b45df5ac447f0c3ffd34c";
      fetchSubmodules = false;
      sha256 = "sha256-KO1z5/9vRh4JNNawbUhy9Zgr3ywGfpSEMx/4N0V+vmw=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "2856b096c3136eed67da47ab47a69ce0b0586ae9";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "2856b096c3136eed67da47ab47a69ce0b0586ae9";
      fetchSubmodules = false;
      sha256 = "sha256-RTXJtP0cwZmfFpzH62FzOm3Wvh9aFSz9xyS2IYzLQ9w=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
      fetchSubmodules = false;
      sha256 = "sha256-muDz1rFTvWOZGrEzql+VZbs42bS09BREjKS5OpBu2g8=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "72b4cf914e6481b013afd57af5777efd3c7a0fa8";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "72b4cf914e6481b013afd57af5777efd3c7a0fa8";
      fetchSubmodules = false;
      sha256 = "sha256-59EudsSM8FWosQ04zBT8Ppjm7ICTVpe8Qs65CiWaSlk=";
    });
  };
  revanced-cli = {
    pname = "revanced-cli";
    version = "2.9.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-cli/releases/download/v2.9.1/revanced-cli-2.9.1-all.jar";
      sha256 = "sha256-tAENQVL2ha0p2jNoB8DzYRgPZaIcaNmRj7xedrlPtJY=";
    };
  };
  revanced-integrations = {
    pname = "revanced-integrations";
    version = "0.31.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-integrations/releases/download/v0.31.1/app-release-unsigned.apk";
      sha256 = "sha256-lO2AUp1pLzar71DhpBrrvHQCn8iBz2mnSJvcSJWm3CY=";
    };
  };
  revanced-patches-dex = {
    pname = "revanced-patches-dex";
    version = "2.32.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-patches/releases/download/v2.32.1/revanced-patches-2.32.1.dex";
      sha256 = "sha256-FrGxN2hCTojmN0ww5YWMWDl3QYzrd5a2umnZKx4mDQM=";
    };
  };
  revanced-patches-jar = {
    pname = "revanced-patches-jar";
    version = "2.32.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-patches/releases/download/v2.32.1/revanced-patches-2.32.1.jar";
      sha256 = "sha256-f6h0Z6DUZCcUyy27FFZbZxYv3GxDHrS9qWYN+mGfqOU=";
    };
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "6801bd85bbfa59143b8ec443a05b22ef977b4349";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "6801bd85bbfa59143b8ec443a05b22ef977b4349";
      fetchSubmodules = true;
      sha256 = "sha256-3kPzEkljNXOf+4HSCrjXm6BUxusDT9NP2wbxqBRvLRk=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "e5e57943cb31ad6937d8b9d153e1ee73c6f6458a";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "e5e57943cb31ad6937d8b9d153e1ee73c6f6458a";
      fetchSubmodules = false;
      sha256 = "sha256-UCSjjUW0OyOl6snEfSJqEA4r9RVSBvSqwIS0NEicL7A=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./rustdesk-e5e57943cb31ad6937d8b9d153e1ee73c6f6458a/Cargo.lock;
      outputHashes = {
        "trayicon-0.1.3-1" = "sha256-shLsOncL3ySRN/m9SjvjurneMaXhGDWks0QF3pVz6J0=";
        "rust-pulsectl-0.2.12" = "sha256-8jXTspWvjONFcvw9/Z8C43g4BuGZ3rsG32tvLMQbtbM=";
        "confy-0.4.0" = "sha256-e91cvEixhpPzIthAxzTa3fDY6eCsHUy/eZQAqs7QTDo=";
        "parity-tokio-ipc-0.7.3-1" = "sha256-eULJePtBu0iBI3It/bPH0h82Obsb1PJALgwYwrnCFYI=";
        "tokio-socks-0.5.1-1" = "sha256-45QQ6FrhGU9uEhbKXTKd/mY6MDumO6p46NmlakdyDQk=";
        "hwcodec-0.1.0" = "sha256-RRiEfz0cO8d50ADwn4PfLlQSAssqyNnL6K7yADkrzcM=";
        "mouce-0.2.1" = "sha256-YcS7rn3eWmFWIq3X6ytwPRp3eWuXjJwseqsMoA6k7/w=";
        "sciter-rs-0.5.57" = "sha256-ZZnZDhMjK0LjgmK0da1yvB0uoKueLhhhQtzmjoN+1R0=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
        "evdev-0.11.5" = "sha256-aoPmjGi/PftnH6ClEWXHvIj0X3oh15ZC1q7wPC1XPr0=";
        "rdev-0.5.0-1" = "sha256-aaC2Aq6xBSKV7+eUZWKLSmDBFwNcHWkgw1jJWQXvNqA=";
      };
    };
  };
  rustdesk-server = {
    pname = "rustdesk-server";
    version = "848b5aedb7e8bda0f582706c792ffbab2d657a39";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server";
      rev = "848b5aedb7e8bda0f582706c792ffbab2d657a39";
      fetchSubmodules = false;
      sha256 = "sha256-5LsnT6NI5JmcRnIirn3YNOQU+Y8Bjpg+/FC+bx16LcI=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./rustdesk-server-848b5aedb7e8bda0f582706c792ffbab2d657a39/Cargo.lock;
      outputHashes = {
        "confy-0.4.0" = "sha256-e91cvEixhpPzIthAxzTa3fDY6eCsHUy/eZQAqs7QTDo=";
        "async-speed-limit-0.3.1" = "sha256-iOel6XA07RPrBjQAFLnxXX4VBpDrYZaqQc9clnsOorI=";
        "tokio-socks-0.5.1" = "sha256-inmAJk0fAlsVNIwfD/M+htwIdQHwGSTRrEy6N/mspMI=";
      };
    };
  };
  sddm = {
    pname = "sddm";
    version = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
      fetchSubmodules = false;
      sha256 = "sha256-FfbYQrHndU7rtI8CKK7wtn3pdufBSiXUgefozCja4Do=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-SIht9sqmeijEeU4uLwm+tlZtFlTnD/G5GH8haUL6dlU=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-g/SzgU3vOzm8uRuA6AN/N8Tnrl2Vpya58hx99dGfecI=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-jnhTTmSy5J8MJotbsI8g5hxotgjvyDbccymjABwajYw=";
    };
  };
  snui = {
    pname = "snui";
    version = "16377f082ce976882788168c4fb722f1da2e17c2";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "16377f082ce976882788168c4fb722f1da2e17c2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-J8zrinml+S3Z5gqxQkwmaQX5oA1+WmUym0s/fISVQx4=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "6f473f28151c75e08e83fb280dd30fadd22d9c04";
    src = fetchFromGitHub ({
      owner = "spicetify";
      repo = "spicetify-cli";
      rev = "6f473f28151c75e08e83fb280dd30fadd22d9c04";
      fetchSubmodules = false;
      sha256 = "sha256-Gzq9SeLInfAoF/nUf0gq3l0MC3OKnuTB8u/utcMRgG8=";
    });
  };
  spicetify-marketplace = {
    pname = "spicetify-marketplace";
    version = "240cd80049f0ff08413c83b603ff36535ea615f8";
    src = fetchFromGitHub ({
      owner = "spicetify";
      repo = "spicetify-marketplace";
      rev = "240cd80049f0ff08413c83b603ff36535ea615f8";
      fetchSubmodules = false;
      sha256 = "sha256-3/Slve7Lq6sE3gTMRslNpotFNmfGdwJryvz2JI7RYbc=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "9a2fcb5a545da368e4bf1d8189f58d0f664f3115";
    src = fetchFromGitHub ({
      owner = "spicetify";
      repo = "spicetify-themes";
      rev = "9a2fcb5a545da368e4bf1d8189f58d0f664f3115";
      fetchSubmodules = false;
      sha256 = "sha256-ikF7v7U+iFKOs7sffUymH/O58ItEDfz8UpTMw6GC9aE=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.84.716.gc5f8b819";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_60.snap";
      sha256 = "sha256-ho3WjGNjmHsERzC3FLgliuVSQWK2F5ec0ddQSfq6oyI=";
    };
  };
  spotify-1_1_83_954_gd226dfe8 = {
    pname = "spotify-1_1_83_954_gd226dfe8";
    version = "1.1.83.954.gd226dfe8";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_59.snap";
      sha256 = "sha256-IAktrSHXcoO6MxId4mJphMknOik0NG67Imwy4pLFCk8=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "993336f74ec89cb6cad23dd009251e70548761b6";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "993336f74ec89cb6cad23dd009251e70548761b6";
      fetchSubmodules = false;
      sha256 = "sha256-IILJCvH+dyKRRUERW9zicsoRoCBiKw03MTnitZb2hp0=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./spotifyd-993336f74ec89cb6cad23dd009251e70548761b6/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "cb0ecfb19039e2478bd702bfd7d51c6aaf65a3de";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "cb0ecfb19039e2478bd702bfd7d51c6aaf65a3de";
      fetchSubmodules = false;
      sha256 = "sha256-fOVEowRrSv1E3aj1nYmAlmpXYPkYFuwpL9SGyYs8Ri8=";
    });
  };
  supergfxctl = {
    pname = "supergfxctl";
    version = "46f808da96802b6cc27e1b195bb500889fcf3a49";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl";
      rev = "46f808da96802b6cc27e1b195bb500889fcf3a49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FTDJpmWsgF9CGfnVLYu7UosluQa/I5/omhOil8oEW64=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./supergfxctl-46f808da96802b6cc27e1b195bb500889fcf3a49/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  sway-borders = {
    pname = "sway-borders";
    version = "3890d2a2fb255276993891e2da5f6cb33670efcd";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "3890d2a2fb255276993891e2da5f6cb33670efcd";
      fetchSubmodules = false;
      sha256 = "sha256-esMruivwq6XPPYJWaW825+d8rD8NOxbJQqVfAeBtXe0=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "4b54b85d964243eef8d77ea0505eed728c62387f";
    src = fetchFromGitHub ({
      owner = "jirutka";
      repo = "swaylock-effects";
      rev = "4b54b85d964243eef8d77ea0505eed728c62387f";
      fetchSubmodules = false;
      sha256 = "sha256-QvMnJ5/uL/DvBhP9kagZJh9vwXBF2sCw3HWkfI4FDH0=";
    });
  };
  swhkd = {
    pname = "swhkd";
    version = "2997d94b6dc6b460abc1131f17113e9e543c869e";
    src = fetchFromGitHub ({
      owner = "waycrate";
      repo = "swhkd";
      rev = "2997d94b6dc6b460abc1131f17113e9e543c869e";
      fetchSubmodules = false;
      sha256 = "sha256-Mbh0Yx/v9l/kuXP2hUpEjs9orZhBI9ciytoxBUrUVkI=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-2997d94b6dc6b460abc1131f17113e9e543c869e/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  tailscale = {
    pname = "tailscale";
    version = "ec9d13bce56ddb01f127f44e7d79503069f76bbf";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "ec9d13bce56ddb01f127f44e7d79503069f76bbf";
      fetchSubmodules = false;
      sha256 = "sha256-mUtWbn2uV6/11pzZ5hkZ7K3WVhvPCCEXCaPoi3gM6ro=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "8e943debe7801a79c0e146cf9f53f0b9aa9d5e72";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "8e943debe7801a79c0e146cf9f53f0b9aa9d5e72";
      fetchSubmodules = false;
      sha256 = "sha256-iIKth2qPc8S5h0ebasoiIGiEEy+mip8Ris1HWW/p6Ko=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.5.00.10453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.10453_amd64.deb";
      sha256 = "sha256-fLVw2axSMetuaoRzjg+x4DRYY8WP5TQbL7LbfF6LFfA=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "145f651d2a2e507879b0163e46c590b01185839e";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-x8D5XrvMjNV2R5CXs/ficOhwXNTRglsQxPhfvuUF4nM=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "54ae1e71f34a18e858167319ca046e5ccf742eeb";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "54ae1e71f34a18e858167319ca046e5ccf742eeb";
      fetchSubmodules = false;
      sha256 = "sha256-9+q5rGAQjWw9ZYss6ijX+y76anACWpfNSBraZ/OV9oY=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.25.2";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.25.2";
      fetchSubmodules = false;
      sha256 = "sha256-6CpdvLCw7SUmWm9NHAxFAo454Rrp1FloDp67YAr0pjQ=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./vaultwarden-1.25.2/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2022.6.2";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2022.6.2/bw_web_v2022.6.2.tar.gz";
      sha256 = "sha256-IG/eCBTUa7eKeaelqxCWO+rrXJUuBanhsYwklftxdOE=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.79";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.79/ventoy-1.0.79-linux.tar.gz";
      sha256 = "sha256-azkoDquN/i01QHsd1wJG79kdhHhBvXzPXIRnjKHAHNE=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  waydroid = {
    pname = "waydroid";
    version = "c90b59266a3bd21c637c9123aeaadd7b955cce80";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "c90b59266a3bd21c637c9123aeaadd7b955cce80";
      fetchSubmodules = false;
      sha256 = "sha256-foGYEbjiMpdQpqBkr+ivY9GWAi/yS8rEGtPQb/RApnQ=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "140f9832314247e5a122ca252d139449255ad7c3";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "140f9832314247e5a122ca252d139449255ad7c3";
      fetchSubmodules = false;
      sha256 = "sha256-tUEeczs3J//2ZrZkAsSn3C+GScRPaIgheRM2wByS8p4=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "55b836f1c726969505aa3436e68df96c5d735a55";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "55b836f1c726969505aa3436e68df96c5d735a55";
      fetchSubmodules = false;
      sha256 = "sha256-Vl+OxT0xmb6o0Za++xT0vS0X2JiFWm+F/sr2lG2c7rE=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "ee243fe41b215fa4016c89dd9510b5f1be7871c8";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "ee243fe41b215fa4016c89dd9510b5f1be7871c8";
      fetchSubmodules = false;
      sha256 = "sha256-rk2XYoHsI8ulfwcpNKEJHSVwA2xLQLi/4xT4e9fFWLY=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2449.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2449.0-linux-x64.zip";
      sha256 = "sha256-vsr6eymKqU2Y6HM4DPHnUfVkB2BQ1HSSWvk1tNhUA5Y=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  ydotool = {
    pname = "ydotool";
    version = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
      fetchSubmodules = false;
      sha256 = "sha256-maXXGCqB8dkGO8956hsKSwM4HQdYn6z1jBFENQ9sKcA=";
    });
  };
  yubikey-agent = {
    pname = "yubikey-agent";
    version = "6d9db9c29100daacbe83e74653c79c94acc5958d";
    src = fetchFromGitHub ({
      owner = "FiloSottile";
      repo = "yubikey-agent";
      rev = "6d9db9c29100daacbe83e74653c79c94acc5958d";
      fetchSubmodules = false;
      sha256 = "sha256-mrdZcKD61S94ZkVH93SJhozmsXW/22ho08WMCrDEwhs=";
    });
  };
  yubikey-guide = {
    pname = "yubikey-guide";
    version = "dc29279197bbf866b63976395d2c69b1a95ad088";
    src = fetchFromGitHub ({
      owner = "drduh";
      repo = "YubiKey-Guide";
      rev = "dc29279197bbf866b63976395d2c69b1a95ad088";
      fetchSubmodules = false;
      sha256 = "sha256-MMcfiJ31SsrJdPCYn+5MuUxqLJzhY4VeqOS02T9AlL8=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.11.3.3882";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.11.3.3882/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-AKW3jQaew3VrMkyfMSEjR86BT6kE3Qe/2Giy7EChoCc=";
    };
  };
}
