# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.108.0-b.10";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.10/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-V8DML1NpVFRbVqITJZiU8UNBR4c4oZk6zfLNt+KBGVs=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.108.0-b.10";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.10/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-Lv8d9jXzcbmg9GvRhF1igRbF19CdQKNOkUE71xRNeMQ=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.108.0-b.10";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.10/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-ga5aC7M4J8zqfWyDOIHT11fNw+mqMVYWm5pG65MLyX8=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.108.0-b.10";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.108.0-b.10/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-eMFvEtrWcVPTNjWgqEtnQ6MrRxb/Q8UzpWCG05SRF7E=";
    };
  };
  adl = {
    pname = "adl";
    version = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "65f68e1dcae4c0caa52668d3a854269e7d226f7c";
      fetchSubmodules = false;
      sha256 = "sha256-huGpDtkWrhZyKDNKXat8T3qtAyMjBaq8HFd1w1ThUVk=";
    });
  };
  age-plugin-yubikey = {
    pname = "age-plugin-yubikey";
    version = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
    src = fetchFromGitHub ({
      owner = "str4d";
      repo = "age-plugin-yubikey";
      rev = "08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb";
      fetchSubmodules = false;
      sha256 = "sha256-KXqicTZ9GZlNj1AH3tMmOrC8zjXoEnqo4JJJTBdiI4E=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./age-plugin-yubikey-08ba0aa1ec3ced531dcb16a9db1795d6ee9b52cb/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "941eef9d5435b38775911d5c773a7dfda8adfea8";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "941eef9d5435b38775911d5c773a7dfda8adfea8";
      fetchSubmodules = false;
      sha256 = "sha256-k9zwrmXRG93BVExtJkZe7w8H1oOiI2aAHEkllqsv2jw=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  argonone-fancontrold = {
    pname = "argonone-fancontrold";
    version = "b6b960eb492224012680f56e3c6fba13502e542c";
    src = fetchFromGitHub ({
      owner = "mgdm";
      repo = "argonone-utils";
      rev = "b6b960eb492224012680f56e3c6fba13502e542c";
      fetchSubmodules = false;
      sha256 = "sha256-v098KH8TgzGgCc7+59SVWy19xW456eXX/BDdt9zzVhk=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "a5e75c4bd3b23ea6537d1d6cbb488e6e95c06ecc";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "a5e75c4bd3b23ea6537d1d6cbb488e6e95c06ecc";
      fetchSubmodules = false;
      sha256 = "sha256-6IFsIHXYKAqrZ/3gYa1VF1J4/a2lt20vswfON0G8j8I=";
    });
  };
  asusctl = {
    pname = "asusctl";
    version = "e6ebf72a111e9374350939af9f6ff0d91e30f3e0";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl";
      rev = "e6ebf72a111e9374350939af9f6ff0d91e30f3e0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-TykCdp7AkfJ449ejUpgDClc7FCkXz7gOaNFCX2E/9iQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./asusctl-e6ebf72a111e9374350939af9f6ff0d91e30f3e0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  avizo = {
    pname = "avizo";
    version = "67af5fd55279c25546d79cebdb4cb73440093082";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "67af5fd55279c25546d79cebdb4cb73440093082";
      fetchSubmodules = false;
      sha256 = "sha256-bZE9uTAaKUFP3zw6pJB8xpZjN00vM7lntn5zG3+2CYc=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "b7bac1dc761f7e231355e76351500a97b27b6803";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "b7bac1dc761f7e231355e76351500a97b27b6803";
      fetchSubmodules = false;
      sha256 = "sha256-SxydaQScu0kvBn3VOnT29/Sji0Y+7my+tO46mpMggAQ=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  betterdiscord-installer = {
    pname = "betterdiscord-installer";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/BetterDiscord/Installer/releases/download/v1.1.1/BetterDiscord-Linux.AppImage";
      sha256 = "sha256-EZj8vRyWbEfCagy/x3QTFADvE6Z76fqnDVRQZhD0S2k=";
    };
  };
  betterdiscordctl = {
    pname = "betterdiscordctl";
    version = "49a26fe82d441fbb8e51b0511969929f05cb2057";
    src = fetchFromGitHub ({
      owner = "bb010g";
      repo = "betterdiscordctl";
      rev = "49a26fe82d441fbb8e51b0511969929f05cb2057";
      fetchSubmodules = false;
      sha256 = "sha256-aBJDQAKmsBGoFaurADBTDqL9L/4+bWBk2y26vQ0LFx4=";
    });
  };
  bling = {
    pname = "bling";
    version = "e384951c321420dcaada7ad4381a644f2c7eea83";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "e384951c321420dcaada7ad4381a644f2c7eea83";
      fetchSubmodules = false;
      sha256 = "sha256-P725jMxPK7TOhLvvwQyyJBSOU48EDQeXIfcuweq6TUw=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "9a9474f5539215744df438950fad30087b58b65d";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "9a9474f5539215744df438950fad30087b58b65d";
      fetchSubmodules = false;
      sha256 = "sha256-PyRqpFMBasy8oWXsRcublo8oJD6irH6dJUCbcZoCzfk=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "v2.5.2";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "v2.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-Z9A2DRdX0LWjIKdHAHk2IRxsUzvC90Gf5ohFLXNHcsw=";
    });
  };
  caddy-git = {
    pname = "caddy-git";
    version = "abad9bc256eea7353b9959d066f5b7ea64990a22";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "abad9bc256eea7353b9959d066f5b7ea64990a22";
      fetchSubmodules = false;
      sha256 = "sha256-yRLn9RfcD30Wck6ht6pKhNZ+ftnZJKJXL4RtF6OUTBs=";
    });
  };
  cinny = {
    pname = "cinny";
    version = "2.0.4";
    src = fetchurl {
      url = "https://github.com/cinnyapp/cinny/releases/download/v2.0.4/cinny-v2.0.4.tar.gz";
      sha256 = "sha256-D4vA4Fldg+/TicuaXUlwxW50KqDzMBMUCSVpOW0Rulw=";
    };
  };
  cinny-desktop = {
    pname = "cinny-desktop";
    version = "7cc558d82658697153759a144b47c9cd1c22dd25";
    src = fetchFromGitHub ({
      owner = "cinnyapp";
      repo = "cinny-desktop";
      rev = "7cc558d82658697153759a144b47c9cd1c22dd25";
      fetchSubmodules = true;
      sha256 = "sha256-XteKYFJqyxLzii35BL2Tw1C3OEVP4GZ20YRfebODCaY=";
    });
    cargoLock."src-tauri/Cargo.lock" = {
      lockFile = ./cinny-desktop-7cc558d82658697153759a144b47c9cd1c22dd25/src-tauri/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  cinny-desktop-bin = {
    pname = "cinny-desktop-bin";
    version = "2.0.4";
    src = fetchurl {
      url = "https://github.com/cinnyapp/cinny-desktop/releases/download/v2.0.4/cinny_2.0.4_amd64.AppImage";
      sha256 = "sha256-9ZQyVcTsHja67DhuIyniTK/xr0C6qN7fiCmjt8enUd8=";
    };
  };
  conduit = {
    pname = "conduit";
    version = "0b926c2a31deff57a3526dd75d8c08775b02241a";
    src = fetchgit {
      url = "https://gitlab.com/famedly/conduit";
      rev = "0b926c2a31deff57a3526dd75d8c08775b02241a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-UQpMM4GDNcRKaYime1VyzyeTiAwvFDn79So1XibdD7U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./conduit-0b926c2a31deff57a3526dd75d8c08775b02241a/Cargo.lock;
      outputHashes = {
        "ruma-0.5.0" = "sha256-srmybII7j3xkSDVFvIiWUQnZsW+vEKKagSZhA5MRRQc=";
        "reqwest-0.11.9" = "sha256-wH/q7REnkz30ENBIK5Rlxnc1F6vOyuEANMHFmiVPaGw=";
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  conduit-toolbox = {
    pname = "conduit-toolbox";
    version = "805baa070528e6db7161ef35b75180e70d896541";
    src = fetchFromGitHub ({
      owner = "ShadowJonathan";
      repo = "conduit_toolbox";
      rev = "805baa070528e6db7161ef35b75180e70d896541";
      fetchSubmodules = false;
      sha256 = "sha256-vQ4r2Cvf2okeJ5qGIQ8mHoUmmrbUbY+bIEpee7XH6zA=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./conduit-toolbox-805baa070528e6db7161ef35b75180e70d896541/Cargo.lock;
      outputHashes = {
        "heed-0.10.6" = "sha256-rm02pJ6wGYN4SsAbp85jBVHDQ5ITjZZd+79EC2ubRsY=";
      };
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.136";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.136/discord-canary-0.0.136.tar.gz";
      sha256 = "sha256-OrGg4jXziesHBhQORxREN/wq776RgNGaTyjJNV4pSAU=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "91388b148cbdcb9056b2b039a28d651a5b4b34bf";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "91388b148cbdcb9056b2b039a28d651a5b4b34bf";
      fetchSubmodules = false;
      sha256 = "sha256-tQSQBfnXWAH95eF+YqIjK4/UigveCwF8Jcq/6qaYdlk=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "2cf9e7bf2ce445632b68aa47d6e2e5aacea7afc1";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "2cf9e7bf2ce445632b68aa47d6e2e5aacea7afc1";
      fetchSubmodules = false;
      sha256 = "sha256-6jNs8vigrwKk47Voe42J9QYMTP7KnNAtJ5vFZTUW680=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "8da36b8e5f07a20af2ca8a1dd3c81eedf7282fa1";
      fetchSubmodules = false;
      sha256 = "sha256-70wtFxJOY9h4moT4hCTs4yfp2wGM39i5qnJerBVkpV4=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "71a74d22ed700650a83b7cb653bd92b0ed3cd01a";
      fetchSubmodules = false;
      sha256 = "sha256-5m+btrwhlk/nIZSasu+fTK1NhK0KdugVeD0KYOt0vE4=";
    });
  };
  duf = {
    pname = "duf";
    version = "ef60745b0ef94ea8abbbe54985a6550547c4e764";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "ef60745b0ef94ea8abbbe54985a6550547c4e764";
      fetchSubmodules = false;
      sha256 = "sha256-6IcvPbsk+dG/vlroD7L5me4YFwXtGeM+ZWNywBjBco4=";
    });
  };
  eww = {
    pname = "eww";
    version = "b2f60a1f436567bca7bb4c8edd04096c573c4caa";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "b2f60a1f436567bca7bb4c8edd04096c573c4caa";
      fetchSubmodules = false;
      sha256 = "sha256-z54zjlAamMFg/dnQ8P9lv/OkQTqFlo9e8Z4Tg5uXC7Y=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./eww-b2f60a1f436567bca7bb4c8edd04096c573c4caa/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "29d4c43dc9d827a11be724b867d23be35dba30ec";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "29d4c43dc9d827a11be724b867d23be35dba30ec";
      fetchSubmodules = false;
      sha256 = "sha256-Jlfb9gL2yJgNq862Vcr35b+Rl6qYU5pupG7C7+bqC2I=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "57c8e8d893669cd83d8b279ea3ff6db50b16aa48";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "57c8e8d893669cd83d8b279ea3ff6db50b16aa48";
      fetchSubmodules = false;
      sha256 = "sha256-V0taTVCSuVKy0f5gtJ7gRmhkvpZdhLRfoJyTJuk7FFI=";
    });
  };
  fluffychat = {
    pname = "fluffychat";
    version = "839711bb9bd573fc43426408e0ade62f895537f7";
    src = fetchgit {
      url = "https://gitlab.com/famedly/fluffychat";
      rev = "839711bb9bd573fc43426408e0ade62f895537f7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-MwT9einz6sNZ0rNLvULPcDJy6IJ4IG1Ae0651Jx1uig=";
    };
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  fx_cast = {
    pname = "fx_cast";
    version = "cec6e625cc36e5e5346e1746f511ebd739c75832";
    src = fetchFromGitHub ({
      owner = "hensm";
      repo = "fx_cast";
      rev = "cec6e625cc36e5e5346e1746f511ebd739c75832";
      fetchSubmodules = false;
      sha256 = "sha256-+P7T5+ispMjL+qC1l8P6JAMpIiD+HO7r6aBpdnbP23c=";
    });
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "6981a24ead15010f25a8c31e49c862891d9069f5";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "6981a24ead15010f25a8c31e49c862891d9069f5";
      fetchSubmodules = false;
      sha256 = "sha256-cjDRvzBHA8cUWpuDg5Tnn+6IqPeTriRLEZ5aR6JQFLU=";
    });
  };
  hyprland = {
    pname = "hyprland";
    version = "189cbe9f098816231673e9ebe1ac5fa5872f33e7";
    src = fetchFromGitHub ({
      owner = "vaxerski";
      repo = "hyprland";
      rev = "189cbe9f098816231673e9ebe1ac5fa5872f33e7";
      fetchSubmodules = false;
      sha256 = "sha256-j6zaEtkCqfZKp2bYwSwWketGH8amA+wElWlXy7XIGVo=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "00a78d6d0bc1d964cdd50959bcc37f340678dab4";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "00a78d6d0bc1d964cdd50959bcc37f340678dab4";
      fetchSubmodules = false;
      sha256 = "sha256-R5fwuJb15a+ZQbJldNXbiE6tCeE4hgnyH6W0F2VSiK0=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "3380c09d5812cec18ff7ed80e7e6d69d6afd3ab2";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "3380c09d5812cec18ff7ed80e7e6d69d6afd3ab2";
      fetchSubmodules = false;
      sha256 = "sha256-IkmNNYyV3eRAqTdh19d1hgNWtENmlMD5qYAGs34T3ZU=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-137-g260cee3";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-137-g260cee3-1_all.deb";
      sha256 = "sha256-jfp8rwVFcbCuVNW/yWcqxLXcn9YG26SYwwfh0JjGgdw=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-909";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-909-1_all.deb";
      sha256 = "sha256-TU5RqEO45zjKiA1FohThkcINDJInagTzt610M3JQcrw=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.6373";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.6373.tar.bz2";
      sha256 = "sha256-plMge9sCVHd9MbCCTlUynaXryvRuvYkD6IOW4MzxW/M=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.6373";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.6373-1_all.deb";
      sha256 = "sha256-UQmOLXO0T8ghzEe6ITD15KkLi9GmFTtMJaxmDZo/N58=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.2-18-gade06bf8";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.2-18-gade06bf8-1_all.deb";
      sha256 = "sha256-PI5RUXJYTeGXS7/+xHmSgrPm0XyPDAdPv8PIBsm3c+w=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "d15b877fb5b0a5f90f010871c7dbfb163b874fe4";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "d15b877fb5b0a5f90f010871c7dbfb163b874fe4";
      fetchSubmodules = false;
      sha256 = "sha256-3oC2DOqxp/Kpcrt2g+KxpfQkh9XSrTVSHZ7yxQblNeI=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "c5fb45423ec1ee1080e442e061ccfcdb98b32e4a";
      fetchSubmodules = false;
      sha256 = "sha256-8v9ytywv2+/qqN94g44vHMGsbKueYSDXq76wo95pSFE=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  matrix-appservice-discord = {
    pname = "matrix-appservice-discord";
    version = "v1.0.0";
    src = fetchFromGitHub ({
      owner = "Half-Shot";
      repo = "matrix-appservice-discord";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-hZQ+3FDRWNGsnaHblnB2p6Inf9ZMrbB2jmgR2rskil0=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "104.0.1293.25";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_104.0.1293.25-1_amd64.deb";
      sha256 = "sha256-MmJp38SEHxzFKL1VkGq6EJ9iWemAZ8hJwecDhTxJxoc=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "105.0.1321.0";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_105.0.1321.0-1_amd64.deb";
      sha256 = "sha256-NHSTUWYZiNvDzMLp8lbh/66hdBWXFwgyqsQyzEqtt8M=";
    };
  };
  microsoft-edge-stable = {
    pname = "microsoft-edge-stable";
    version = "103.0.1264.62";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_103.0.1264.62-1_amd64.deb";
      sha256 = "sha256-ZAps8/YvvYu1NmRAnwMTvlmj1id6KyeJW5RQuiF/yMA=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "086b2457e8b769d6af44917759403f76b8b3b90e";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "086b2457e8b769d6af44917759403f76b8b3b90e";
      fetchSubmodules = false;
      sha256 = "sha256-WvDS1z33/j8uXMNFGqZ8D0kRnCqhKzgtXdMVOoo9vxg=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.35.1";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.35.1.tar.gz";
      sha256 = "sha256-yR1ew5VDQz7elr7hJRxI/iF0xupM4tD8+eOSJd9GoVM=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.33.1";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.33.1.tar.gz";
      sha256 = "sha256-1fMvCX+nh8RCZoAqIU/9wTEZw2PzN4BTggug/ejjdjA=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "97987692deb6ab09816f40972fe5b04c1ddebd7e";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "97987692deb6ab09816f40972fe5b04c1ddebd7e";
      fetchSubmodules = false;
      sha256 = "sha256-zeQ+ValEtCZjvC9S8hADzigqdzikiXeEEOCUAaXtLXI=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "583ddfde0bd3ebc93e03f047d6419f696826803e";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "583ddfde0bd3ebc93e03f047d6419f696826803e";
      fetchSubmodules = false;
      sha256 = "sha256-eC9wLJvd3iXd2oeY+0lShnEfKYkgi4QT4D7fSG6NzE8=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-Rr0UpJa7kemczCqNn6b8HNtW6PiWO/Ez1LUh/WNk8S8=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "f6a4c9ffbe4f5761202a1678720323c72adfed2b";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "f6a4c9ffbe4f5761202a1678720323c72adfed2b";
      fetchSubmodules = false;
      sha256 = "sha256-nrVeuEERRxTk/ATCd0x371RVFxY9BxbHFOHMDO+bpzI=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./ouch-f6a4c9ffbe4f5761202a1678720323c72adfed2b/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "896acabab11e977a5a07e2a59d9b35bfeb167263";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "896acabab11e977a5a07e2a59d9b35bfeb167263";
      fetchSubmodules = false;
      sha256 = "sha256-QaEuewhAbaBW+rYt0eFwV1hD466ydI6ihGWasFICurI=";
    });
  };
  playit-agent = {
    pname = "playit-agent";
    version = "18e692e513437c792c4b56977b72db33342a22c4";
    src = fetchFromGitHub ({
      owner = "playit-cloud";
      repo = "playit-agent";
      rev = "18e692e513437c792c4b56977b72db33342a22c4";
      fetchSubmodules = false;
      sha256 = "sha256-/7zWL3LNoT99T9o9Ozr07zoFnpjnnXBWJseUUmAx3zw=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./playit-agent-18e692e513437c792c4b56977b72db33342a22c4/Cargo.lock;
      outputHashes = {
        "webbrowser-0.5.5" = "sha256-9LhheWDmQKUdKLsYo5Uo+Z3PlKeMMnZvfWyXOMvEf7M=";
      };
    };
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.45.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.45.0.tar.gz";
      sha256 = "sha256-75ZFzhRsczkwhiUl1upKjSvmqN0RkXaM8cKr4zLgi4w=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "bd4a7d5d3f2c6fcdc7d42abeee1fd69d505db835";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "bd4a7d5d3f2c6fcdc7d42abeee1fd69d505db835";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2ZOLTzv8/33LoEAdosrOa8rfGolyuP2RUAmtPnaI2T4=";
    };
  };
  polymc-cracked = {
    pname = "polymc-cracked";
    version = "6000f5de6742bf825ed56477b16be559f5cfe227";
    src = fetchFromGitHub ({
      owner = "thecountrox";
      repo = "PolyMC-Cracked";
      rev = "6000f5de6742bf825ed56477b16be559f5cfe227";
      fetchSubmodules = false;
      sha256 = "sha256-7N/H+mpYl/v522b+D3HI8zw9oLqj2yFJ0WGVDzLQC4w=";
    });
  };
  pure = {
    pname = "pure";
    version = "3b2606db2e7eb6f05c67b229b5e3c68a1c3947a6";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "3b2606db2e7eb6f05c67b229b5e3c68a1c3947a6";
      fetchSubmodules = false;
      sha256 = "sha256-shiBRF2DeLVWFcla6DuATtmc4vc+xoChzOS70Rd8NAM=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "2856b096c3136eed67da47ab47a69ce0b0586ae9";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "2856b096c3136eed67da47ab47a69ce0b0586ae9";
      fetchSubmodules = false;
      sha256 = "sha256-RTXJtP0cwZmfFpzH62FzOm3Wvh9aFSz9xyS2IYzLQ9w=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "231a8434a3c1aedd64dd8ca4cf2e67318440c9ff";
      fetchSubmodules = false;
      sha256 = "sha256-muDz1rFTvWOZGrEzql+VZbs42bS09BREjKS5OpBu2g8=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "3cf7e881ec1c02298ffe1c70e843f235f024d980";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "3cf7e881ec1c02298ffe1c70e843f235f024d980";
      fetchSubmodules = false;
      sha256 = "sha256-xQj+7mXvbF9A0mxgToxRNHhUHlxOyMQuT9KudYqpINo=";
    });
  };
  revanced-cli = {
    pname = "revanced-cli";
    version = "2.6.0";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-cli/releases/download/v2.6.0/revanced-cli-2.6.0-all.jar";
      sha256 = "sha256-HuYo5AqvXDgwev6HII+DbUsLJtFi5v5HeupcDI17fNA=";
    };
  };
  revanced-integrations = {
    pname = "revanced-integrations";
    version = "0.27.4";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-integrations/releases/download/v0.27.4/app-release-unsigned.apk";
      sha256 = "sha256-5K86OYAi9Aw0bB7lExCpvyoQNe/yRrDJ4f9Rj6TgWKY=";
    };
  };
  revanced-patches-dex = {
    pname = "revanced-patches-dex";
    version = "2.20.4";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-patches/releases/download/v2.20.4/revanced-patches-2.20.4.dex";
      sha256 = "sha256-FG+MaYmlIWlei9FYL4SjHbDXmrrWZ2ewfCB4Mu4pyG0=";
    };
  };
  revanced-patches-jar = {
    pname = "revanced-patches-jar";
    version = "2.20.4";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-patches/releases/download/v2.20.4/revanced-patches-2.20.4.jar";
      sha256 = "sha256-plboFtBNkaNw7heEaBzxeosEU4duuxFYL4vIiyXv3ZY=";
    };
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "6801bd85bbfa59143b8ec443a05b22ef977b4349";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "6801bd85bbfa59143b8ec443a05b22ef977b4349";
      fetchSubmodules = true;
      sha256 = "sha256-3kPzEkljNXOf+4HSCrjXm6BUxusDT9NP2wbxqBRvLRk=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "d65c486b278d8aeb09be99ccce5a69ad846e737e";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "d65c486b278d8aeb09be99ccce5a69ad846e737e";
      fetchSubmodules = false;
      sha256 = "sha256-n/loSTwCTVNdo+zsmZK4w+gXOp9/xXxG7WWdDuDjFvA=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./rustdesk-d65c486b278d8aeb09be99ccce5a69ad846e737e/Cargo.lock;
      outputHashes = {
        "trayicon-0.1.3-1" = "sha256-shLsOncL3ySRN/m9SjvjurneMaXhGDWks0QF3pVz6J0=";
        "rust-pulsectl-0.2.12" = "sha256-8jXTspWvjONFcvw9/Z8C43g4BuGZ3rsG32tvLMQbtbM=";
        "confy-0.4.0" = "sha256-e91cvEixhpPzIthAxzTa3fDY6eCsHUy/eZQAqs7QTDo=";
        "parity-tokio-ipc-0.7.3-1" = "sha256-eULJePtBu0iBI3It/bPH0h82Obsb1PJALgwYwrnCFYI=";
        "tokio-socks-0.5.1-1" = "sha256-45QQ6FrhGU9uEhbKXTKd/mY6MDumO6p46NmlakdyDQk=";
        "hwcodec-0.1.0" = "sha256-RRiEfz0cO8d50ADwn4PfLlQSAssqyNnL6K7yADkrzcM=";
        "mouce-0.2.1" = "sha256-YcS7rn3eWmFWIq3X6ytwPRp3eWuXjJwseqsMoA6k7/w=";
        "sciter-rs-0.5.57" = "sha256-ZZnZDhMjK0LjgmK0da1yvB0uoKueLhhhQtzmjoN+1R0=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
        "evdev-0.11.5" = "sha256-aoPmjGi/PftnH6ClEWXHvIj0X3oh15ZC1q7wPC1XPr0=";
        "rdev-0.5.0-1" = "sha256-aaC2Aq6xBSKV7+eUZWKLSmDBFwNcHWkgw1jJWQXvNqA=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "2e539cf5bfc60b1463519de2566422464877992d";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "2e539cf5bfc60b1463519de2566422464877992d";
      fetchSubmodules = false;
      sha256 = "sha256-MMPmTEMYghf2A+rQF5pJaLTb2NyXpV3HKx20g7o/deg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "e67307e4103a8606d57a0c2fd48a378e40fcef06";
      fetchSubmodules = false;
      sha256 = "sha256-FfbYQrHndU7rtI8CKK7wtn3pdufBSiXUgefozCja4Do=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-SIht9sqmeijEeU4uLwm+tlZtFlTnD/G5GH8haUL6dlU=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-g/SzgU3vOzm8uRuA6AN/N8Tnrl2Vpya58hx99dGfecI=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-jnhTTmSy5J8MJotbsI8g5hxotgjvyDbccymjABwajYw=";
    };
  };
  snui = {
    pname = "snui";
    version = "677e824521f8fecb592ad4159b7e66031eeccf20";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "677e824521f8fecb592ad4159b7e66031eeccf20";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-hAMRr0Jedh1F4GEFOXu4tNTCO8iAt2hUwgTnP5AfLok=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "ba5cef8fd63d2735b55243796896cf71915c8945";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "ba5cef8fd63d2735b55243796896cf71915c8945";
      fetchSubmodules = false;
      sha256 = "sha256-lGLe9T6cN600OA8nSklRDpgWLgIvqSHuZ/JLstqqCio=";
    });
  };
  spicetify-marketplace = {
    pname = "spicetify-marketplace";
    version = "86097e1ac1de1fad8ca6669d993ac150ea44d954";
    src = fetchFromGitHub ({
      owner = "spicetify";
      repo = "spicetify-marketplace";
      rev = "86097e1ac1de1fad8ca6669d993ac150ea44d954";
      fetchSubmodules = false;
      sha256 = "sha256-W3DNhIrcLEyiHGRWYPWIr2e78HBA4cynld5/X0+Ow/s=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "86f72355ffefe7461ca28edf7f9491b404a7d0d3";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "86f72355ffefe7461ca28edf7f9491b404a7d0d3";
      fetchSubmodules = false;
      sha256 = "sha256-NBqTfB0IA4ziphEZ+b1CSOf26p+AALWrvrKgWXhv2q0=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.84.716.gc5f8b819";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_60.snap";
      sha256 = "sha256-ho3WjGNjmHsERzC3FLgliuVSQWK2F5ec0ddQSfq6oyI=";
    };
  };
  spotify-1_1_83_954_gd226dfe8 = {
    pname = "spotify-1_1_83_954_gd226dfe8";
    version = "1.1.83.954.gd226dfe8";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_59.snap";
      sha256 = "sha256-IAktrSHXcoO6MxId4mJphMknOik0NG67Imwy4pLFCk8=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "993336f74ec89cb6cad23dd009251e70548761b6";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "993336f74ec89cb6cad23dd009251e70548761b6";
      fetchSubmodules = false;
      sha256 = "sha256-IILJCvH+dyKRRUERW9zicsoRoCBiKw03MTnitZb2hp0=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./spotifyd-993336f74ec89cb6cad23dd009251e70548761b6/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "9a30319162be76df69e77787ed3a3ae63144ea04";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "9a30319162be76df69e77787ed3a3ae63144ea04";
      fetchSubmodules = false;
      sha256 = "sha256-pSB1zJji0aceunueU1shrXhRjKv55kVrVcnQUJeUITM=";
    });
  };
  supergfxctl = {
    pname = "supergfxctl";
    version = "46f808da96802b6cc27e1b195bb500889fcf3a49";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl";
      rev = "46f808da96802b6cc27e1b195bb500889fcf3a49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FTDJpmWsgF9CGfnVLYu7UosluQa/I5/omhOil8oEW64=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./supergfxctl-46f808da96802b6cc27e1b195bb500889fcf3a49/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  sway-borders = {
    pname = "sway-borders";
    version = "3890d2a2fb255276993891e2da5f6cb33670efcd";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "3890d2a2fb255276993891e2da5f6cb33670efcd";
      fetchSubmodules = false;
      sha256 = "sha256-esMruivwq6XPPYJWaW825+d8rD8NOxbJQqVfAeBtXe0=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  swhkd = {
    pname = "swhkd";
    version = "19db3259a5f24e3c4395bbfeb3cfad8709d14f18";
    src = fetchFromGitHub ({
      owner = "waycrate";
      repo = "swhkd";
      rev = "19db3259a5f24e3c4395bbfeb3cfad8709d14f18";
      fetchSubmodules = false;
      sha256 = "sha256-VuzdAfu1eN6AsFGFuI95i7KdiqBylVE4b2IVylSTn7w=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./swhkd-19db3259a5f24e3c4395bbfeb3cfad8709d14f18/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  tailscale = {
    pname = "tailscale";
    version = "d8cb5aae1720c3edc5e30f77b5fc7634e940a252";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "d8cb5aae1720c3edc5e30f77b5fc7634e940a252";
      fetchSubmodules = false;
      sha256 = "sha256-/jqbvepvA6NkteBMvrZVvntVHdSP9/y0odMLR2/Cruo=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "8e943debe7801a79c0e146cf9f53f0b9aa9d5e72";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "8e943debe7801a79c0e146cf9f53f0b9aa9d5e72";
      fetchSubmodules = false;
      sha256 = "sha256-iIKth2qPc8S5h0ebasoiIGiEEy+mip8Ris1HWW/p6Ko=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.5.00.10453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.10453_amd64.deb";
      sha256 = "sha256-fLVw2axSMetuaoRzjg+x4DRYY8WP5TQbL7LbfF6LFfA=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "022524d4cabae6278b9b35b05b2e4ffca84ef9d3";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-x8D5XrvMjNV2R5CXs/ficOhwXNTRglsQxPhfvuUF4nM=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "ecb038a10a80259e51dbc6d500233a57c37a68f5";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "ecb038a10a80259e51dbc6d500233a57c37a68f5";
      fetchSubmodules = false;
      sha256 = "sha256-EMHrKcyb1qfV9MlUtICnedlA6feOh7n0Vmrp9aVwRO4=";
    });
  };
  ultimmc = {
    pname = "ultimmc";
    version = "66bb7105db93e0977bb64a59a12b001f780e0566";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "66bb7105db93e0977bb64a59a12b001f780e0566";
      fetchSubmodules = true;
      sha256 = "sha256-t/R3BBRy2orzUuh537xMPwORHmhQy4aGe96e77CVzZs=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.25.1";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.25.1";
      fetchSubmodules = false;
      sha256 = "sha256-oX1P0YsBhjk/0xcG4RbZ5aFfbJcYEVhV9jSQ1270N9M=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./vaultwarden-1.25.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2022.6.2";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2022.6.2/bw_web_v2022.6.2.tar.gz";
      sha256 = "sha256-IG/eCBTUa7eKeaelqxCWO+rrXJUuBanhsYwklftxdOE=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  waydroid = {
    pname = "waydroid";
    version = "28453601379e7561c0a798b2e3d178a53d3fc346";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "28453601379e7561c0a798b2e3d178a53d3fc346";
      fetchSubmodules = false;
      sha256 = "sha256-UNhDQBt2oeuH0OjlPUXqHMfxJoaySdRDMgag2oqIcSA=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "140f9832314247e5a122ca252d139449255ad7c3";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "140f9832314247e5a122ca252d139449255ad7c3";
      fetchSubmodules = false;
      sha256 = "sha256-tUEeczs3J//2ZrZkAsSn3C+GScRPaIgheRM2wByS8p4=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "c3e0a5187fe41e84fd953233633e60c38e2e65c9";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "c3e0a5187fe41e84fd953233633e60c38e2e65c9";
      fetchSubmodules = false;
      sha256 = "sha256-BzrbM65LL6sxWKFrLNeBryNGQuZjrcDYAGnHDxYNeiY=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "1ea3e6dbf5f097d2178568b3a4041fe2fa102bbd";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "1ea3e6dbf5f097d2178568b3a4041fe2fa102bbd";
      fetchSubmodules = false;
      sha256 = "sha256-GKvYZxV02uKykUC7wZkM3QHiv1YQbK0Q+3o8w+90Wv4=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2449.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2449.0-linux-x64.zip";
      sha256 = "sha256-vsr6eymKqU2Y6HM4DPHnUfVkB2BQ1HSSWvk1tNhUA5Y=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xdg-desktop-portal = {
    pname = "xdg-desktop-portal";
    version = "750b9e5d6d7cdf451bb4f9f4fc97682fafa1a364";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal";
      rev = "750b9e5d6d7cdf451bb4f9f4fc97682fafa1a364";
      fetchSubmodules = false;
      sha256 = "sha256-Qz99CfwuyXex+dCwLIBlbQRJcrsxiMrzN4gqXlZU5vM=";
    });
  };
  xdg-desktop-portal-gtk = {
    pname = "xdg-desktop-portal-gtk";
    version = "93e50a2cf6a4b8b1a6ba30fbb2215bc497347a70";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal-gtk";
      rev = "93e50a2cf6a4b8b1a6ba30fbb2215bc497347a70";
      fetchSubmodules = false;
      sha256 = "sha256-F7PYlOPP8KoZuYU3KvHvGAbr5vvXv8ww8hNypwp/zRU=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "d9ca87eea9eecddaccc3a77227bcb3acf84e89df";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "d9ca87eea9eecddaccc3a77227bcb3acf84e89df";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-r72BE+WCZngaMutOxidnJyQ1IpXPFH5NXBs/7l5agD4=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "912e050d8df0fc3d034c8b03d8afe37b9ce15402";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "912e050d8df0fc3d034c8b03d8afe37b9ce15402";
      fetchSubmodules = false;
      sha256 = "sha256-vlmrIM9iloxXJFefN1ErsML6AeRWLc/pW9TvFcR3O2w=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "6907b6ea2b4ce949cb07271f5b678d5966d9df42";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "6907b6ea2b4ce949cb07271f5b678d5966d9df42";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AmW4hpFHkSVUc4P+0Y82Xig3GprVpicpdRGS7OL25VE=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "81195bfde8f9b5218e6e87bbd6f6e362a7653aad";
      fetchSubmodules = false;
      sha256 = "sha256-maXXGCqB8dkGO8956hsKSwM4HQdYn6z1jBFENQ9sKcA=";
    });
  };
  yubikey-agent = {
    pname = "yubikey-agent";
    version = "6d9db9c29100daacbe83e74653c79c94acc5958d";
    src = fetchFromGitHub ({
      owner = "FiloSottile";
      repo = "yubikey-agent";
      rev = "6d9db9c29100daacbe83e74653c79c94acc5958d";
      fetchSubmodules = false;
      sha256 = "sha256-mrdZcKD61S94ZkVH93SJhozmsXW/22ho08WMCrDEwhs=";
    });
  };
  yubikey-guide = {
    pname = "yubikey-guide";
    version = "dc29279197bbf866b63976395d2c69b1a95ad088";
    src = fetchFromGitHub ({
      owner = "drduh";
      repo = "YubiKey-Guide";
      rev = "dc29279197bbf866b63976395d2c69b1a95ad088";
      fetchSubmodules = false;
      sha256 = "sha256-MMcfiJ31SsrJdPCYn+5MuUxqLJzhY4VeqOS02T9AlL8=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.11.3.3882";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.11.3.3882/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-AKW3jQaew3VrMkyfMSEjR86BT6kE3Qe/2Giy7EChoCc=";
    };
  };
}
