# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  B4dM4n-nixpkgs-fmt = {
    pname = "B4dM4n-nixpkgs-fmt";
    version = "0.0.1";
    src = fetchurl {
      url = "https://B4dM4n.gallery.vsassets.io/_apis/public/gallery/publisher/B4dM4n/extension/nixpkgs-fmt/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nixpkgs-fmt-0.0.1.zip";
      sha256 = "sha256-vz2kU36B1xkLci2QwLpl/SBEhfSWltIDJ1r7SorHcr8=";
    };
    license = "MIT";
    name = "nixpkgs-fmt";
    publisher = "B4dM4n";
  };
  RoscoP-ActiveFileInStatusBar = {
    pname = "RoscoP-ActiveFileInStatusBar";
    version = "1.0.3";
    src = fetchurl {
      url = "https://RoscoP.gallery.vsassets.io/_apis/public/gallery/publisher/RoscoP/extension/ActiveFileInStatusBar/1.0.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ActiveFileInStatusBar-1.0.3.zip";
      sha256 = "sha256-5GJODdKL8949a8KR2O7hGsRgAknfPyNEJ+9aiEYYemk=";
    };
    license = "MIT";
    name = "ActiveFileInStatusBar";
    publisher = "RoscoP";
  };
  alefragnani-pascal = {
    pname = "alefragnani-pascal";
    version = "9.5.1";
    src = fetchurl {
      url = "https://alefragnani.gallery.vsassets.io/_apis/public/gallery/publisher/alefragnani/extension/pascal/9.5.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pascal-9.5.1.zip";
      sha256 = "sha256-q2Fx7pc66tlREhcDUcIXUWDLW76gwbVBv+NzHOkndjU=";
    };
    license = "MIT";
    name = "pascal";
    publisher = "alefragnani";
  };
  alefragnani-pascal-formatter = {
    pname = "alefragnani-pascal-formatter";
    version = "2.6.1";
    src = fetchurl {
      url = "https://alefragnani.gallery.vsassets.io/_apis/public/gallery/publisher/alefragnani/extension/pascal-formatter/2.6.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pascal-formatter-2.6.1.zip";
      sha256 = "sha256-nUtHkHdHB+DTVfqbhkqTj9ElaR7ip73PpUw5f+nl8dM=";
    };
    license = "MIT";
    name = "pascal-formatter";
    publisher = "alefragnani";
  };
  astro-build-astro-vscode = {
    pname = "astro-build-astro-vscode";
    version = "0.20.3";
    src = fetchurl {
      url = "https://astro-build.gallery.vsassets.io/_apis/public/gallery/publisher/astro-build/extension/astro-vscode/0.20.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "astro-vscode-0.20.3.zip";
      sha256 = "sha256-NJQEW5aJUHQWFwCEYTO99OUG5Lc9sZet/k+YznE226s=";
    };
    license = "MIT";
    name = "astro-vscode";
    publisher = "astro-build";
  };
  dzhavat-css-initial-value = {
    pname = "dzhavat-css-initial-value";
    version = "0.2.6";
    src = fetchurl {
      url = "https://dzhavat.gallery.vsassets.io/_apis/public/gallery/publisher/dzhavat/extension/css-initial-value/0.2.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "css-initial-value-0.2.6.zip";
      sha256 = "sha256-QLzjkPWPFCVJ0GrT8rtx8/V2JsdJ1zMdTmARtaqEcJQ=";
    };
    license = "MIT";
    name = "css-initial-value";
    publisher = "dzhavat";
  };
  heybourn-headwind = {
    pname = "heybourn-headwind";
    version = "1.7.0";
    src = fetchurl {
      url = "https://heybourn.gallery.vsassets.io/_apis/public/gallery/publisher/heybourn/extension/headwind/1.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "headwind-1.7.0.zip";
      sha256 = "sha256-yXsZoSuJQTdbHLjEERXX2zVheqNYmcPXs97/uQYa7og=";
    };
    license = "MIT";
    name = "headwind";
    homepage = "https://github.com/heybourn/headwind";
    description = "An opinionated Tailwind CSS class sorter built for Visual Studio Code";
    publisher = "heybourn";
  };
  ms-vscode-cpptools = {
    pname = "ms-vscode-cpptools";
    version = "1.12.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools/1.12.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cpptools-1.12.0.zip";
      sha256 = "sha256-G0ZvVMchubAp6u5MXtJb7HLLyP4EfBtiJGIkzxDvqww=";
    };
    license = "MIT";
    name = "cpptools";
    publisher = "ms-vscode";
  };
  msjsdiag-react-native = {
    pname = "msjsdiag-react-native";
    version = "1.9.2";
    src = fetchurl {
      url = "https://msjsdiag.gallery.vsassets.io/_apis/public/gallery/publisher/msjsdiag/extension/vscode-react-native/1.9.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-react-native-1.9.2.zip";
      sha256 = "sha256-F6E7fx9FR6stcpe4Hca6hkhV7FUsTi/mozKRhGL+SgY=";
    };
    license = "MIT";
    name = "vscode-react-native";
    publisher = "msjsdiag";
  };
}
