# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.107.0-b.14";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0-b.14/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-VC6aNYOZSFntDuO+FCSHdcFpS7fGYcqOJ8hVerOT0eg=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.107.0-b.14";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0-b.14/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-+uFP20t9AW2yXDErg9+T890kn0sa2JAq8H5RXedBiLo=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.107.0-b.14";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0-b.14/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-h1n1avhQ5BOu9/X9fkbP8BvnzjUBwI/mCphX8USnq5I=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.107.0-b.14";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0-b.14/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-7eUmzrk6boDe4xbHkc8e0KhFRca/OO5vxK8mjfKh8bI=";
    };
  };
  adl = {
    pname = "adl";
    version = "bad3cb6d17ed70f814747c1b6ae8ac307c46992b";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "bad3cb6d17ed70f814747c1b6ae8ac307c46992b";
      fetchSubmodules = false;
      sha256 = "sha256-0WusE9WGxlfXjT1A41nQIM9Q7T3rk2JIieCksR7CsRg=";
    });
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "669f32d41589a234e2e870d6ce505b004a40fedb";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "669f32d41589a234e2e870d6ce505b004a40fedb";
      fetchSubmodules = false;
      sha256 = "sha256-u1vaRnBD94iJIQlqfqTEsAUe+WzI4LB1w9SoY4H+oNE=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
      fetchSubmodules = false;
      sha256 = "sha256-E6Q7nVPuoC81aGMYOFkmlRv1i6eoOtbYw2AeCCXMR2A=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "f8932dced142ec5ea633bfb163bfc7579ac38a07";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "f8932dced142ec5ea633bfb163bfc7579ac38a07";
      fetchSubmodules = false;
      sha256 = "sha256-CtfcxuQCUtkUVyR7EgXXsZxlIQTOl0pScMvLBu4VhK4=";
    });
  };
  avizo = {
    pname = "avizo";
    version = "7b3874e5ee25c80800b3c61c8ea30612aaa6e8d1";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "7b3874e5ee25c80800b3c61c8ea30612aaa6e8d1";
      fetchSubmodules = false;
      sha256 = "sha256-ixAdiAH22Nh19uK5GoAXtAZJeAfCGSWTcGbrvCczWYc=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "2eb035e1257c05aaaea33540e3db8dea504c2d13";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "2eb035e1257c05aaaea33540e3db8dea504c2d13";
      fetchSubmodules = false;
      sha256 = "sha256-42N4RrVRNV2hBnlMpr7uDwf3RogbwL34gxjX4+JcYYI=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  bling = {
    pname = "bling";
    version = "92dabc890e15397d823983b688f5beb7aae8d4c2";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "92dabc890e15397d823983b688f5beb7aae8d4c2";
      fetchSubmodules = false;
      sha256 = "sha256-5OKGiA0D5D019xmO6CQzNk66WOZ11sDbf5pW0XrpwHs=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "b75a5755fd2bd5169c7d40ca618e517d66a1fc1d";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "b75a5755fd2bd5169c7d40ca618e517d66a1fc1d";
      fetchSubmodules = false;
      sha256 = "sha256-LoIN3ZtvYOoSrivZmvR5ELqnHJNMO0uQqa11iz+MH5E=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "24fda7514ddeebf19a1e872343b45ec523eefcba";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "24fda7514ddeebf19a1e872343b45ec523eefcba";
      fetchSubmodules = false;
      sha256 = "sha256-kXKcdNbdKhpyS+k8C/qKrW53myN9ONq8yeakcAVc0Y0=";
    });
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.131";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.131/discord-canary-0.0.131.tar.gz";
      sha256 = "sha256-ZYPdE02Jq79LmvXu7KIJFugJX++Nnj0Og/mBuaP/+SA=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "9e7221c31cab868b4908d5ff035bf51f906ba424";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "9e7221c31cab868b4908d5ff035bf51f906ba424";
      fetchSubmodules = false;
      sha256 = "sha256-eFXzwiScers1Qc9/MYHzc5om1RPtwQZMAksFUjhdZZs=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "3d7b4a9821af17137e01ca7969d6531c6a67ebf2";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "3d7b4a9821af17137e01ca7969d6531c6a67ebf2";
      fetchSubmodules = false;
      sha256 = "sha256-TG1pWLf/aB/5clzBYdbZcGZb+64oV9olT5xezUWay/M=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "c5a1dd3f16916db5d632f9b3ad5aec1091f4ab2a";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "c5a1dd3f16916db5d632f9b3ad5aec1091f4ab2a";
      fetchSubmodules = false;
      sha256 = "sha256-X6IcHlXh/m2xBBt0jr1tpAr3uYjJWwpFl+RGl1BuMz4=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "b527a730a47c45bc9cbad0fd34896299f8730cc9";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "b527a730a47c45bc9cbad0fd34896299f8730cc9";
      fetchSubmodules = false;
      sha256 = "sha256-h88hIhdCyjC5vlJU4ohDmBVY2VEZQZGO5/x/bklidy4=";
    });
  };
  duf = {
    pname = "duf";
    version = "673a3d13841abf5bab5fc2d42ff4a07ef4b8bef8";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "673a3d13841abf5bab5fc2d42ff4a07ef4b8bef8";
      fetchSubmodules = false;
      sha256 = "sha256-sbZUyCO5zTi3AvDhuUb13LP4YA7LkyBBU8ulvO1LsqI=";
    });
  };
  eww = {
    pname = "eww";
    version = "df29780d2ae33784a21e0f955a70868d7764d820";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "df29780d2ae33784a21e0f955a70868d7764d820";
      fetchSubmodules = false;
      sha256 = "sha256-oJPOuXwhuKArEC3dmCU9jNZldGOhf6PZr44RekQl6TU=";
    });
    cargoLock = {
      lockFile = ./eww-df29780d2ae33784a21e0f955a70868d7764d820/Cargo.lock;
      outputHashes = { };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "80f04cf8762e31fad55a90bc5559c07f6e94c6b2";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "80f04cf8762e31fad55a90bc5559c07f6e94c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-Uwttm0JksP1ZT6SWA6oTBsqKh4gjcPrvSN3E9yfvSYU=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "445a4c68e81e876dbec78e53deaef4b5c3bac291";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "445a4c68e81e876dbec78e53deaef4b5c3bac291";
      fetchSubmodules = false;
      sha256 = "sha256-SycWS5KOyjZ8kNuE/Gobio2rgeqNiXiE6/Hm3jdCyn8=";
    });
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = { };
    };
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "6dedbf9b6e5079e49c167bf2ca11f58bdf1e67cb";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "6dedbf9b6e5079e49c167bf2ca11f58bdf1e67cb";
      fetchSubmodules = false;
      sha256 = "sha256-eEz7pgLGZNrRUBcEQf8vs067WR54oFSMrZwG6PtA6bk=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "28acfd433b3df1673b7c7177915c027ce48c061e";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "28acfd433b3df1673b7c7177915c027ce48c061e";
      fetchSubmodules = false;
      sha256 = "sha256-S5j+ymWxTTqv1v2W2wBavM5aausX+T20/XjF89JuVFo=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "f6406437969b8e40c5e529cad0055d894fad2c7a";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "f6406437969b8e40c5e529cad0055d894fad2c7a";
      fetchSubmodules = false;
      sha256 = "sha256-w68I1a1mMEGgF4oCzs5TvYmXTdpQPJog/S42Dz519i4=";
    });
  };
  layout-machi = {
    pname = "layout-machi";
    version = "df15a7b78e929203f4de46348b25f3630ac079c1";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "df15a7b78e929203f4de46348b25f3630ac079c1";
      fetchSubmodules = false;
      sha256 = "sha256-DHQdWkQTztO/YBh6F2LzfbfK2bHpklhXnAkuw3fAZWM=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
      fetchSubmodules = false;
      sha256 = "sha256-d8iBxfHkryy5lM5myWPo0a3zgUZQrklYazCSCyKKDGs=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "96.0.1054.13";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_96.0.1054.13-1_amd64.deb";
      sha256 = "sha256-GoMVncusfFfpJkeAEl/PkDYtxYBOL/GP603lSwQDCM0=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "97.0.1060.2";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_97.0.1060.2-1_amd64.deb";
      sha256 = "sha256-my/AO53G/qbrkc1rH2JmBGUVZkWYcJSKQN6c65ljBnk=";
    };
  };
  minecraft-better-beds = {
    pname = "minecraft-better-beds";
    version = "1.2.0";
    src = fetchurl {
      url = "https://github.com/TeamMidnightDust/BetterBeds/releases/download/v1.2.0/betterbeds-1.2.0.jar";
      sha256 = "sha256-ePkc4oTD0SGFD7qnzKSgHrW9fPoDMpni8euR8aowPA8=";
    };
  };
  minecraft-cull-leaves = {
    pname = "minecraft-cull-leaves";
    version = "2.3.2";
    src = fetchurl {
      url = "https://github.com/TeamMidnightDust/CullLeaves/releases/download/v2.3.2/cullleaves-2.3.2.jar";
      sha256 = "sha256-tNi43VJa/tLpKcsSEhIjYim6pYopTlBRCy3zdtNC6xQ=";
    };
  };
  minecraft-fabric-api = {
    pname = "minecraft-fabric-api";
    version = "0.42.1+1.17";
    src = fetchurl {
      url = "https://github.com/FabricMC/fabric/releases/download/0.42.1+1.17/fabric-api-0.42.1+1.17.jar";
      sha256 = "sha256-nmSO3RtLhCJGzYi/dF+JukMm1tHRv9bGWjFJ+2NbYJE=";
    };
  };
  minecraft-fast-furnace = {
    pname = "minecraft-fast-furnace";
    version = "3.0";
    src = fetchurl {
      url = "https://nightly.link/danielphan2003/FabricFastFurnace/workflows/gradle/patch-2/build-artifacts.zip";
      sha256 = "sha256-MEUxqfDBrTb+gLQp0c9Sgt5ECtN1jHAvar48NZ+Hmpo=";
    };
  };
  minecraft-ferrite-core = {
    pname = "minecraft-ferrite-core";
    version = "3.1.0";
    src = fetchurl {
      url = "https://nightly.link/malte0811/FerriteCore/workflows/build.yaml/1.17/build-artifacts.zip";
      sha256 = "sha256-k60O+BdOIo8+9HhijckGxmG9mRR/eWJlu1lHIHbClA8=";
    };
  };
  minecraft-krypton = {
    pname = "minecraft-krypton";
    version = "0.1.4";
    src = fetchurl {
      url = "https://github.com/astei/krypton/releases/download/v0.1.4/krypton-0.1.4.jar";
      sha256 = "sha256-7FLzkVjDteRAAc+sNHaVLE5AH+jUdJYcrm9EFBwWcLY=";
    };
  };
  minecraft-lazydfu = {
    pname = "minecraft-lazydfu";
    version = "0.1.2";
    src = fetchurl {
      url = "https://github.com/astei/lazydfu/releases/download/0.1.2/lazydfu-0.1.2.jar";
      sha256 = "sha256-546xSS4gvNjJmNQULdQ3wlFzk8XQL1giBK2KODQedeg=";
    };
  };
  minecraft-lithium = {
    pname = "minecraft-lithium";
    version = "0.7.5";
    src = fetchurl {
      url = "https://github.com/CaffeineMC/lithium-fabric/releases/download/mc1.17.1-0.7.5/lithium-fabric-mc1.17.1-0.7.5.jar";
      sha256 = "sha256-HADtQ51u6ZBqHS3q9wZeOYAz96E2vFPSmL4sxjYoMhA=";
    };
  };
  minecraft-sodium = {
    pname = "minecraft-sodium";
    version = "0.3.2";
    src = fetchurl {
      url = "https://nightly.link/CaffeineMC/sodium-fabric/workflows/gradle/1.17.x%2Fdev/sodium-artifacts-1.17.x-dev.zip";
      sha256 = "sha256-7nuKV4E8LFghAdp5sc04+XZlrDp+PL3c7o9BlAqaBhc=";
    };
  };
  minecraft-starlight = {
    pname = "minecraft-starlight";
    version = "1.0.0-RC3";
    src = fetchurl {
      url = "https://github.com/PaperMC/Starlight/releases/download/1.0.0-RC3/starlight-1.0.0-RC3+fabric.1.17.x.jar";
      sha256 = "sha256-15vxBPDcq1PT1VRjELJRNB1oO722ycRfj8NKF3cs5AY=";
    };
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "5a49fbd9411782b21537b4ecef7e8136749bbdd4";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "5a49fbd9411782b21537b4ecef7e8136749bbdd4";
      fetchSubmodules = false;
      sha256 = "sha256-vc/WLSrx4PEZJGtwIjaMveaQ06CU47hDjiWEBIRrs9I=";
    });
  };
  multimc-cracked = {
    pname = "multimc-cracked";
    version = "ac69560153a0d0c4b036466a452b7b0c07f34ac0";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "ac69560153a0d0c4b036466a452b7b0c07f34ac0";
      fetchSubmodules = true;
      sha256 = "sha256-C0z7aY4Db1dlT/Vm4zduLHVsb2mbaUFiPjdMXlGTkXw=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.31.0";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.31.0.tar.gz";
      sha256 = "sha256-4IjEtm4b4qttyKWbI3Yie++hlaESpIOJGRbsDwWA7UA=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.30.0";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.30.0.tar.gz";
      sha256 = "sha256-Q4nzM7B+YaHC7nv9YFpaORKZ1+gE+bdHxBvByPqURCs=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
      fetchSubmodules = false;
      sha256 = "sha256-ZJmnUU81hg34JHkA82BfapFGqKrhqFk6wCM2eO2RaVs=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "2e305e6e5222954ff43e6f48ec8bc29161aaefd0";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "2e305e6e5222954ff43e6f48ec8bc29161aaefd0";
      fetchSubmodules = false;
      sha256 = "sha256-i16DJD7rktgfHQpnxVfwNVK6efa/Y6D9PJb8E7fstA8=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-qW/yCo4UPxz/MT7AXtK40pCjuf9gEKsGIZMldMn3lAI=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "abf1d4e3e40e9064c7a184883fb3478c440c6c08";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "abf1d4e3e40e9064c7a184883fb3478c440c6c08";
      fetchSubmodules = false;
      sha256 = "sha256-OTqOZTL4DxphhNNAdTj+QNHonMBylSn3YDzpX2QsLhQ=";
    });
    cargoLock = {
      lockFile = ./ouch-abf1d4e3e40e9064c7a184883fb3478c440c6c08/Cargo.lock;
      outputHashes = { };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  papermc = {
    pname = "papermc";
    version = "373";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/373/downloads/paper-1.17.1-373.jar";
      sha256 = "sha256-QVeWTbwpvFYdUYNbrvGvomGNEutxUACwzWEjlUKr7Uc=";
    };
  };
  picom = {
    pname = "picom";
    version = "fade045eadf171d2c732820d6ebde7d1943a1397";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "fade045eadf171d2c732820d6ebde7d1943a1397";
      fetchSubmodules = false;
      sha256 = "sha256-fPiLZ63+Bw5VCxVNqj9i5had2YLa+jFMMf85MYdqvHU=";
    });
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.39.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.39.0.tar.gz";
      sha256 = "sha256-/zO35/PktFkeucAii2SyRJto5Oih/oisa/Tx2sFqeY4=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "4c4bd77c87e7aa4db97ebfc245c66c72b2a97a2f";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "4c4bd77c87e7aa4db97ebfc245c66c72b2a97a2f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-F+kdJeuz53bo0LplpgnmhpJoOTAUrbK1AKax21hzSvo=";
    };
  };
  pure = {
    pname = "pure";
    version = "90dc9cf908481cc155e1ce5611f684916523fc30";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "90dc9cf908481cc155e1ce5611f684916523fc30";
      fetchSubmodules = false;
      sha256 = "sha256-nsmiP1RSG27WtwRJpTZvDi2CvUQExxdBs5my7T5TSKk=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "f7ac6d55df73a35a730ea73045d9cd623180cb4b";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "f7ac6d55df73a35a730ea73045d9cd623180cb4b";
      fetchSubmodules = false;
      sha256 = "sha256-YdXXPT/FlEEWDk8QrymQNFp0bj64E+0z7u0+edcLEhk=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "d373dc136b805097f5092d02365a90327dc1de4a";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "d373dc136b805097f5092d02365a90327dc1de4a";
      fetchSubmodules = false;
      sha256 = "sha256-JX9sdVXjX38RVNUupktBinyGtAPCEj5YfJBg/N+wabw=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "a93a2e33662c69bdf6e2c5bd9cf0889864ff1509";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "a93a2e33662c69bdf6e2c5bd9cf0889864ff1509";
      fetchSubmodules = false;
      sha256 = "sha256-TPVuuiJDzn4zDEx+06zlyBq6aeVly5QrHUzGAxclMYM=";
    });
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "70efa84f9bdf46593ee9d1a11acfe0a6e1c899a7";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "70efa84f9bdf46593ee9d1a11acfe0a6e1c899a7";
      fetchSubmodules = true;
      sha256 = "sha256-1k/s/9jvCrJVQZ6itnmmxG00h2/Q++PpfOkD43p36hg=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "e6bd5b06989964fb8f6dda425d727575a54f7f36";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "e6bd5b06989964fb8f6dda425d727575a54f7f36";
      fetchSubmodules = false;
      sha256 = "sha256-XnlpZjDFvCOg0wTyHNIPy/jJKqZ+vMCxNthka/HYoDU=";
    });
    cargoLock = {
      lockFile = ./rustdesk-e6bd5b06989964fb8f6dda425d727575a54f7f36/Cargo.lock;
      outputHashes = {
        "magnum-opus-0.3.4-2" = "sha256-3Bl4jyDg5E9zzADdz7jM5SY2HYksokE1jS/ocE/iXcc=";
        "rust-pulsectl-0.2.10" = "sha256-fJcd4aNixFW4dqp+RoHEYQKq78iYZsNa4SpopMIh8Fg=";
        "cpal-0.13.4" = "sha256-e9VG28xT+u/vDYuM1/cOAHFR+VXlYwcSC+XUWgEgv84=";
        "protobuf-3.0.0-pre" = "sha256-yEjMOD0G45MKGnJ8i8Bcm5oRBaj87jlcoeMK/VxRbn0=";
        "parity-tokio-ipc-0.7.2" = "sha256-3gBg303FKbLcbld5q+zb/KIlVKuRGcPpWJJ2zUXRLHM=";
        "sciter-rs-0.5.57" = "sha256-pF5Rwav78//oqDAv0Nhb7tawhSMnlSuy4sPUOfPd8NU=";
        "confy-0.4.1" = "sha256-5QwA4YfEEE6QqEEUJ3+C37UbUf88NYds38kIthVSo5Y=";
        "windows-service-0.4.0" = "sha256-SD+3tprBPEx4QnXmWEjruAwiTeoXofMVET3j+aXstBY=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "d65c42630c24e460ba88bfe95e5d8214ac9dd797";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "d65c42630c24e460ba88bfe95e5d8214ac9dd797";
      fetchSubmodules = false;
      sha256 = "sha256-oI8xy9sT42QfeT7LTjwQWC/9eiKI+A+e7GKLRs81NLg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "4cb6b8e6e97252dc9b0a089b1f793b6e27b0f1ed";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "4cb6b8e6e97252dc9b0a089b1f793b6e27b0f1ed";
      fetchSubmodules = false;
      sha256 = "sha256-/26LchjNRD896Mn/THR986AF1ikDug74/opBjtuRe1g=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-1wEChhE6B3Cj6HvmvOfFP26/BHvKbwdVAVT9b8he0sI=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-Q2QgwnxNFf+zzLbZ/gF2uvE3TZpapmQTUY4enMmMCOM=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-dsQV6a7gUkCHzGoEIRPbazjxoZ8uKG+AeqKXVkYTcKk=";
    };
  };
  snui = {
    pname = "snui";
    version = "8c536184c29e7979b3e6f2c8dbfafd975f9d8dfe";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "8c536184c29e7979b3e6f2c8dbfafd975f9d8dfe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PEEQkGD7qwYIa5+UfkWBk1TPiVCYUqTYE8KVnoRmIjE=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "a44ba6100e26df2c2900cbda8e3b2baf5bec0cdb";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "a44ba6100e26df2c2900cbda8e3b2baf5bec0cdb";
      fetchSubmodules = false;
      sha256 = "sha256-peVUrL1FcuQb3IO4jY1TPcq2VNiHSKT5SvL2vjULM8E=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "5046217e28084f7eaf69543f1f7c1b7c276496cc";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "5046217e28084f7eaf69543f1f7c1b7c276496cc";
      fetchSubmodules = false;
      sha256 = "sha256-diKIBEbgru1iJ9JoU8HhRxj7ciuvc9IkSSXXqZP/iI0=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.68.632.g2b11de83";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_53.snap";
      sha256 = "sha256-Cw37q54WXZ34pub4BPyYiLeQHJBHSKzY7dKlqfD7Obk=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "f4909621da43636185f2d2ffe4392178b8d654b6";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "f4909621da43636185f2d2ffe4392178b8d654b6";
      fetchSubmodules = false;
      sha256 = "sha256-5Sc/o8jRWeHQGJfwWcTobK0JsCGcMFt73T96VjCF4nc=";
    });
    cargoLock = {
      lockFile = ./spotifyd-f4909621da43636185f2d2ffe4392178b8d654b6/Cargo.lock;
      outputHashes = { };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "34295e843b3d4ee5d2d433079ecda7becf940cbe";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "34295e843b3d4ee5d2d433079ecda7becf940cbe";
      fetchSubmodules = false;
      sha256 = "sha256-MHlDHDjMhx73RxcQ9i5FvgbJZNwABgSMjeyIhfabeWk=";
    });
  };
  sway-borders = {
    pname = "sway-borders";
    version = "d8012358055f55a6bff883c47c1b2f7391c43d3b";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "d8012358055f55a6bff883c47c1b2f7391c43d3b";
      fetchSubmodules = false;
      sha256 = "sha256-SkfKiFa6KkRxYL/7lR0NXb+EXoGWgev0EEoCsgV54as=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  tailscale = {
    pname = "tailscale";
    version = "e6fbc0cd54906c85f58f8d69fb5872886db8811d";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "e6fbc0cd54906c85f58f8d69fb5872886db8811d";
      fetchSubmodules = false;
      sha256 = "sha256-M8Gh79c/Hzmfy2jbuF+dJMg+eE1xbPKhabtNWRjX+pc=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "20c7e85e3d64602b87699c388185513e112a5a9c";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "20c7e85e3d64602b87699c388185513e112a5a9c";
      fetchSubmodules = false;
      sha256 = "sha256-XP874ciM4eBrT/rOGqwMzZQ27T0QJ3ggODHB5pIkZzU=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.4.00.26453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.26453_amd64.deb";
      sha256 = "sha256-7hW1d5Oqa3nM2nRNUjLaZwM1q9kxuuKgIPUEOhKauFk=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "55728fde0cd3c58044e9f2b7d6d1e56fe189148b";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-f+hSmQfznOSpWDQ2Zi6uns/B05Dx9Rh2suYKBomfUoM=";
    };
  };
  tuinitymc = {
    pname = "tuinitymc";
    version = "4c31ea1630f3dfd4a1d64de56c37ac1b0cc096a7";
    src = fetchurl {
      url = "https://ci.codemc.io/job/Spottedleaf/job/Tuinity-1.17/lastSuccessfulBuild/artifact/tuinity-paperclip.jar";
      sha256 = "sha256-DYd7nlGN0JIJO0k1MCeXyW06wtUBD+voD0THYJ5WJ3E=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "25c9a338f77b948e29d653c95f68d93956aa8c25";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "25c9a338f77b948e29d653c95f68d93956aa8c25";
      fetchSubmodules = false;
      sha256 = "sha256-c3ERmqjhyxR72N6ya7AAzjuVrTzleXGHX1ObhupjHBg=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "4b0801037f599c363b29bb107a9df40df0f6c967";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "4b0801037f599c363b29bb107a9df40df0f6c967";
      fetchSubmodules = false;
      sha256 = "sha256-vBbLXaByaHkR6i+1XhpfbKtcoOBjClueo62LTXR+Duk=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.23.0";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.23.0";
      fetchSubmodules = false;
      sha256 = "sha256-lbOsJsmZxdBNTbhsGJ1mcjWlJ6802GYM3waTiWYOErY=";
    });
    cargoLock = {
      lockFile = ./vaultwarden-1.23.0/Cargo.lock;
      outputHashes = {
        "data-url-0.1.0" = "sha256-7arUV7+XYxk3UFYIoD/A7NOKLom8QdEWJLFIIfUFuxs=";
        "rocket-0.5.0-dev" = "sha256-sZL6GtLrfDy0ePix2UxZTdpFQvvc0G/Q+7qbCLGknqY=";
        "job_scheduler-1.2.1" = "sha256-b0jIKAHVrQNdZdlq+5kfGAOsi8bHu20QDtQaWTuJYtU=";
        "devise-0.3.0" = "sha256-crnEOKK7FiuIs55mOKgNfb3mNzr3QLI0icPPuG+xKVI=";
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2.24.1";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2.24.1/bw_web_v2.24.1.tar.gz";
      sha256 = "sha256-NYXjmBFvVdpbz2/55MirPBlGVO3hWkH+2rTtxixprXc=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  vscode-extensions-ActiveFileInStatusBar = {
    pname = "vscode-extensions-ActiveFileInStatusBar";
    version = "1.0.3";
    src = fetchurl {
      url = "https://RoscoP.gallery.vsassets.io/_apis/public/gallery/publisher/RoscoP/extension/ActiveFileInStatusBar/1.0.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-5GJODdKL8949a8KR2O7hGsRgAknfPyNEJ+9aiEYYemk=";
    };
    license = "mit";
  };
  vscode-extensions-Kotlin = {
    pname = "vscode-extensions-Kotlin";
    version = "1.7.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/mathiasfrohlich/Kotlin/1.7.1/file/mathiasfrohlich.Kotlin-1.7.1.vsix";
      sha256 = "sha256-I7ur5yZRaKYMCCXEAlWJ5RD61rQbK1vFX8Phk27J4gw=";
    };
    homepage = "https://github.com/mathiasfrohlich/vscode-kotlin";
    license = "asl20";
    description = "Kotlin language support for VS Code";
  };
  vscode-extensions-Material-theme = {
    pname = "vscode-extensions-Material-theme";
    version = "3.13.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/zhuangtongfa/material-theme/3.13.2/file/zhuangtongfa.material-theme-3.13.2.vsix";
      sha256 = "sha256-hKkHuWDiaOXjpH3X2HYtpBswxwU8qhazWx9cxVyfD4o=";
    };
    homepage = "https://github.com/Binaryify/OneDark-Pro";
    license = "mit";
    description = "Atom's iconic One Dark theme for Visual Studio Code";
  };
  vscode-extensions-astro = {
    pname = "vscode-extensions-astro";
    version = "0.8.0";
    src = fetchurl {
      url = "https://astro-build.gallery.vsassets.io/_apis/public/gallery/publisher/astro-build/extension/astro-vscode/0.8.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-7ww4TyduUU2C0co2AvPpzas874dYt0KUljYPW+IAPN0=";
    };
    license = "mit";
  };
  vscode-extensions-awesome-flutter-snippets = {
    pname = "vscode-extensions-awesome-flutter-snippets";
    version = "3.0.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Nash/awesome-flutter-snippets/3.0.0/file/Nash.awesome-flutter-snippets-3.0.0.vsix";
      sha256 = "sha256-SyQ8dJ2M3RYJC1uf7gnDCMSa9i+t7k+uhR7M45gkgGU=";
    };
    homepage = "https://github.com/Neevash/awesome-flutter-snippets";
    license = "asl20";
    description = "Awesome Flutter Snippets is a collection snippets and shortcuts for commonly used Flutter functions and classes";
  };
  vscode-extensions-bracket-pair-colorizer-2 = {
    pname = "vscode-extensions-bracket-pair-colorizer-2";
    version = "0.1.4";
    src = fetchurl {
      url = "https://open-vsx.org/api/CoenraadS/bracket-pair-colorizer-2/0.1.4/file/CoenraadS.bracket-pair-colorizer-2-0.1.4.vsix";
      sha256 = "sha256-NsxiPw689RTwfwcCoxflDancEeh0Ih/p45PGS2qm6Ck=";
    };
    homepage = "https://github.com/CoenraadS/Bracket-Pair-Colorizer-2";
    license = "mit";
    description = "A customizable extension for colorizing matching brackets";
  };
  vscode-extensions-code-runner = {
    pname = "vscode-extensions-code-runner";
    version = "0.11.6";
    src = fetchurl {
      url = "https://open-vsx.org/api/formulahendry/code-runner/0.11.6/file/formulahendry.code-runner-0.11.6.vsix";
      sha256 = "sha256-EHOaOsxmmnPXcDzl/7H7zDMxSsEB+2cjoaUOaJYpZHI=";
    };
    homepage = "https://github.com/formulahendry/vscode-code-runner";
    license = "mit";
    description = "Run C, C++, Java, JS, PHP, Python, Perl, Ruby, Go, Lua, Groovy, PowerShell, CMD, BASH, F#, C#, VBScript, TypeScript, CoffeeScript, Scala, Swift, Julia, Crystal, OCaml, R, AppleScript, Elixir, VB.NET, Clojure, Haxe, Obj-C, Rust, Racket, Scheme, AutoHotkey, AutoIt, Kotlin, Dart, Pascal, Haskell, Nim, D, Lisp, Kit, V, SCSS, Sass, CUDA, Less, Fortran";
  };
  vscode-extensions-codeql = {
    pname = "vscode-extensions-codeql";
    version = "1.5.6";
    src = fetchurl {
      url = "https://open-vsx.org/api/GitHub/vscode-codeql/1.5.6/file/GitHub.vscode-codeql-1.5.6.vsix";
      sha256 = "sha256-QCIxxxcRW7F4uz30mviWr4LYpbqBdFF1nZVSomDR7nQ=";
    };
    homepage = "https://github.com/github/vscode-codeql";
    license = "mit";
    description = "CodeQL for Visual Studio Code";
  };
  vscode-extensions-codesnap = {
    pname = "vscode-extensions-codesnap";
    version = "1.3.4";
    src = fetchurl {
      url = "https://open-vsx.org/api/adpyke/codesnap/1.3.4/file/adpyke.codesnap-1.3.4.vsix";
      sha256 = "sha256-x1EpD4Q0tOhkCB9fl2mc7etaB2sI1d6KjbdUqqWIk+k=";
    };
    homepage = "https://github.com/kufii/CodeSnap";
    license = "mit";
    description = "\128247 Take beautiful screenshots of your code";
  };
  vscode-extensions-css-initial-value = {
    pname = "vscode-extensions-css-initial-value";
    version = "0.2.5";
    src = fetchurl {
      url = "https://dzhavat.gallery.vsassets.io/_apis/public/gallery/publisher/dzhavat/extension/css-initial-value/0.2.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-DWSqHWbQ2BJe+aGcWEKHDY1W2finT+X54up2MtQUJT8=";
    };
    license = "mit";
  };
  vscode-extensions-dart-code = {
    pname = "vscode-extensions-dart-code";
    version = "3.28.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Dart-Code/dart-code/3.28.0/file/Dart-Code.dart-code-3.28.0.vsix";
      sha256 = "sha256-N2PwyJZS3FnXesS3OGB1traSjVWmXhluZ91lxCTwl0Y=";
    };
    homepage = "https://github.com/Dart-Code/Dart-Code";
    license = "mit";
    description = "Dart language support and debugger for Visual Studio Code.";
  };
  vscode-extensions-dendron = {
    pname = "vscode-extensions-dendron";
    version = "0.67.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/dendron/dendron/0.67.1/file/dendron.dendron-0.67.1.vsix";
      sha256 = "sha256-Nz2opwK5emjJOVRU//5llIAhkmRX1oRg0pzMQes0aPg=";
    };
    homepage = "https://github.com/dendronhq/dendron";
    license = "agpl3Only";
    description = "Dendron is a hierarchal note taking tool that grows as you do. ";
  };
  vscode-extensions-discord-presence = {
    pname = "vscode-extensions-discord-presence";
    version = "5.7.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/icrawl/discord-vscode/5.7.0/file/icrawl.discord-vscode-5.7.0.vsix";
      sha256 = "sha256-F18E0UOIaCLKh50TgSDv/EqsWt15FbnY+h8/QejAi1w=";
    };
    homepage = "https://github.com/iCrawl/discord-vscode";
    license = "mit";
    description = "Update your discord status with a rich presence.";
  };
  vscode-extensions-dotenv = {
    pname = "vscode-extensions-dotenv";
    version = "1.0.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/mikestead/dotenv/1.0.1/file/mikestead.dotenv-1.0.1.vsix";
      sha256 = "sha256-U5M0/G6/p4HqMtM2JAulkeKl+5lBd5bE4thPtYA4l8Y=";
    };
    homepage = "https://github.com/mikestead/vscode-dotenv";
    license = "mit";
    description = "Support for dotenv file syntax";
  };
  vscode-extensions-eslint = {
    pname = "vscode-extensions-eslint";
    version = "2.1.20";
    src = fetchurl {
      url = "https://open-vsx.org/api/dbaeumer/vscode-eslint/2.1.20/file/dbaeumer.vscode-eslint-2.1.20.vsix";
      sha256 = "sha256-2CSa5xJIVM8/SwqRablxOJufDhHJRpqgyohlQ1pT3hE=";
    };
    homepage = "https://github.com/Microsoft/vscode-eslint";
    license = "mit";
    description = "Integrates ESLint JavaScript into VS Code.";
  };
  vscode-extensions-even-better-toml = {
    pname = "vscode-extensions-even-better-toml";
    version = "0.14.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/tamasfe/even-better-toml/0.14.2/file/tamasfe.even-better-toml-0.14.2.vsix";
      sha256 = "sha256-s9aRdMm/1P7kZElgP6RPAKrpMYwRksJWkNzWVD8dC1Q=";
    };
    homepage = "https://github.com/tamasfe/taplo";
    license = "mit";
    description = "Fully-featured TOML support";
  };
  vscode-extensions-flutter = {
    pname = "vscode-extensions-flutter";
    version = "3.28.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Dart-Code/flutter/3.28.0/file/Dart-Code.flutter-3.28.0.vsix";
      sha256 = "sha256-uASi6cWr8UgHZy0R8079DqswlzXh0EmWShvliOxVcpE=";
    };
    homepage = "https://github.com/Dart-Code/Flutter";
    license = "mit";
    description = "Flutter support and debugger for Visual Studio Code.";
  };
  vscode-extensions-gitlens = {
    pname = "vscode-extensions-gitlens";
    version = "11.6.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/eamodio/gitlens/11.6.0/file/eamodio.gitlens-11.6.0.vsix";
      sha256 = "sha256-JxCNE/IL/v94xWmhebsRZo1Gw+nSSpDgZ41ZGongGVI=";
    };
    homepage = "https://github.com/eamodio/vscode-gitlens";
    license = "mit";
    description = "Supercharge the Git capabilities built into Visual Studio Code \8212 Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more";
  };
  vscode-extensions-headwind = {
    pname = "vscode-extensions-headwind";
    version = "1.7.0";
    src = fetchurl {
      url = "https://heybourn.gallery.vsassets.io/_apis/public/gallery/publisher/heybourn/extension/headwind/1.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-yXsZoSuJQTdbHLjEERXX2zVheqNYmcPXs97/uQYa7og=";
    };
    homepage = "https://github.com/heybourn/headwind";
    license = "mit";
    description = "An opinionated Tailwind CSS class sorter built for Visual Studio Code";
  };
  vscode-extensions-html-css-class-completion = {
    pname = "vscode-extensions-html-css-class-completion";
    version = "1.20.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Zignd/html-css-class-completion/1.20.0/file/Zignd.html-css-class-completion-1.20.0.vsix";
      sha256 = "sha256-ZoTxQ4Wf9ZFDyv/C6iSv3q6igW0rcCZogQEx5dK6354=";
    };
    homepage = "https://github.com/Zignd/HTML-CSS-Class-Completion";
    license = "mit";
    description = "CSS class name completion for the HTML class attribute based on the definitions found in your workspace.";
  };
  vscode-extensions-markdown-all-in-one = {
    pname = "vscode-extensions-markdown-all-in-one";
    version = "3.4.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/yzhang/markdown-all-in-one/3.4.0/file/yzhang.markdown-all-in-one-3.4.0.vsix";
      sha256 = "sha256-TFdvlN662Hvb6VlIqbtdt0W582SrS2R5cSRowHH0j8M=";
    };
    homepage = "https://github.com/yzhang-gh/vscode-markdown";
    license = "mit";
    description = "All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)";
  };
  vscode-extensions-markdown-preview-enhanced = {
    pname = "vscode-extensions-markdown-preview-enhanced";
    version = "0.6.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/shd101wyy/markdown-preview-enhanced/0.6.1/file/shd101wyy.markdown-preview-enhanced-0.6.1.vsix";
      sha256 = "sha256-BnjFsmL5ytA65bkiigtHz9iW1Sgr/ShNLcDqgMBkjx0=";
    };
    homepage = "https://github.com/shd101wyy/vscode-markdown-preview-enhanced";
    license = "ncsa";
    description = "Markdown Preview Enhanced ported to vscode";
  };
  vscode-extensions-material-icon-theme = {
    pname = "vscode-extensions-material-icon-theme";
    version = "4.10.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/PKief/material-icon-theme/4.10.0/file/PKief.material-icon-theme-4.10.0.vsix";
      sha256 = "sha256-x7ZITFa2G1oCA7+PX/py+r75fukxvU09BazcfOPc8Ak=";
    };
    homepage = "https://github.com/PKief/vscode-material-icon-theme";
    license = "mit";
    description = "Material Design Icons for Visual Studio Code";
  };
  vscode-extensions-ms-vscode-cpptools = {
    pname = "vscode-extensions-ms-vscode-cpptools";
    version = "1.7.1";
    src = fetchurl {
      url = "https://github.com/microsoft/vscode-cpptools/releases/download/1.7.1/cpptools-linux.vsix";
      sha256 = "sha256-LqndG/vv8LgVPEX6dGkikDB6M6ISneo2UJ78izXVFbk=";
    };
  };
  vscode-extensions-nix-env-selector = {
    pname = "vscode-extensions-nix-env-selector";
    version = "1.0.7";
    src = fetchurl {
      url = "https://open-vsx.org/api/arrterian/nix-env-selector/1.0.7/file/arrterian.nix-env-selector-1.0.7.vsix";
      sha256 = "sha256-ifFIB+JxgujvLpr9zUV0D1jhihxIefvyDZkbPwW7EZU=";
    };
    homepage = "https://github.com/arrterian/nix-env-selector";
    license = "mit";
    description = "Allows switch environment for Visual Studio Code and extensions based on Nix config file.";
  };
  vscode-extensions-nix-ide = {
    pname = "vscode-extensions-nix-ide";
    version = "0.1.18";
    src = fetchurl {
      url = "https://open-vsx.org/api/jnoortheen/nix-ide/0.1.18/file/jnoortheen.nix-ide-0.1.18.vsix";
      sha256 = "sha256-GoCzYLkp6p+Oe1G3ilxNnXhtyRG3XQ8gUVy5lYd85cM=";
    };
    homepage = "https://github.com/nix-community/vscode-nix-ide";
    license = "mit";
    description = "Nix language support with formatting and error report.";
  };
  vscode-extensions-nixpkgs-fmt = {
    pname = "vscode-extensions-nixpkgs-fmt";
    version = "0.0.1";
    src = fetchurl {
      url = "https://B4dM4n.gallery.vsassets.io/_apis/public/gallery/publisher/B4dM4n/extension/nixpkgs-fmt/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-vz2kU36B1xkLci2QwLpl/SBEhfSWltIDJ1r7SorHcr8=";
    };
    license = "mit";
  };
  vscode-extensions-output-colorizer = {
    pname = "vscode-extensions-output-colorizer";
    version = "0.1.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/IBM/output-colorizer/0.1.2/file/IBM.output-colorizer-0.1.2.vsix";
      sha256 = "sha256-xa14/fZfj61NQI+4WqAkZVYq2E9cAgu4C5/AMua1SSY=";
    };
    homepage = "https://github.com/IBM-Bluemix/vscode-log-output-colorizer";
    license = "mit";
    description = "Syntax highlighting for log files";
  };
  vscode-extensions-pascal = {
    pname = "vscode-extensions-pascal";
    version = "9.3.0";
    src = fetchurl {
      url = "https://alefragnani.gallery.vsassets.io/_apis/public/gallery/publisher/alefragnani/extension/pascal/9.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-zCSsx/9ui1t6rmMNtUmsiZNL3TwPWsulO3yhvtuRrEk=";
    };
    license = "mit";
  };
  vscode-extensions-pascal-formatter = {
    pname = "vscode-extensions-pascal-formatter";
    version = "2.5.0";
    src = fetchurl {
      url = "https://alefragnani.gallery.vsassets.io/_apis/public/gallery/publisher/alefragnani/extension/pascal-formatter/2.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-3mvnfeJy/d/qaRF66VGYMLRHsYjqg3mIjkLJeZx5P9s=";
    };
    license = "mit";
  };
  vscode-extensions-prettier = {
    pname = "vscode-extensions-prettier";
    version = "9.0.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/esbenp/prettier-vscode/9.0.0/file/esbenp.prettier-vscode-9.0.0.vsix";
      sha256 = "sha256-LenRtP7I1uv/lZRYJHw55TdYgez5ndHRRhUtsjDy0EM=";
    };
    homepage = "https://github.com/prettier/prettier-vscode";
    license = "mit";
    description = "Code formatter using prettier";
  };
  vscode-extensions-pubspec-assist = {
    pname = "vscode-extensions-pubspec-assist";
    version = "2.3.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/jeroen-meijer/pubspec-assist/2.3.2/file/jeroen-meijer.pubspec-assist-2.3.2.vsix";
      sha256 = "sha256-FwP1Eu7aASOSlb9NuVUOFyeFNPh+avLjLpwdsZYsNEs=";
    };
    homepage = "https://github.com/jeroen-meijer/pubspec-assist";
    license = "mit";
    description = "Easily add and update dependencies to your Dart and Flutter project.";
  };
  vscode-extensions-python = {
    pname = "vscode-extensions-python";
    version = "2021.10.1365161279";
    src = fetchurl {
      url = "https://open-vsx.org/api/ms-python/python/2021.10.1365161279/file/ms-python.python-2021.10.1365161279.vsix";
      sha256 = "sha256-mHt+cmYlONWwRdWgmtfetwfk1jRgegmxbEUHLlcllCk=";
    };
    homepage = "https://github.com/Microsoft/vscode-python";
    license = "mit";
    description = "Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.";
  };
  vscode-extensions-react-native = {
    pname = "vscode-extensions-react-native";
    version = "1.7.1";
    src = fetchurl {
      url = "https://msjsdiag.gallery.vsassets.io/_apis/public/gallery/publisher/msjsdiag/extension/vscode-react-native/1.7.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-YnBTzA5Ay7zp1HIeam49yAGZjQVK6wP1iKswBHrzuKU=";
    };
    license = "mit";
  };
  vscode-extensions-rest-client = {
    pname = "vscode-extensions-rest-client";
    version = "0.24.5";
    src = fetchurl {
      url = "https://open-vsx.org/api/humao/rest-client/0.24.5/file/humao.rest-client-0.24.5.vsix";
      sha256 = "sha256-PDgTSzK62LPWokkGK/v/+plNBdAM6ZkZx+AKCKUcCpA=";
    };
    homepage = "https://github.com/Huachao/vscode-restclient";
    license = "mit";
    description = "REST Client for Visual Studio Code";
  };
  vscode-extensions-rust = {
    pname = "vscode-extensions-rust";
    version = "0.7.8";
    src = fetchurl {
      url = "https://open-vsx.org/api/rust-lang/rust/0.7.8/file/rust-lang.rust-0.7.8.vsix";
      sha256 = "sha256-5nur1zFsqudAzP5mQS/7r4rmgkbwY7+ONi0qM/3Ftwo=";
    };
    homepage = "https://github.com/rust-lang/rls-vscode";
    license = "[ \"mit\", \"asl20\" ]";
    description = "Rust for Visual Studio Code (powered by Rust Language Server/Rust Analyzer). Provides lints, code completion and navigation, formatting and more.";
  };
  vscode-extensions-svelte = {
    pname = "vscode-extensions-svelte";
    version = "105.5.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/svelte/svelte-vscode/105.5.0/file/svelte.svelte-vscode-105.5.0.vsix";
      sha256 = "sha256-JTbscWRHN4OZ5iBpVYbfZF94cW0F502MuAYegRi7jr8=";
    };
    homepage = "https://github.com/sveltejs/language-tools";
    license = "mit";
    description = "Svelte language support for VS Code";
  };
  vscode-extensions-tailwindcss = {
    pname = "vscode-extensions-tailwindcss";
    version = "0.7.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/bradlc/vscode-tailwindcss/0.7.1/file/bradlc.vscode-tailwindcss-0.7.1.vsix";
      sha256 = "sha256-uhb7fU5RDVeTfh3/PlHtSzI8Or1TH2ZRkSNINAPtsng=";
    };
    homepage = "https://github.com/tailwindlabs/tailwindcss-intellisense";
    license = "mit";
    description = "Intelligent Tailwind CSS tooling for VS Code";
  };
  vscode-extensions-versionlens = {
    pname = "vscode-extensions-versionlens";
    version = "1.0.9";
    src = fetchurl {
      url = "https://open-vsx.org/api/pflannery/vscode-versionlens/1.0.9/file/pflannery.vscode-versionlens-1.0.9.vsix";
      sha256 = "sha256-cPESnrSnCurVUEgPh6g4Tk7PY3K4du6w9pcOZUYf1bM=";
    };
    homepage = "https://gitlab.com/versionlens/vscode-versionlens";
    license = "isc";
    description = "Shows the latest version for each package using code lens";
  };
  waydroid = {
    pname = "waydroid";
    version = "d03e10c132de8e03dff781868b3e37b7f7c7128a";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "d03e10c132de8e03dff781868b3e37b7f7c7128a";
      fetchSubmodules = false;
      sha256 = "sha256-y2+rRwxZ4jrnWDEYruzjOQlLF2ERB4v+sGchPK5mrTU=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "64cf7a5c1b1e39b3180471b74434a81874addf91";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "64cf7a5c1b1e39b3180471b74434a81874addf91";
      fetchSubmodules = false;
      sha256 = "sha256-UmLK76BPYhg1cUDVTEb1JqcTZxpJtjERNL5gcoKkAiU=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "49a1d3dd47ecb7b652affc3ea13bbb15abff4e01";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "49a1d3dd47ecb7b652affc3ea13bbb15abff4e01";
      fetchSubmodules = false;
      sha256 = "sha256-Md8u94o+l7MgDTqXN7cg8QZOluuQSveOpPlvb4Jtvak=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "d54e32f5057756d1e543de48ed87a019d56936a1";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "d54e32f5057756d1e543de48ed87a019d56936a1";
      fetchSubmodules = false;
      sha256 = "sha256-LZ0GLJFUUvzsPhU2sBkfy5mPpQHuPzYhbumwFKnogoA=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2391.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2391.0-linux-x64.zip";
      sha256 = "sha256-7gH808C67m/s09e4rQUQHb/t+iGVdzW+YzrB1ZxGIdo=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qKKb/i67QY/NxZFkJaVRc3hGPjjnRfgpMqGqZ0YNQE8=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "57acac1d4c7967f4661fb1c9f86f48f34a46c48d";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "57acac1d4c7967f4661fb1c9f86f48f34a46c48d";
      fetchSubmodules = false;
      sha256 = "sha256-Ar5ccxwVwRnzd5pAF6a9M7Z1btKxXHLUefaTqXSVDfY=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "2df3a62c66272c29299f7076c0f90a4f02b4d33e";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "2df3a62c66272c29299f7076c0f90a4f02b4d33e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZX5tO9xT3SXHbXCspqz48JqiaJg3KlJtkWYmYj7sYz8=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "7e5f4986d570e08dff1ef9934d7c363962c90a42";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "7e5f4986d570e08dff1ef9934d7c363962c90a42";
      fetchSubmodules = false;
      sha256 = "sha256-oaKFz0+7lnyVk3mKGZeIZ6m3YyF+Hktr+hQlFSNO4PM=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.8.3.145";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.8.3.145/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-eRp+fWh6w+X8LWbVhPtGodLqTsitnFMJyCXNy9Z9itw=";
    };
  };
}
