# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adguardhome-darwin-amd64 = {
    pname = "adguardhome-darwin-amd64";
    version = "0.107.0";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0/AdGuardHome_darwin_amd64.zip";
      sha256 = "sha256-HoFv8gsrMbMnXJZXYJhQyVUXFzDh8c1/tnkFw0j1IDg=";
    };
  };
  adguardhome-linux-386 = {
    pname = "adguardhome-linux-386";
    version = "0.107.0";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0/AdGuardHome_linux_386.tar.gz";
      sha256 = "sha256-gWylZgCk+bGf1h2lTX2gRnW39P7C2ks0LH7anJW6JKw=";
    };
  };
  adguardhome-linux-amd64 = {
    pname = "adguardhome-linux-amd64";
    version = "0.107.0";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-g2DIeXwaqTTfshYyyDNHbOU57YUbuxXDKJHFqKFrqzw=";
    };
  };
  adguardhome-linux-arm64 = {
    pname = "adguardhome-linux-arm64";
    version = "0.107.0";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.0/AdGuardHome_linux_arm64.tar.gz";
      sha256 = "sha256-PovduGRcfSUbhqX1cxRgMknN8mWJekjjpB0b1TE1//g=";
    };
  };
  adl = {
    pname = "adl";
    version = "45b1dd4cb9350cde6b1fb8bc03d098c6864efcd5";
    src = fetchFromGitHub ({
      owner = "RaitaroH";
      repo = "adl";
      rev = "45b1dd4cb9350cde6b1fb8bc03d098c6864efcd5";
      fetchSubmodules = false;
      sha256 = "sha256-AgIUMKo2mylkU/5Lhqz0PCmHEqQKQdPHnIZaqo8dr+o=";
    });
  };
  anbox = {
    pname = "anbox";
    version = "84f0268012cbe322ad858d76613f4182074510ac";
    src = fetchFromGitHub ({
      owner = "anbox";
      repo = "anbox";
      rev = "84f0268012cbe322ad858d76613f4182074510ac";
      fetchSubmodules = true;
      sha256 = "sha256-QXWhatewiUDQ93cH1UZsYgbjUxpgB1ajtGFYZnKmabc=";
    });
  };
  anime-downloader = {
    pname = "anime-downloader";
    version = "17fb8fe8bcf0525cc2052b37492c7f6fc2f56454";
    src = fetchFromGitHub ({
      owner = "anime-dl";
      repo = "anime-downloader";
      rev = "17fb8fe8bcf0525cc2052b37492c7f6fc2f56454";
      fetchSubmodules = false;
      sha256 = "sha256-DPA9FB0nk3lruRpFp2oql6GvaESkcao0iWenphD1qes=";
    });
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
      fetchSubmodules = false;
      sha256 = "sha256-E6Q7nVPuoC81aGMYOFkmlRv1i6eoOtbYw2AeCCXMR2A=";
    });
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "2787da7f90b31b19d3549b61a77210b79bd1166b";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "2787da7f90b31b19d3549b61a77210b79bd1166b";
      fetchSubmodules = false;
      sha256 = "sha256-w4YrtxT+Ytug1B0JhZoh0QLxqOl4Wg2/PWObIdQJ5Os=";
    });
  };
  avizo = {
    pname = "avizo";
    version = "4e1f2200d497c8b0e0c372195aee627bcdc89a08";
    src = fetchFromGitHub ({
      owner = "misterdanb";
      repo = "avizo";
      rev = "4e1f2200d497c8b0e0c372195aee627bcdc89a08";
      fetchSubmodules = false;
      sha256 = "sha256-xQLgemNlIcqb47uf3tYiMK1vXyyUHCKUywFJTfEuayo=";
    });
  };
  awesome = {
    pname = "awesome";
    version = "7451c6952e0a24bd54edc0f7ecff6ad46ef65dcb";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "7451c6952e0a24bd54edc0f7ecff6ad46ef65dcb";
      fetchSubmodules = false;
      sha256 = "sha256-5mxa7rid/meFrBUY9GBuJlHGOU9OJJP0hwIRMvSwh58=";
    });
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchFromGitHub ({
      owner = "K4rakara";
      repo = "awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      sha256 = "sha256-VuMmEf5bCifXKHerTyFOYW4w4fXA83HM02Oj4VmQOeo=";
    });
  };
  bling = {
    pname = "bling";
    version = "e0423796b075b21cf3252a9d59b6c23dbf2bb46c";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "e0423796b075b21cf3252a9d59b6c23dbf2bb46c";
      fetchSubmodules = false;
      sha256 = "sha256-l5FifujhIu1z2aLViwK7c74MZXl3ZauGklQixtFybN0=";
    });
  };
  bottles = {
    pname = "bottles";
    version = "958b782601c71d7010aaa43a873afedd439eaad5";
    src = fetchFromGitHub ({
      owner = "bottlesdevs";
      repo = "Bottles";
      rev = "958b782601c71d7010aaa43a873afedd439eaad5";
      fetchSubmodules = false;
      sha256 = "sha256-KptBpZPHlE8rHOZBVzklIk2Ar7hrRQ38muvhAMjHswk=";
    });
  };
  caddy = {
    pname = "caddy";
    version = "5333c3528bd2badf1676efcced322d151e3706c8";
    src = fetchFromGitHub ({
      owner = "caddyserver";
      repo = "caddy";
      rev = "5333c3528bd2badf1676efcced322d151e3706c8";
      fetchSubmodules = false;
      sha256 = "sha256-cF9/xZDAK03LmDQu4fbQkntDmGl6st26ni2rpNreQMo=";
    });
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
      sha256 = "sha256-c4Zp7f9/FGn+XkESAth/k7oltF8zKmI/tgfUnFmqlTE=";
    };
  };
  discord-canary = {
    pname = "discord-canary";
    version = "0.0.131";
    src = fetchurl {
      url = "https://dl-canary.discordapp.net/apps/linux/0.0.131/discord-canary-0.0.131.tar.gz";
      sha256 = "sha256-ZYPdE02Jq79LmvXu7KIJFugJX++Nnj0Og/mBuaP/+SA=";
    };
  };
  dnscrypt-proxy2 = {
    pname = "dnscrypt-proxy2";
    version = "53f3a0e63d45ce90bcb7c36a441f3ceeaffb214a";
    src = fetchFromGitHub ({
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "53f3a0e63d45ce90bcb7c36a441f3ceeaffb214a";
      fetchSubmodules = false;
      sha256 = "sha256-XefitjRwvXOIL9DsaN4xgkyObBcBWcZSwTuPJmeG734=";
    });
  };
  doggo = {
    pname = "doggo";
    version = "9ae8b0a3f24489da62291cfee0561ae9cf214c15";
    src = fetchFromGitHub ({
      owner = "mr-karan";
      repo = "doggo";
      rev = "9ae8b0a3f24489da62291cfee0561ae9cf214c15";
      fetchSubmodules = false;
      sha256 = "sha256-JiBpocumhdPXDx4sYJaelfm/7UheHB08sEkgi6hwTfs=";
    });
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "13186767e8790a6bfb8502da1846fc800029150e";
    src = fetchFromGitHub ({
      owner = "JulienMaille";
      repo = "dribbblish-dynamic-theme";
      rev = "13186767e8790a6bfb8502da1846fc800029150e";
      fetchSubmodules = false;
      sha256 = "sha256-FgzHcQG7zMuYamrgdMJYCnCB0smHmpSMEDkvErAo7zc=";
    });
  };
  droidcam = {
    pname = "droidcam";
    version = "1a8ac86b5941d7784c73300d63654db7296d4319";
    src = fetchFromGitHub ({
      owner = "aramg";
      repo = "droidcam";
      rev = "1a8ac86b5941d7784c73300d63654db7296d4319";
      fetchSubmodules = false;
      sha256 = "sha256-3iA7GDTiCx5vHawj8ZBFAK0BIfmxEFuQrVfL7Gi6FhM=";
    });
  };
  duf = {
    pname = "duf";
    version = "ca80cac8339e32deba9c79b07c689300025107a4";
    src = fetchFromGitHub ({
      owner = "muesli";
      repo = "duf";
      rev = "ca80cac8339e32deba9c79b07c689300025107a4";
      fetchSubmodules = false;
      sha256 = "sha256-rAXU4IufIfNhpgiJ1NGJRByuVfaycejcu6AYTIGBW1E=";
    });
  };
  eww = {
    pname = "eww";
    version = "106106ade31e7cc669f2ae53f24191cd0a683c39";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "eww";
      rev = "106106ade31e7cc669f2ae53f24191cd0a683c39";
      fetchSubmodules = false;
      sha256 = "sha256-VntDl7JaIfvn3pd+2uDocnXFRkPnQQbRkYDn4XWeC5o=";
    });
    cargoLock = {
      lockFile = ./eww-106106ade31e7cc669f2ae53f24191cd0a683c39/Cargo.lock;
      outputHashes = { };
    };
  };
  fake-background-webcam = {
    pname = "fake-background-webcam";
    version = "ba100796e2ea383de02a59a23c8cd05b917529f7";
    src = fetchFromGitHub ({
      owner = "fangfufu";
      repo = "Linux-Fake-Background-Webcam";
      rev = "ba100796e2ea383de02a59a23c8cd05b917529f7";
      fetchSubmodules = false;
      sha256 = "sha256-JkdY2G6y9zimEdfHxjnJd5M+0OAgL85nABAqBTMZAk8=";
    });
  };
  flameshot = {
    pname = "flameshot";
    version = "06eb7acdd3df75cbd490a0aa5c3090769a414577";
    src = fetchFromGitHub ({
      owner = "flameshot-org";
      repo = "flameshot";
      rev = "06eb7acdd3df75cbd490a0aa5c3090769a414577";
      fetchSubmodules = false;
      sha256 = "sha256-Q7POkZcqygKCL+i8LlBx34lDnRJXkTg9ehsGgFQRDCs=";
    });
  };
  flyingfox = {
    pname = "flyingfox";
    version = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
    src = fetchFromGitHub ({
      owner = "akshat46";
      repo = "FlyingFox";
      rev = "4a6ba46cafc189ad628ee13bb8d3eef3e69fbced";
      fetchSubmodules = false;
      sha256 = "sha256-ZUTQ2VvIAEPbLnEX2AYScAGTM3hWp7vUuGCz2wd8qG0=";
    });
  };
  frece = {
    pname = "frece";
    version = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
    src = fetchFromGitHub ({
      owner = "YodaEmbedding";
      repo = "frece";
      rev = "d4071c6c852e68dda82b7ab0bfb0f141b39d4484";
      fetchSubmodules = false;
      sha256 = "sha256-lLSRLcnUJqWCEIJEOVHANzxTI+xR3VegRHtjHHI0gTs=";
    });
    cargoLock = {
      lockFile = ./frece-d4071c6c852e68dda82b7ab0bfb0f141b39d4484/Cargo.lock;
      outputHashes = { };
    };
  };
  guiscrcpy = {
    pname = "guiscrcpy";
    version = "44da9572c84d16345cae776e0a81812779c5e0ee";
    src = fetchFromGitHub ({
      owner = "srevinsaju";
      repo = "guiscrcpy";
      rev = "44da9572c84d16345cae776e0a81812779c5e0ee";
      fetchSubmodules = false;
      sha256 = "sha256-6KjyHc5KuzVhMnmIBvTWbryFFoSNemDL9CpVXbk3CoM=";
    });
  };
  ibus = {
    pname = "ibus";
    version = "675b94f63a2bce5554c9bb28a03462ed70933bec";
    src = fetchFromGitHub ({
      owner = "ibus";
      repo = "ibus";
      rev = "675b94f63a2bce5554c9bb28a03462ed70933bec";
      fetchSubmodules = false;
      sha256 = "sha256-eATfAm9VoNDeYZqtuZrxaqRXrTfoSPCkaAelWaR/t8E=";
    });
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "f6406437969b8e40c5e529cad0055d894fad2c7a";
    src = fetchFromGitHub ({
      owner = "BambooEngine";
      repo = "ibus-bamboo";
      rev = "f6406437969b8e40c5e529cad0055d894fad2c7a";
      fetchSubmodules = false;
      sha256 = "sha256-w68I1a1mMEGgF4oCzs5TvYmXTdpQPJog/S42Dz519i4=";
    });
  };
  jibri = {
    pname = "jibri";
    version = "8.0-115-gddb146c";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jibri_8.0-115-gddb146c-1_all.deb";
      sha256 = "sha256-/FWaJwuf+d4AVPgYD6tYWeHy0cOjaUHnSiD/7DwjJsU=";
    };
  };
  jicofo = {
    pname = "jicofo";
    version = "1.0-838";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jicofo_1.0-838-1_all.deb";
      sha256 = "sha256-V47zH8Cj04hqsi7pWW91ArCY/NSf5Sur8X6UvKf4744=";
    };
  };
  jitsi-meet = {
    pname = "jitsi-meet";
    version = "1.0.5724";
    src = fetchurl {
      url = "https://download.jitsi.org/jitsi-meet/src/jitsi-meet-1.0.5724.tar.bz2";
      sha256 = "sha256-0Y9pc+o4V2O2zTXIEzcrkQ/R//FarEdMCnNBk4k/H80=";
    };
  };
  jitsi-meet-prosody = {
    pname = "jitsi-meet-prosody";
    version = "1.0.5724";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-meet-prosody_1.0.5724-1_all.deb";
      sha256 = "sha256-XiWoGNAMmfgezl6BITJnItDkNs5B6pKkTJAWw1O3Jl4=";
    };
  };
  jitsi-videobridge2 = {
    pname = "jitsi-videobridge2";
    version = "2.1-601-g28cdd301";
    src = fetchurl {
      url = "https://download.jitsi.org/unstable/jitsi-videobridge2_2.1-601-g28cdd301-1_all.deb";
      sha256 = "sha256-3CeuaJd7TS+4Wq4n3thzKDdjubGA7n/lx8EL6qf+Bqs=";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "df15a7b78e929203f4de46348b25f3630ac079c1";
    src = fetchFromGitHub ({
      owner = "xinhaoyuan";
      repo = "layout-machi";
      rev = "df15a7b78e929203f4de46348b25f3630ac079c1";
      fetchSubmodules = false;
      sha256 = "sha256-DHQdWkQTztO/YBh6F2LzfbfK2bHpklhXnAkuw3fAZWM=";
    });
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
      sha256 = "sha256-Fok8OPP9dWjFyIVWUud+UDLiG/lUBNisuCcI0ipjHi4=";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchFromGitHub ({
      owner = "benhoyt";
      repo = "inih";
      rev = "r53";
      fetchSubmodules = false;
      sha256 = "sha256-hi29V40q3c3IvPH7eH3q3z1PiNN59Y0zMhgSroUsDjc=";
    });
  };
  light = {
    pname = "light";
    version = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
    src = fetchFromGitHub ({
      owner = "haikarainen";
      repo = "light";
      rev = "33f2316e5512762a5a33a62c78db7a435d9fec9b";
      fetchSubmodules = false;
      sha256 = "sha256-d8iBxfHkryy5lM5myWPo0a3zgUZQrklYazCSCyKKDGs=";
    });
  };
  lightcord = {
    pname = "lightcord";
    version = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
    src = fetchFromGitHub ({
      owner = "Lightcord";
      repo = "Lightcord";
      rev = "39fc7f28937029dc7270c0ec2bac11c0b467113c";
      fetchSubmodules = false;
      sha256 = "sha256-BXf8HDzEcTnExwAW6ddjyDc+G0iDitvXV7kVp0Btbg0=";
    });
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchFromGitHub ({
      owner = "RMTT";
      repo = "lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      sha256 = "sha256-Kn0ozckmgxs19TmCuSChdiYMch92eif7DTEK+UoBtjw=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "97.0.1072.41";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_97.0.1072.41-1_amd64.deb";
      sha256 = "sha256-5vFTdjwFteB/umTlhhElkY43LwCSzuZEV1cBoyXEbhc=";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "98.0.1100.3";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_98.0.1100.3-1_amd64.deb";
      sha256 = "sha256-CHFFLqQ0wO/gI77myPDkDX2wGcD4nXhWvy7BOPUOMw8=";
    };
  };
  minecraft-better-beds-1_16 = {
    pname = "minecraft-better-beds-1_16";
    version = "1.1.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/kKwy3HU9/versions/1.1.0/betterbeds-1.1.0.jar";
      sha256 = "sha256-cHZpq8SS3ffruSQ7Jn07mVBLGRb8zNz6qTj+WGitVds=";
    };
    modId = "kKwy3HU9";
    mcVer = "1.16";
  };
  minecraft-better-beds-1_17 = {
    pname = "minecraft-better-beds-1_17";
    version = "1.2.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/kKwy3HU9/versions/1.2.0/betterbeds-1.2.0.jar";
      sha256 = "sha256-ePkc4oTD0SGFD7qnzKSgHrW9fPoDMpni8euR8aowPA8=";
    };
    modId = "kKwy3HU9";
    mcVer = "1.16";
  };
  minecraft-cull-leaves-1_16 = {
    pname = "minecraft-cull-leaves-1_16";
    version = "2.0.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/GNxdLCoP/versions/2.0.0/cullleaves-2.0.0.jar";
      sha256 = "sha256-1vqwrorAl8YSNBxDnQOWK4tZb5LEaeCymyUGUtDLs4U=";
    };
    modId = "GNxdLCoP";
    mcVer = "1.16";
  };
  minecraft-cull-leaves-1_16_1 = {
    pname = "minecraft-cull-leaves-1_16_1";
    version = "2.1.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/GNxdLCoP/versions/2.1.0/cullleaves-2.1.0.jar";
      sha256 = "sha256-x6GwaiYH9GetsM4tdw8lIuoI0/ls2MACXrNA27HT2BM=";
    };
    modId = "GNxdLCoP";
    mcVer = "1.16.1";
  };
  minecraft-cull-leaves-1_17 = {
    pname = "minecraft-cull-leaves-1_17";
    version = "2.3.2";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/GNxdLCoP/versions/2.3.2/cullleaves-2.3.2.jar";
      sha256 = "sha256-tNi43VJa/tLpKcsSEhIjYim6pYopTlBRCy3zdtNC6xQ=";
    };
    modId = "GNxdLCoP";
    mcVer = "1.17";
  };
  minecraft-fabric-api-1_14 = {
    pname = "minecraft-fabric-api-1_14";
    version = "0.2.7+build.127";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.2.7+build.127/fabric-0.2.7+build.127.jar";
      sha256 = "sha256-Uv//C6GCzlwB9nVHSd+QcT3w272pHoPKBdevrdLvnpg=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.14";
  };
  minecraft-fabric-api-1_14_1 = {
    pname = "minecraft-fabric-api-1_14_1";
    version = "0.3.0-pre+build.157a";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.3.0-pre+build.157a/fabric-api-0.3.0-pre+build.157a.jar";
      sha256 = "sha256-L7y7Lj7izi3nEwjG1tJVziOirIgay8kwqDamgYkN/50=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.14.1";
  };
  minecraft-fabric-api-1_14_2 = {
    pname = "minecraft-fabric-api-1_14_2";
    version = "0.3.0+build.185";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.3.0+build.185/fabric-api-0.3.0+build.185.jar";
      sha256 = "sha256-V5YjA7QYTOUAwuyQuFyFtJXV0L35wvD4Bv/IKBVXkyg=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.14.2";
  };
  minecraft-fabric-api-1_14_3 = {
    pname = "minecraft-fabric-api-1_14_3";
    version = "0.3.0+build.198";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.3.0+build.198/fabric-api-0.3.0+build.198.jar";
      sha256 = "sha256-p7AQHjJxLhIohG/jJMawwDfuBREJFk0K2iup2Z+Mowc=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.14.3";
  };
  minecraft-fabric-api-1_14_4 = {
    pname = "minecraft-fabric-api-1_14_4";
    version = "0.28.5+1.14";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.28.5+1.14/fabric-api-0.28.5+1.14.jar";
      sha256 = "sha256-9emDhUvdp3Q2KCMc9I7APZBD7il+TCAVh4ALkWP4sK0=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.14.4";
  };
  minecraft-fabric-api-1_15 = {
    pname = "minecraft-fabric-api-1_15";
    version = "0.4.24+build.279-1.15";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.4.24+build.279-1.15/fabric-api-0.4.24+build.279-1.15.jar";
      sha256 = "sha256-x6Xe5JD8VdWoieJoHz1J0N/sNtyqPC34MR/0jkyJDBY=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.15";
  };
  minecraft-fabric-api-1_15_1 = {
    pname = "minecraft-fabric-api-1_15_1";
    version = "0.4.27+build.286-1.15";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.4.27+build.286-1.15/fabric-api-0.4.27+build.286-1.15.jar";
      sha256 = "sha256-BDrxap1aEsbQRTxRSYEBvmYTYxwiPXwvR6lmqLIiSf4=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16.1";
  };
  minecraft-fabric-api-1_15_2 = {
    pname = "minecraft-fabric-api-1_15_2";
    version = "0.28.5+1.15";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.28.5+1.15/fabric-api-0.28.5+1.15.jar";
      sha256 = "sha256-lnC0VgfSlEoeSOSSw7QPI9WshxlB8I19AfHK2g53wKo=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.15.2";
  };
  minecraft-fabric-api-1_16 = {
    pname = "minecraft-fabric-api-1_16";
    version = "0.13.1+build.370-1.16";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.13.1+build.370-1.16/fabric-api-0.13.1+build.370-1.16.jar";
      sha256 = "sha256-sVrBUgP+F7/aHeL1vL6zNJ5LedMluhtv/LF94A82+ZI=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16";
  };
  minecraft-fabric-api-1_16_1 = {
    pname = "minecraft-fabric-api-1_16_1";
    version = "0.18.0+build.387-1.16.1";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.18.0+build.387-1.16.1/fabric-api-0.18.0+build.387-1.16.1.jar";
      sha256 = "sha256-7SdIJd07EGoN4EtfxGhpJ7QBig3khIT1b2TId5HtTbs=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16.1";
  };
  minecraft-fabric-api-1_16_2 = {
    pname = "minecraft-fabric-api-1_16_2";
    version = "0.20.1+build.401-1.16";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.20.1+build.401-1.16/fabric-api-0.20.1+build.401-1.16.jar";
      sha256 = "sha256-+z9AlmYmqG7EAQzuxHFAqd7FLEaMTDJEQQkbAk4cu8o=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16.2";
  };
  minecraft-fabric-api-1_16_3 = {
    pname = "minecraft-fabric-api-1_16_3";
    version = "0.25.0+build.415-1.16";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.25.0+build.415-1.16/fabric-api-0.25.0+build.415-1.16.jar";
      sha256 = "sha256-5+oIAqKmB/S7OwiddYHyV0fjgurwfLearibtXE37x1I=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16.3";
  };
  minecraft-fabric-api-1_16_4 = {
    pname = "minecraft-fabric-api-1_16_4";
    version = "0.29.3+1.16";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.29.3+1.16/fabric-api-0.29.3+1.16.jar";
      sha256 = "sha256-PbzOgbUZF9GewfyVyFcWMEJ58XkIqa4t76+g8/+t8Q0=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16.4";
  };
  minecraft-fabric-api-1_16_5 = {
    pname = "minecraft-fabric-api-1_16_5";
    version = "0.42.0+1.16";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.42.0+1.16/fabric-api-0.42.0+1.16.jar";
      sha256 = "sha256-PfjdUD81qgrJ+ritn5o2n9/QsatUSvGaPWJtlI+0WGw=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.16.5";
  };
  minecraft-fabric-api-1_17 = {
    pname = "minecraft-fabric-api-1_17";
    version = "0.36.0+1.17";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.36.0+1.17/fabric-api-0.36.0+1.17.jar";
      sha256 = "sha256-hub8Ijb522iIFeASD2Hppa3mrqjDy8qwQv6rvt3EsTM=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.17";
  };
  minecraft-fabric-api-1_17_1 = {
    pname = "minecraft-fabric-api-1_17_1";
    version = "0.45.0+1.17";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.45.0+1.17/fabric-api-0.45.0+1.17.jar";
      sha256 = "sha256-Tyyi3hmvZV3+t/cQWcn4UZNvq78cyPVxakGKHTebZGs=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.17.1";
  };
  minecraft-fabric-api-1_18 = {
    pname = "minecraft-fabric-api-1_18";
    version = "0.44.0+1.18";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.44.0+1.18/fabric-api-0.44.0+1.18.jar";
      sha256 = "sha256-ZCByRV30DF6J3XG7wAL48E4uQZ2BvY80ImocIOuRlVY=";
    };
    modId = "P7dR8mSH";
    mcVer = "1.18";
  };
  minecraft-ferritecore-1_16_5 = {
    pname = "minecraft-ferritecore-1_16_5";
    version = "2.1.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/uXXizFIs/versions/2.1.0/ferritecore-2.1.0-fabric.jar";
      sha256 = "sha256-FyTpDH5lFOKYwQy6Ynn/4ddhCxU8clGHBrDndUs3KXE=";
    };
    modId = "uXXizFIs";
    mcVer = "1.16.5";
  };
  minecraft-ferritecore-1_17 = {
    pname = "minecraft-ferritecore-1_17";
    version = "3.0.1";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/uXXizFIs/versions/3.0.1/ferritecore-3.0.1-fabric.jar";
      sha256 = "sha256-wqk2B+dcAupiZ73IfBPHxBXxCZw7x3gfhB0pqsq6uYo=";
    };
    modId = "uXXizFIs";
    mcVer = "1.17";
  };
  minecraft-ferritecore-1_17_1 = {
    pname = "minecraft-ferritecore-1_17_1";
    version = "3.1.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/uXXizFIs/versions/3.1.0/ferritecore-3.1.0-fabric.jar";
      sha256 = "sha256-DZdL1vkQBYaaVQokws5UOMe/oZmnJnK/SnCcCKMDRzs=";
    };
    modId = "uXXizFIs";
    mcVer = "1.17.1";
  };
  minecraft-ferritecore-1_18 = {
    pname = "minecraft-ferritecore-1_18";
    version = "4.0.0";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/uXXizFIs/versions/4.0.0/ferritecore-4.0.0-fabric.jar";
      sha256 = "sha256-YK0d0+tZWybchXH7hhCG+DV1268K+rpPATQBTK6DBMo=";
    };
    modId = "uXXizFIs";
    mcVer = "1.18";
  };
  minecraft-krypton-1_16_5 = {
    pname = "minecraft-krypton-1_16_5";
    version = "0.1.2";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.2/krypton-0.1.2.jar";
      sha256 = "sha256-U/i8qX6qtznjjtDaC8fTBT8RQ9sozwfVjHLMlUVrB5g=";
    };
    modId = "fQEb0iXm";
    mcVer = "1.16.5";
  };
  minecraft-krypton-1_17 = {
    pname = "minecraft-krypton-1_17";
    version = "0.1.3";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.3/krypton-0.1.3.jar";
      sha256 = "sha256-BLi6bGzWVaeMzoFNZXSj8zPUGsxIgb2wo05oIkzI4kU=";
    };
    modId = "fQEb0iXm";
    mcVer = "1.17";
  };
  minecraft-krypton-1_17_1 = {
    pname = "minecraft-krypton-1_17_1";
    version = "0.1.4";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.4/krypton-0.1.4.jar";
      sha256 = "sha256-7FLzkVjDteRAAc+sNHaVLE5AH+jUdJYcrm9EFBwWcLY=";
    };
    modId = "fQEb0iXm";
    mcVer = "1.17.1";
  };
  minecraft-krypton-1_18_1 = {
    pname = "minecraft-krypton-1_18_1";
    version = "0.1.6";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.6/krypton-0.1.6.jar";
      sha256 = "sha256-0cKxJIMRUnmrsdRg0iy37vx/J5o3dvptc1lXwvnaK+Y=";
    };
    modId = "fQEb0iXm";
    mcVer = "1.18.1";
  };
  minecraft-lazydfu = {
    pname = "minecraft-lazydfu";
    version = "0.1.2";
    src = fetchurl {
      url = "https://github.com/astei/lazydfu/releases/download/0.1.2/lazydfu-0.1.2.jar";
      sha256 = "sha256-546xSS4gvNjJmNQULdQ3wlFzk8XQL1giBK2KODQedeg=";
    };
  };
  minecraft-lithium-1_16_5 = {
    pname = "minecraft-lithium-1_16_5";
    version = "0.6.6";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.16.5-0.6.6/lithium-fabric-mc1.16.5-0.6.6.jar";
      sha256 = "sha256-kGe0VQn8MCPXa/+FrQMO8B0w5an7/ngV/2Zq0xu6TSg=";
    };
    modId = "gvQqBUqZ";
    mcVer = "1.16.5";
  };
  minecraft-lithium-1_17_1 = {
    pname = "minecraft-lithium-1_17_1";
    version = "0.7.5";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17.1-0.7.5/lithium-fabric-mc1.17.1-0.7.5.jar";
      sha256 = "sha256-HADtQ51u6ZBqHS3q9wZeOYAz96E2vFPSmL4sxjYoMhA=";
    };
    modId = "gvQqBUqZ";
    mcVer = "1.17.1";
  };
  minecraft-lithium-1_18 = {
    pname = "minecraft-lithium-1_18";
    version = "0.7.6-rc1";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18-0.7.6-rc1/lithium-fabric-mc1.18-0.7.6-rc1.jar";
      sha256 = "sha256-dggI0EBWNh8r20zqmEwtAcKrgQwhhhPqtbWBdOcdt2c=";
    };
    modId = "gvQqBUqZ";
    mcVer = "1.18";
  };
  minecraft-lithium-1_18_1 = {
    pname = "minecraft-lithium-1_18_1";
    version = "0.7.6";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18.1-0.7.6/lithium-fabric-mc1.18.1-0.7.6.jar";
      sha256 = "sha256-x1H0QnqGnHZ+42qofrVHcBQ8FAjo+FyXiWSjU96Mgbs=";
    };
    modId = "gvQqBUqZ";
    mcVer = "1.18.1";
  };
  minecraft-starlight-fabric-1_17 = {
    pname = "minecraft-starlight-fabric-1_17";
    version = "1.0.0+fabric.73f6d37";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight%201.0.0%201.17.x/starlight-1.0.0+fabric.73f6d37.jar";
      sha256 = "sha256-oLJ282+JieNpThs2ULghn9KTSTYDXlY8cZ4Y4niC2Ow=";
    };
    modId = "H8CaAYZC";
    mcVer = "1.17";
  };
  minecraft-starlight-fabric-1_18 = {
    pname = "minecraft-starlight-fabric-1_18";
    version = "1.0.0+fabric.d0a3220";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight%201.0.0%201.18.x/starlight-1.0.0+fabric.d0a3220.jar";
      sha256 = "sha256-QdFnvpR5VWNRvxh1h8/C5QFds4BT0VO6sYhBWEiNaS8=";
    };
    modId = "H8CaAYZC";
    mcVer = "1.18";
  };
  minecraft-starlight-forge-1_17_1 = {
    pname = "minecraft-starlight-forge-1_17_1";
    version = "1.0.0+forge.5d16647";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/iRfIGC1s/versions/Starlight%201.0.0%201.17.x/starlight-1.0.0+forge.5d16647.jar";
      sha256 = "sha256-7pPXm47HUCpfBMRpg5D4HmRl2lM7PpQtsWmLL9i91Yw=";
    };
    modId = "iRfIGC1s";
    mcVer = "1.17.1";
  };
  minecraft-starlight-forge-1_18_1 = {
    pname = "minecraft-starlight-forge-1_18_1";
    version = "1.0.0+forge.4fd2e63";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/iRfIGC1s/versions/Starlight%201.0.0%201.18.1+/starlight-1.0.0+forge.4fd2e63.jar";
      sha256 = "sha256-RmqCPBMTDbJaDYYfL10pFWUBlitr0VZoSX5hbdkQ8UQ=";
    };
    modId = "iRfIGC1s";
    mcVer = "1.18.1";
  };
  minecraft-wayland = {
    pname = "minecraft-wayland";
    version = "88eba707930eb98715fd9fb5d10d3ff02a535abf";
    src = fetchFromGitHub ({
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "88eba707930eb98715fd9fb5d10d3ff02a535abf";
      fetchSubmodules = false;
      sha256 = "sha256-NzXAFtQLvPWdQAq+xTBbDMOyGvs7MKyiJTP+VL8HpRg=";
    });
  };
  netdata = {
    pname = "netdata";
    version = "1.32.1";
    src = fetchurl {
      url = "https://github.com/netdata/netdata/archive/refs/tags/v1.32.1.tar.gz";
      sha256 = "sha256-K1RwyhOzp8l5T2sg0UVGzXAYGA/miKt2iC2VuKWTufY=";
    };
  };
  netdata-go-d-plugin = {
    pname = "netdata-go-d-plugin";
    version = "0.31.0";
    src = fetchurl {
      url = "https://github.com/netdata/go.d.plugin/archive/refs/tags/v0.31.0.tar.gz";
      sha256 = "sha256-XTn2Vb04/NDvCUq5sM/XWNAaw+oud/lMWuQM4a+ijsA=";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchFromGitHub ({
      owner = "Ma27";
      repo = "nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      sha256 = "sha256-TWgo56l+FBXssOYWlAfJ5j4pOHNmontOEolcGdihIJs=";
    });
  };
  ntfs2btrfs = {
    pname = "ntfs2btrfs";
    version = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "ntfs2btrfs";
      rev = "f97247434ecda2cd2c451da5c73c3af98dfaea35";
      fetchSubmodules = false;
      sha256 = "sha256-ZJmnUU81hg34JHkA82BfapFGqKrhqFk6wCM2eO2RaVs=";
    });
  };
  nwg-drawer = {
    pname = "nwg-drawer";
    version = "94c94b8b1e125c00c386d52c738b01dded7d4529";
    src = fetchFromGitHub ({
      owner = "nwg-piotr";
      repo = "nwg-drawer";
      rev = "94c94b8b1e125c00c386d52c738b01dded7d4529";
      fetchSubmodules = false;
      sha256 = "sha256-EaMTx5BqhhMc6W+k2PkWG5d1LJ0OKpS9mjWUW6SMyKs=";
    });
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
      sha256 = "sha256-MAxQkdR40YUDl7z0OYbuwiueOoB2JuYikIu11CqiAto=";
    };
  };
  ouch = {
    pname = "ouch";
    version = "308b8f7e906c57d8da334ae6395aa15ecbdfb2d8";
    src = fetchFromGitHub ({
      owner = "ouch-org";
      repo = "ouch";
      rev = "308b8f7e906c57d8da334ae6395aa15ecbdfb2d8";
      fetchSubmodules = false;
      sha256 = "sha256-65yz5o/sITdk3x9gqHPvcMEDsImrEObJkg/cc3kCD9s=";
    });
    cargoLock = {
      lockFile = ./ouch-308b8f7e906c57d8da334ae6395aa15ecbdfb2d8/Cargo.lock;
      outputHashes = { };
    };
  };
  paper = {
    pname = "paper";
    version = "35ecb75c6776615f1db5dfb861fbe407263d8057";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper";
      rev = "35ecb75c6776615f1db5dfb861fbe407263d8057";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D0VMUZ7QN4xTcTBulzSlt7IvjRxPYFiTs1AcuhNKrek=";
    };
    cargoLock = {
      lockFile = ./paper-35ecb75c6776615f1db5dfb861fbe407263d8057/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "sha256-y61EWKr5qD9OFrMVQs9SVyLCqq5lOwLXCAo2w0AYt7M=";
      };
    };
  };
  papermc-1_10_2 = {
    pname = "papermc-1_10_2";
    version = "918";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.10.2/builds/918/downloads/paper-1.10.2-918.jar";
      sha256 = "sha256-gzVNJKIrYmXnbAibPRelaKu0RsDM0SwkUvXhSEErFsI=";
    };
    mcVer = "1.10.2";
  };
  papermc-1_11_2 = {
    pname = "papermc-1_11_2";
    version = "1106";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.11.2/builds/1106/downloads/paper-1.11.2-1106.jar";
      sha256 = "sha256-PQ9A7B+WMN/br6YmzCDCZtf7kPwiWD3BuZXn+/t2gw0=";
    };
    mcVer = "1.11.2";
  };
  papermc-1_12 = {
    pname = "papermc-1_12";
    version = "1169";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.12/builds/1169/downloads/paper-1.12-1169.jar";
      sha256 = "sha256-Hn6Iou1vK3D6P27GYRNzRYxdcrKocH5gkh32AceR5g4=";
    };
    mcVer = "1.12";
  };
  papermc-1_12_1 = {
    pname = "papermc-1_12_1";
    version = "1204";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.12.1/builds/1204/downloads/paper-1.12.1-1204.jar";
      sha256 = "sha256-26IhnWdK2F5O8sQZMdNLb6S+daiHlz7KryhnJ6A4Eto=";
    };
    mcVer = "1.12.1";
  };
  papermc-1_12_2 = {
    pname = "papermc-1_12_2";
    version = "1620";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.12.2/builds/1620/downloads/paper-1.12.2-1620.jar";
      sha256 = "sha256-OiBBgH9JLc3DTrsySih0FJRuPgXsPfb9A/W199mvwhA=";
    };
    mcVer = "1.12.2";
  };
  papermc-1_13 = {
    pname = "papermc-1_13";
    version = "173";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13/builds/173/downloads/paper-1.13-173.jar";
      sha256 = "sha256-ANuC0hQkLJNFJm1E/40RqOhXoaAu33y1/MLR2XMoMSk=";
    };
    mcVer = "1.13";
  };
  papermc-1_13-pre7 = {
    pname = "papermc-1_13-pre7";
    version = "12";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13-pre7/builds/12/downloads/paper-1.13-pre7-12.jar";
      sha256 = "sha256-jCxNvDooQr6EVLTEswYma8Yi4ttoEjNVj+34IwgAlAw=";
    };
    mcVer = "1.13-pre7";
  };
  papermc-1_13_1 = {
    pname = "papermc-1_13_1";
    version = "386";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13.1/builds/386/downloads/paper-1.13.1-386.jar";
      sha256 = "sha256-ZjdAHYfQ9dtarukNcQP1LF4bqva21GQ6V5PnsCtXdcs=";
    };
    mcVer = "1.13.1";
  };
  papermc-1_13_2 = {
    pname = "papermc-1_13_2";
    version = "657";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.13.2/builds/657/downloads/paper-1.13.2-657.jar";
      sha256 = "sha256-Eego0FZat2oKDhgMBWNkqV3kSVjP1qavP5sdxwsD6c0=";
    };
    mcVer = "1.13.2";
  };
  papermc-1_14 = {
    pname = "papermc-1_14";
    version = "17";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14/builds/17/downloads/paper-1.14-17.jar";
      sha256 = "sha256-M4vnf1I5xEz/P4D1wQe15hrEj7OTSLznJJMDIJIBByo=";
    };
    mcVer = "1.14";
  };
  papermc-1_14_1 = {
    pname = "papermc-1_14_1";
    version = "50";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.1/builds/50/downloads/paper-1.14.1-50.jar";
      sha256 = "sha256-K8+AF0hcxBs+ctqnKFpG8mqF0FW51ji8mgf3djIWitc=";
    };
    mcVer = "1.14.1";
  };
  papermc-1_14_2 = {
    pname = "papermc-1_14_2";
    version = "107";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.2/builds/107/downloads/paper-1.14.2-107.jar";
      sha256 = "sha256-EgNOV44BTrNp4pKfNyW9QJhYv5QSjkbR8obVvjbDyw4=";
    };
    mcVer = "1.14.2";
  };
  papermc-1_14_3 = {
    pname = "papermc-1_14_3";
    version = "134";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.3/builds/134/downloads/paper-1.14.3-134.jar";
      sha256 = "sha256-ttLYrGfWhRQWl6jOzZnEe69gSQAAfrDicP1uqGy7xUA=";
    };
    mcVer = "1.14.3";
  };
  papermc-1_14_4 = {
    pname = "papermc-1_14_4";
    version = "245";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.14.4/builds/245/downloads/paper-1.14.4-245.jar";
      sha256 = "sha256-vY7FzbIjcNN4FqbeJnmN89Kw1vnHyWyIykWhMD/qUOg=";
    };
    mcVer = "1.14.4";
  };
  papermc-1_15 = {
    pname = "papermc-1_15";
    version = "21";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.15/builds/21/downloads/paper-1.15-21.jar";
      sha256 = "sha256-i3JsDetsOiZdZ5o9OiwPjlJD+8bdz8r0LiQgnLH4KbQ=";
    };
    mcVer = "1.15";
  };
  papermc-1_15_1 = {
    pname = "papermc-1_15_1";
    version = "62";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.15.1/builds/62/downloads/paper-1.15.1-62.jar";
      sha256 = "sha256-IqehnzeNuO35LNulfZHO6n5PpkcLZ35rvlfo9+HZpN0=";
    };
    mcVer = "1.15.1";
  };
  papermc-1_15_2 = {
    pname = "papermc-1_15_2";
    version = "393";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.15.2/builds/393/downloads/paper-1.15.2-393.jar";
      sha256 = "sha256-vS3W8sxInPniu4AMtPttY+nSk5RdOsELCd2cYJj6nzQ=";
    };
    mcVer = "1.15.2";
  };
  papermc-1_16_1 = {
    pname = "papermc-1_16_1";
    version = "138";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.1/builds/138/downloads/paper-1.16.1-138.jar";
      sha256 = "sha256-kpVZuh38beKQThcon7PRrJXwq0jHVAz1uMLwVf6p1Zw=";
    };
    mcVer = "1.16.1";
  };
  papermc-1_16_2 = {
    pname = "papermc-1_16_2";
    version = "189";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.2/builds/189/downloads/paper-1.16.2-189.jar";
      sha256 = "sha256-5eEFF9qqm9bVSooNIthm4x2nwbR8ueQl/6rCNv3nXsk=";
    };
    mcVer = "1.16.2";
  };
  papermc-1_16_3 = {
    pname = "papermc-1_16_3";
    version = "253";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.3/builds/253/downloads/paper-1.16.3-253.jar";
      sha256 = "sha256-lAMD7l9bzAg3fjiOocHaoQnBrIxNGJ3GfeEQaFPy/CM=";
    };
    mcVer = "1.16.3";
  };
  papermc-1_16_4 = {
    pname = "papermc-1_16_4";
    version = "416";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/416/downloads/paper-1.16.4-416.jar";
      sha256 = "sha256-ljJo7VZKx9LsB2Rj6SH/oJVwI19Ye70aTZGiPKQmS2Y=";
    };
    mcVer = "1.16.4";
  };
  papermc-1_16_5 = {
    pname = "papermc-1_16_5";
    version = "794";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/794/downloads/paper-1.16.5-794.jar";
      sha256 = "sha256-5n2khR0IzeN4qyuJvliEkjjDAzUe0kghgamcLCtIknY=";
    };
    mcVer = "1.16.5";
  };
  papermc-1_17 = {
    pname = "papermc-1_17";
    version = "79";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.17/builds/79/downloads/paper-1.17-79.jar";
      sha256 = "sha256-dgqTuUpY1hm9ZH1xr4RohhfQRE0itxZQC8azQ4WNyHE=";
    };
    mcVer = "1.17";
  };
  papermc-1_17_1 = {
    pname = "papermc-1_17_1";
    version = "403";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/403/downloads/paper-1.17.1-403.jar";
      sha256 = "sha256-0og9skctiS+3OwxCwOIO1M3wmlXQjiyk6iNCkf1D7yw=";
    };
    mcVer = "1.17.1";
  };
  papermc-1_18 = {
    pname = "papermc-1_18";
    version = "66";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.18/builds/66/downloads/paper-1.18-66.jar";
      sha256 = "sha256-PJlfINrk5OIdVVT6yVegqKXIW9W/NJFfrEtPFuDvEBs=";
    };
    mcVer = "1.18";
  };
  papermc-1_18_1 = {
    pname = "papermc-1_18_1";
    version = "105";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/105/downloads/paper-1.18.1-105.jar";
      sha256 = "sha256-3gIxjY/ljGtjdAm6QuYO3p6yuNQZ7s11EYD9643d6+Y=";
    };
    mcVer = "1.18.1";
  };
  papermc-1_8_8 = {
    pname = "papermc-1_8_8";
    version = "445";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar";
      sha256 = "sha256-f/bSzsZx7w2Vs3I7XJKJARj7iC1zt/j6CizTHZfFX4Y=";
    };
    mcVer = "1.8.8";
  };
  papermc-1_9_4 = {
    pname = "papermc-1_9_4";
    version = "775";
    src = fetchurl {
      url = "https://papermc.io/api/v2/projects/paper/versions/1.9.4/builds/775/downloads/paper-1.9.4-775.jar";
      sha256 = "sha256-FaWCHd6sxZZDLD+/JCYqLSZPVWBg7Nbxg4+wGrVimoE=";
    };
    mcVer = "1.9.4";
  };
  picom = {
    pname = "picom";
    version = "31e58712ec11b198340ae217d33a73d8ac73b7fe";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "31e58712ec11b198340ae217d33a73d8ac73b7fe";
      fetchSubmodules = false;
      sha256 = "sha256-VBnIzisg/7Xetd/AWVHlnaWXlxX+wqeYTpstO6+T5cE=";
    });
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchFromGitHub ({
      owner = "adi1090x";
      repo = "plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
    });
  };
  pmbootstrap = {
    pname = "pmbootstrap";
    version = "1.40.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pmbootstrap/pmbootstrap-1.40.0.tar.gz";
      sha256 = "sha256-b/9NEURp42d/j/Fk8NUS0ZAG99q56eg0pEU/xkFnvrM=";
    };
  };
  pmbootstrap-test = {
    pname = "pmbootstrap-test";
    version = "8a14d366ef6fcd2e5b0a9eb86763960c578260a2";
    src = fetchgit {
      url = "https://gitlab.com/postmarketOS/pmbootstrap";
      rev = "8a14d366ef6fcd2e5b0a9eb86763960c578260a2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-8Mb46phfxLKQ5D18wyHuIL04dZv1aJI1OVx5FUvMH2I=";
    };
  };
  pure = {
    pname = "pure";
    version = "90dc9cf908481cc155e1ce5611f684916523fc30";
    src = fetchFromGitHub ({
      owner = "sindresorhus";
      repo = "pure";
      rev = "90dc9cf908481cc155e1ce5611f684916523fc30";
      fetchSubmodules = false;
      sha256 = "sha256-nsmiP1RSG27WtwRJpTZvDi2CvUQExxdBs5my7T5TSKk=";
    });
  };
  pythonPackages-cfscrape = {
    pname = "pythonPackages-cfscrape";
    version = "e510962c608382bcef5de75033d60cc98cb9561d";
    src = fetchurl {
      url = "https://github.com/Anorov/cloudflare-scrape/archive/master.tar.gz";
      sha256 = "sha256-+pFN1Ts23Ggm6YZueyLdQaMJCfox/CRmMelzGvWRtEw=";
    };
  };
  pythonPackages-cmapy = {
    pname = "pythonPackages-cmapy";
    version = "0.6.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/c/cmapy/cmapy-0.6.6.tar.gz";
      sha256 = "sha256-y1KmswV8SaFG+wlkuDAvL7fWHf5q5t4amLY2qs6AUlU=";
    };
  };
  pythonPackages-mediapipe = {
    pname = "pythonPackages-mediapipe";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5f/188b509ab93e740f3fd8d9179de0ef9340852b48f1f5d671cd090a54996f/mediapipe-0.8.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl";
      sha256 = "sha256-qW1D06zrH8HnZiQoO5PC+8mK8z1HcZJxU9hmwyi8FZc=";
    };
  };
  pythonPackages-pySmartDL = {
    pname = "pythonPackages-pySmartDL";
    version = "b93df794e1e60017c42d9520ac097b6fd38c2e8b";
    src = fetchurl {
      url = "https://github.com/iTaybb/pySmartDL/archive/master.tar.gz";
      sha256 = "sha256-26TGmz9eIXm6epKUnvNDQymRBOC3TcpxCXFbhuVfVto=";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
      sha256 = "sha256-Wec9fic4lXT7gBY04D2EcfCb/gYoZcrYA/aMRWaA7WY=";
    };
  };
  quibble = {
    pname = "quibble";
    version = "f7ac6d55df73a35a730ea73045d9cd623180cb4b";
    src = fetchFromGitHub ({
      owner = "maharmstone";
      repo = "quibble";
      rev = "f7ac6d55df73a35a730ea73045d9cd623180cb4b";
      fetchSubmodules = false;
      sha256 = "sha256-YdXXPT/FlEEWDk8QrymQNFp0bj64E+0z7u0+edcLEhk=";
    });
  };
  rainfox = {
    pname = "rainfox";
    version = "d373dc136b805097f5092d02365a90327dc1de4a";
    src = fetchFromGitHub ({
      owner = "1280px";
      repo = "rainfox";
      rev = "d373dc136b805097f5092d02365a90327dc1de4a";
      fetchSubmodules = false;
      sha256 = "sha256-JX9sdVXjX38RVNUupktBinyGtAPCEj5YfJBg/N+wabw=";
    });
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchFromGitHub ({
      owner = "minus7";
      repo = "redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      sha256 = "sha256-pyR7xNdi/83NSoC2WIrX8U+A6nU+vZBlePLXrQZnc1k=";
    });
  };
  retroarch = {
    pname = "retroarch";
    version = "916a3fd157a489ac9dbe991ce0e57f54c8f0cc4b";
    src = fetchFromGitHub ({
      owner = "libretro";
      repo = "retroarch";
      rev = "916a3fd157a489ac9dbe991ce0e57f54c8f0cc4b";
      fetchSubmodules = false;
      sha256 = "sha256-4IG8GhIJIs00SuOOLMKgxB8BQjpmPAFj2zx0QnFQMrc=";
    });
  };
  rofi-wayland = {
    pname = "rofi-wayland";
    version = "07c801cd2d7a261173030e6297d4014dcaa998b2";
    src = fetchFromGitHub ({
      owner = "lbonn";
      repo = "rofi";
      rev = "07c801cd2d7a261173030e6297d4014dcaa998b2";
      fetchSubmodules = true;
      sha256 = "sha256-96scjlii4pvq3DYRpWk2rQxS0tXo5XeWhJp65Z8lkD0=";
    });
  };
  rustdesk = {
    pname = "rustdesk";
    version = "66e39b62a2fb6f1b2171bd12c4777d73d1bffaf3";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk";
      rev = "66e39b62a2fb6f1b2171bd12c4777d73d1bffaf3";
      fetchSubmodules = false;
      sha256 = "sha256-VYicD+zQrUaPlhaW8FgsQJ1dNMZ5NSNA3ErOSxQZHj0=";
    });
    cargoLock = {
      lockFile = ./rustdesk-66e39b62a2fb6f1b2171bd12c4777d73d1bffaf3/Cargo.lock;
      outputHashes = {
        "systray-0.4.1" = "sha256-p1PMr/8oS6zHx4+Ng4zCqt0xZ57cq3wAu6/agyWq5Jw=";
        "parity-tokio-ipc-0.7.3" = "sha256-Ji/q7RQDznFs+m4AHH1IEL1TMqqCtH4Z5DY6sjcu/T0=";
        "libappindicator-0.6.1" = "sha256-JGnnZrcwbh8WJ6+/4bYhfD3HvgF2C7XaaGb6TaMRWdw=";
        "cpal-0.13.4" = "sha256-Gs1cqYJP92Zy8Fnu3wGQ9+p5oIkCkOp9v++8ocFSNiU=";
        "sciter-rs-0.5.57" = "sha256-pF5Rwav78//oqDAv0Nhb7tawhSMnlSuy4sPUOfPd8NU=";
        "psutil-3.2.1" = "sha256-n3LTTDBCW+l0xKFGHdFHePlw998nO6G9K7PCWdukN/0=";
        "confy-0.4.1" = "sha256-5QwA4YfEEE6QqEEUJ3+C37UbUf88NYds38kIthVSo5Y=";
        "magnum-opus-0.4.0" = "sha256-GoCuStsQW/M6PEfdtbJ69ePNAL8bQ9HIJVopv+k93nY=";
        "rust-pulsectl-0.2.11" = "sha256-CZkvii6pQM5jaR9RK9HDrczxIxZwuahpdVM+UsRLw9s=";
      };
    };
  };
  rustdesk-server-oss = {
    pname = "rustdesk-server-oss";
    version = "2e539cf5bfc60b1463519de2566422464877992d";
    src = fetchFromGitHub ({
      owner = "rustdesk";
      repo = "rustdesk-server-demo";
      rev = "2e539cf5bfc60b1463519de2566422464877992d";
      fetchSubmodules = false;
      sha256 = "sha256-MMPmTEMYghf2A+rQF5pJaLTb2NyXpV3HKx20g7o/deg=";
    });
  };
  sddm = {
    pname = "sddm";
    version = "04242833b35748f06b569dc5c8130a66c823e154";
    src = fetchFromGitHub ({
      owner = "sddm";
      repo = "sddm";
      rev = "04242833b35748f06b569dc5c8130a66c823e154";
      fetchSubmodules = false;
      sha256 = "sha256-l7+4pHp3clabT7JO5uNUfAhVO7AbIxVpXMX35fwC2/U=";
    });
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchFromGitHub ({
      owner = "MarianArlt";
      repo = "sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      sha256 = "sha256-wxWsdRGC59YzDcSopDRzxg8TfjjmA3LHrdWjepTuzgw=";
    });
  };
  segue-ui-linux = {
    pname = "segue-ui-linux";
    version = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
    src = fetchFromGitHub ({
      owner = "mrbvrz";
      repo = "segoe-ui-linux";
      rev = "02f6e1e9290581e7fc9bf3beefc0ebc9ec8c1611";
      fetchSubmodules = false;
      sha256 = "sha256-zmR87N8loBtmi8qVH2kC0XSgydn8Sw570awYi/XAcuM=";
    });
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
      sha256 = "sha256-SHZHMCpqlrLH/3cEbIcnZg4lDQYl765bVO3v1o1D6hg=";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
      sha256 = "sha256-+JF3SyNi+6rEVIEg/Llqu0w/z8gqBbbLtP3cCl9Kqjo=";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
      sha256 = "sha256-8niJPk3hGfK1USIs9eoxZ6GlM4aZ7ZObmQj2Zomj+Go=";
    };
  };
  snui = {
    pname = "snui";
    version = "a5897d6406dcf501bbe4f29123c963c6f53dfbd8";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/snui";
      rev = "a5897d6406dcf501bbe4f29123c963c6f53dfbd8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gR1/FmqcQYxY6mdUUauKL4DxeuS23jJpm0EGOCglfrM=";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "cf6ce0e87703f78e5a98e10edd8761a3fef8b3ab";
    src = fetchFromGitHub ({
      owner = "khanhas";
      repo = "spicetify-cli";
      rev = "cf6ce0e87703f78e5a98e10edd8761a3fef8b3ab";
      fetchSubmodules = false;
      sha256 = "sha256-+itMF1ynIM5JSBWw2LnIzT9zIdNQ/A+4hTiGIFmBJVI=";
    });
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "1d9ef3902aa79659ce0a6884d0f1249f07174918";
    src = fetchFromGitHub ({
      owner = "morpheusthewhite";
      repo = "spicetify-themes";
      rev = "1d9ef3902aa79659ce0a6884d0f1249f07174918";
      fetchSubmodules = false;
      sha256 = "sha256-LzDn214UuN49u6iSry+EA9m5Fe03IGMFd+87ZKnvES4=";
    });
  };
  spotify = {
    pname = "spotify";
    version = "1.1.72.439.gc253025e";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_56.snap";
      sha256 = "sha256-GKQBMPMLlbBZp4YXKPxY03lOJvmsuitiIldg0aLh6RE=";
    };
  };
  spotifyd = {
    pname = "spotifyd";
    version = "603bcc4d802d2b8f45ac517c0513eb4096252d7b";
    src = fetchFromGitHub ({
      owner = "Spotifyd";
      repo = "spotifyd";
      rev = "603bcc4d802d2b8f45ac517c0513eb4096252d7b";
      fetchSubmodules = false;
      sha256 = "sha256-zOyRbeaC+wI0MgJeUksSzS9SR+folKAg6aCzc7mgONI=";
    });
    cargoLock = {
      lockFile = ./spotifyd-603bcc4d802d2b8f45ac517c0513eb4096252d7b/Cargo.lock;
      outputHashes = { };
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "c0b61756ee30f93d296efc32f018eaf5ace37fbe";
    src = fetchFromGitHub ({
      owner = "ChimeraOS";
      repo = "steamos-compositor-plus";
      rev = "c0b61756ee30f93d296efc32f018eaf5ace37fbe";
      fetchSubmodules = false;
      sha256 = "sha256-CybAPCUDHulW54x94F0ZRAnhrT4dK175X55ZPmgYxPc=";
    });
  };
  sway-borders = {
    pname = "sway-borders";
    version = "5f4162f449b19f6d198b365fc6d3dd0febc065e2";
    src = fetchFromGitHub ({
      owner = "fluix-dev";
      repo = "sway-borders";
      rev = "5f4162f449b19f6d198b365fc6d3dd0febc065e2";
      fetchSubmodules = false;
      sha256 = "sha256-gCdnim7excF11GEoni5YbIGTWSIx+wjHc8NO8lVNFts=";
    });
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
    src = fetchFromGitHub ({
      owner = "mortie";
      repo = "swaylock-effects";
      rev = "a8fc557b86e70f2f7a30ca9ff9b3124f89e7f204";
      fetchSubmodules = false;
      sha256 = "sha256-GN+cxzC11Dk1nN9wVWIyv+rCrg4yaHnCePRYS1c4JTk=";
    });
  };
  tailscale = {
    pname = "tailscale";
    version = "434af15a043f7d34612d68c655c835a2e3dd7ad5";
    src = fetchFromGitHub ({
      owner = "tailscale";
      repo = "tailscale";
      rev = "434af15a043f7d34612d68c655c835a2e3dd7ad5";
      fetchSubmodules = false;
      sha256 = "sha256-JVRR3Uh5OKoj74faLO9TVT/hnjtn3VX00L6mHJGzUIk=";
    });
  };
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "20c7e85e3d64602b87699c388185513e112a5a9c";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "20c7e85e3d64602b87699c388185513e112a5a9c";
      fetchSubmodules = false;
      sha256 = "sha256-XP874ciM4eBrT/rOGqwMzZQ27T0QJ3ggODHB5pIkZzU=";
    });
  };
  teams = {
    pname = "teams";
    version = "1.4.00.26453";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.26453_amd64.deb";
      sha256 = "sha256-7hW1d5Oqa3nM2nRNUjLaZwM1q9kxuuKgIPUEOhKauFk=";
    };
  };
  trackma = {
    pname = "trackma";
    version = "2422c23228efc9b72872b69f22f7d25c1d337264";
    src = fetchurl {
      url = "https://github.com/z411/trackma/archive/master.tar.gz";
      sha256 = "sha256-ML1pCEnK+DDHsUmFneqsHrSl05ZLHz1GPydPcurOFbY=";
    };
  };
  ulauncher = {
    pname = "ulauncher";
    version = "44735d8d4c2b4b8a8d28f95ab6a6c6d577c859e5";
    src = fetchFromGitHub ({
      owner = "Ulauncher";
      repo = "Ulauncher";
      rev = "44735d8d4c2b4b8a8d28f95ab6a6c6d577c859e5";
      fetchSubmodules = false;
      sha256 = "sha256-urChMTImmt1oETvIvgpp07TsYxUQ16WUNIxyWILOKqg=";
    });
  };
  ultimmc = {
    pname = "ultimmc";
    version = "66bb7105db93e0977bb64a59a12b001f780e0566";
    src = fetchFromGitHub ({
      owner = "AfoninZ";
      repo = "MultiMC5-Cracked";
      rev = "66bb7105db93e0977bb64a59a12b001f780e0566";
      fetchSubmodules = true;
      sha256 = "sha256-t/R3BBRy2orzUuh537xMPwORHmhQy4aGe96e77CVzZs=";
    });
  };
  uniemoji = {
    pname = "uniemoji";
    version = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
    src = fetchFromGitHub ({
      owner = "salty-horse";
      repo = "ibus-uniemoji";
      rev = "40e69ae550f74bd91fa0b87db4f2e303344fd7aa";
      fetchSubmodules = false;
      sha256 = "sha256-aIoAQu4KpaUnSGV8UwPUXzM91Hu9k9eaLj7oP1GRRAw=";
    });
  };
  vaultwarden = {
    pname = "vaultwarden";
    version = "1.23.1";
    src = fetchFromGitHub ({
      owner = "dani-garcia";
      repo = "vaultwarden";
      rev = "1.23.1";
      fetchSubmodules = false;
      sha256 = "sha256-UMeltpuGUPdB5j4NBxA6SuLUqzinrF8USCaJk9SjDJA=";
    });
    cargoLock = {
      lockFile = ./vaultwarden-1.23.1/Cargo.lock;
      outputHashes = {
        "rocket-0.5.0-dev" = "sha256-sZL6GtLrfDy0ePix2UxZTdpFQvvc0G/Q+7qbCLGknqY=";
        "job_scheduler-1.2.1" = "sha256-b0jIKAHVrQNdZdlq+5kfGAOsi8bHu20QDtQaWTuJYtU=";
        "devise-0.3.0" = "sha256-crnEOKK7FiuIs55mOKgNfb3mNzr3QLI0icPPuG+xKVI=";
      };
    };
  };
  vaultwarden-vault = {
    pname = "vaultwarden-vault";
    version = "2.25.0";
    src = fetchurl {
      url = "https://github.com/dani-garcia/bw_web_builds/releases/download/v2.25.0/bw_web_v2.25.0.tar.gz";
      sha256 = "sha256-0uxkHz/oHWl4MdzV7zRVKgkEqOkrl7Fd405TOf472gw=";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
      sha256 = "sha256-FxQy6ZBBjvmce7bCDLKpOs4ZTq37bO3U0Iu7U2RRxL4=";
    };
  };
  vimPlugins-yuck = {
    pname = "vimPlugins-yuck";
    version = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
    src = fetchFromGitHub ({
      owner = "elkowar";
      repo = "yuck.vim";
      rev = "6dc3da77c53820c32648cf67cbdbdfb6994f4e08";
      fetchSubmodules = false;
      sha256 = "sha256-lp7qJWkvelVfoLCyI0aAiajTC+0W1BzDhmtta7tnICE=";
    });
  };
  vscode-extensions-ActiveFileInStatusBar = {
    pname = "vscode-extensions-ActiveFileInStatusBar";
    version = "1.0.3";
    src = fetchurl {
      url = "https://RoscoP.gallery.vsassets.io/_apis/public/gallery/publisher/RoscoP/extension/ActiveFileInStatusBar/1.0.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-5GJODdKL8949a8KR2O7hGsRgAknfPyNEJ+9aiEYYemk=";
    };
    license = "mit";
  };
  vscode-extensions-Kotlin = {
    pname = "vscode-extensions-Kotlin";
    version = "1.7.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/mathiasfrohlich/Kotlin/1.7.1/file/mathiasfrohlich.Kotlin-1.7.1.vsix";
      sha256 = "sha256-I7ur5yZRaKYMCCXEAlWJ5RD61rQbK1vFX8Phk27J4gw=";
    };
    homepage = "https://github.com/mathiasfrohlich/vscode-kotlin";
    license = "asl20";
    description = "Kotlin language support for VS Code";
  };
  vscode-extensions-Material-theme = {
    pname = "vscode-extensions-Material-theme";
    version = "3.13.8";
    src = fetchurl {
      url = "https://open-vsx.org/api/zhuangtongfa/material-theme/3.13.8/file/zhuangtongfa.material-theme-3.13.8.vsix";
      sha256 = "sha256-+JoRByOdkBTbL5ZWJOdngeep/xvobNSHXg6XhlMjz9k=";
    };
    homepage = "https://github.com/Binaryify/OneDark-Pro";
    license = "mit";
    description = "Atom's iconic One Dark theme for Visual Studio Code";
  };
  vscode-extensions-astro = {
    pname = "vscode-extensions-astro";
    version = "0.8.5";
    src = fetchurl {
      url = "https://astro-build.gallery.vsassets.io/_apis/public/gallery/publisher/astro-build/extension/astro-vscode/0.8.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-xO6CPtZf+olM2wRZEbD+KrH1Alce92NJXF51QESHy8o=";
    };
    license = "mit";
  };
  vscode-extensions-awesome-flutter-snippets = {
    pname = "vscode-extensions-awesome-flutter-snippets";
    version = "3.0.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Nash/awesome-flutter-snippets/3.0.0/file/Nash.awesome-flutter-snippets-3.0.0.vsix";
      sha256 = "sha256-SyQ8dJ2M3RYJC1uf7gnDCMSa9i+t7k+uhR7M45gkgGU=";
    };
    homepage = "https://github.com/Neevash/awesome-flutter-snippets";
    license = "asl20";
    description = "Awesome Flutter Snippets is a collection snippets and shortcuts for commonly used Flutter functions and classes";
  };
  vscode-extensions-bracket-pair-colorizer-2 = {
    pname = "vscode-extensions-bracket-pair-colorizer-2";
    version = "0.1.4";
    src = fetchurl {
      url = "https://open-vsx.org/api/CoenraadS/bracket-pair-colorizer-2/0.1.4/file/CoenraadS.bracket-pair-colorizer-2-0.1.4.vsix";
      sha256 = "sha256-NsxiPw689RTwfwcCoxflDancEeh0Ih/p45PGS2qm6Ck=";
    };
    homepage = "https://github.com/CoenraadS/Bracket-Pair-Colorizer-2";
    license = "mit";
    description = "A customizable extension for colorizing matching brackets";
  };
  vscode-extensions-code-runner = {
    pname = "vscode-extensions-code-runner";
    version = "0.11.6";
    src = fetchurl {
      url = "https://open-vsx.org/api/formulahendry/code-runner/0.11.6/file/formulahendry.code-runner-0.11.6.vsix";
      sha256 = "sha256-EHOaOsxmmnPXcDzl/7H7zDMxSsEB+2cjoaUOaJYpZHI=";
    };
    homepage = "https://github.com/formulahendry/vscode-code-runner";
    license = "mit";
    description = "Run C, C++, Java, JS, PHP, Python, Perl, Ruby, Go, Lua, Groovy, PowerShell, CMD, BASH, F#, C#, VBScript, TypeScript, CoffeeScript, Scala, Swift, Julia, Crystal, OCaml, R, AppleScript, Elixir, VB.NET, Clojure, Haxe, Obj-C, Rust, Racket, Scheme, AutoHotkey, AutoIt, Kotlin, Dart, Pascal, Haskell, Nim, D, Lisp, Kit, V, SCSS, Sass, CUDA, Less, Fortran";
  };
  vscode-extensions-codeql = {
    pname = "vscode-extensions-codeql";
    version = "1.5.9";
    src = fetchurl {
      url = "https://open-vsx.org/api/GitHub/vscode-codeql/1.5.9/file/GitHub.vscode-codeql-1.5.9.vsix";
      sha256 = "sha256-EvR0qPp125fiog2aOmCU42Niru5gLp58AS0ZkuNKals=";
    };
    homepage = "https://github.com/github/vscode-codeql";
    license = "mit";
    description = "CodeQL for Visual Studio Code";
  };
  vscode-extensions-codesnap = {
    pname = "vscode-extensions-codesnap";
    version = "1.3.4";
    src = fetchurl {
      url = "https://open-vsx.org/api/adpyke/codesnap/1.3.4/file/adpyke.codesnap-1.3.4.vsix";
      sha256 = "sha256-x1EpD4Q0tOhkCB9fl2mc7etaB2sI1d6KjbdUqqWIk+k=";
    };
    homepage = "https://github.com/kufii/CodeSnap";
    license = "mit";
    description = "\128247 Take beautiful screenshots of your code";
  };
  vscode-extensions-css-initial-value = {
    pname = "vscode-extensions-css-initial-value";
    version = "0.2.6";
    src = fetchurl {
      url = "https://dzhavat.gallery.vsassets.io/_apis/public/gallery/publisher/dzhavat/extension/css-initial-value/0.2.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-QLzjkPWPFCVJ0GrT8rtx8/V2JsdJ1zMdTmARtaqEcJQ=";
    };
    license = "mit";
  };
  vscode-extensions-dart-code = {
    pname = "vscode-extensions-dart-code";
    version = "3.29.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Dart-Code/dart-code/3.29.0/file/Dart-Code.dart-code-3.29.0.vsix";
      sha256 = "sha256-8Mnaz2bt3MV59/hRdsRSsDlW/lJ9B8KlC/uPbJiu7nY=";
    };
    homepage = "https://github.com/Dart-Code/Dart-Code";
    license = "mit";
    description = "Dart language support and debugger for Visual Studio Code.";
  };
  vscode-extensions-dendron = {
    pname = "vscode-extensions-dendron";
    version = "0.74.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/dendron/dendron/0.74.0/file/dendron.dendron-0.74.0.vsix";
      sha256 = "sha256-0Rmlgc2afYNUtCmLpSMODmdxoYHwEYxyS6dgLy35VNA=";
    };
    homepage = "https://github.com/dendronhq/dendron";
    license = "agpl3Only";
    description = "Dendron is a hierarchal note taking tool that grows as you do. ";
  };
  vscode-extensions-discord-presence = {
    pname = "vscode-extensions-discord-presence";
    version = "5.7.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/icrawl/discord-vscode/5.7.0/file/icrawl.discord-vscode-5.7.0.vsix";
      sha256 = "sha256-F18E0UOIaCLKh50TgSDv/EqsWt15FbnY+h8/QejAi1w=";
    };
    homepage = "https://github.com/iCrawl/discord-vscode";
    license = "mit";
    description = "Update your discord status with a rich presence.";
  };
  vscode-extensions-dotenv = {
    pname = "vscode-extensions-dotenv";
    version = "1.0.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/mikestead/dotenv/1.0.1/file/mikestead.dotenv-1.0.1.vsix";
      sha256 = "sha256-U5M0/G6/p4HqMtM2JAulkeKl+5lBd5bE4thPtYA4l8Y=";
    };
    homepage = "https://github.com/mikestead/vscode-dotenv";
    license = "mit";
    description = "Support for dotenv file syntax";
  };
  vscode-extensions-eslint = {
    pname = "vscode-extensions-eslint";
    version = "2.2.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/dbaeumer/vscode-eslint/2.2.2/file/dbaeumer.vscode-eslint-2.2.2.vsix";
      sha256 = "sha256-Q6/sRwV3hXQSt0Tj2a1nbi4+EEKM9LMItE+rMmp5GeI=";
    };
    homepage = "https://github.com/Microsoft/vscode-eslint";
    license = "mit";
    description = "Integrates ESLint JavaScript into VS Code.";
  };
  vscode-extensions-even-better-toml = {
    pname = "vscode-extensions-even-better-toml";
    version = "0.14.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/tamasfe/even-better-toml/0.14.2/file/tamasfe.even-better-toml-0.14.2.vsix";
      sha256 = "sha256-s9aRdMm/1P7kZElgP6RPAKrpMYwRksJWkNzWVD8dC1Q=";
    };
    homepage = "https://github.com/tamasfe/taplo";
    license = "mit";
    description = "Fully-featured TOML support";
  };
  vscode-extensions-flutter = {
    pname = "vscode-extensions-flutter";
    version = "3.29.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Dart-Code/flutter/3.29.0/file/Dart-Code.flutter-3.29.0.vsix";
      sha256 = "sha256-NK3hnh6ujKDwiXoBTkd/2W425nCrbqkDFBz8XGzMAAs=";
    };
    homepage = "https://github.com/Dart-Code/Flutter";
    license = "mit";
    description = "Flutter support and debugger for Visual Studio Code.";
  };
  vscode-extensions-gitlens = {
    pname = "vscode-extensions-gitlens";
    version = "11.7.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/eamodio/gitlens/11.7.0/file/eamodio.gitlens-11.7.0.vsix";
      sha256 = "sha256-po8JzwrADPSZY2SBlaX3N6VSURP/PZIGjFhS3hyV8io=";
    };
    homepage = "https://github.com/eamodio/vscode-gitlens";
    license = "mit";
    description = "Supercharge the Git capabilities built into Visual Studio Code \8212 Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more";
  };
  vscode-extensions-headwind = {
    pname = "vscode-extensions-headwind";
    version = "1.7.0";
    src = fetchurl {
      url = "https://heybourn.gallery.vsassets.io/_apis/public/gallery/publisher/heybourn/extension/headwind/1.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-yXsZoSuJQTdbHLjEERXX2zVheqNYmcPXs97/uQYa7og=";
    };
    homepage = "https://github.com/heybourn/headwind";
    license = "mit";
    description = "An opinionated Tailwind CSS class sorter built for Visual Studio Code";
  };
  vscode-extensions-html-css-class-completion = {
    pname = "vscode-extensions-html-css-class-completion";
    version = "1.20.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/Zignd/html-css-class-completion/1.20.0/file/Zignd.html-css-class-completion-1.20.0.vsix";
      sha256 = "sha256-ZoTxQ4Wf9ZFDyv/C6iSv3q6igW0rcCZogQEx5dK6354=";
    };
    homepage = "https://github.com/Zignd/HTML-CSS-Class-Completion";
    license = "mit";
    description = "CSS class name completion for the HTML class attribute based on the definitions found in your workspace.";
  };
  vscode-extensions-markdown-all-in-one = {
    pname = "vscode-extensions-markdown-all-in-one";
    version = "3.4.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/yzhang/markdown-all-in-one/3.4.0/file/yzhang.markdown-all-in-one-3.4.0.vsix";
      sha256 = "sha256-TFdvlN662Hvb6VlIqbtdt0W582SrS2R5cSRowHH0j8M=";
    };
    homepage = "https://github.com/yzhang-gh/vscode-markdown";
    license = "mit";
    description = "All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)";
  };
  vscode-extensions-markdown-preview-enhanced = {
    pname = "vscode-extensions-markdown-preview-enhanced";
    version = "0.6.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/shd101wyy/markdown-preview-enhanced/0.6.1/file/shd101wyy.markdown-preview-enhanced-0.6.1.vsix";
      sha256 = "sha256-BnjFsmL5ytA65bkiigtHz9iW1Sgr/ShNLcDqgMBkjx0=";
    };
    homepage = "https://github.com/shd101wyy/vscode-markdown-preview-enhanced";
    license = "ncsa";
    description = "Markdown Preview Enhanced ported to vscode";
  };
  vscode-extensions-material-icon-theme = {
    pname = "vscode-extensions-material-icon-theme";
    version = "4.11.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/PKief/material-icon-theme/4.11.0/file/PKief.material-icon-theme-4.11.0.vsix";
      sha256 = "sha256-nN+MiHffPppE7M9mVl4rXlwt/g1gegwMFt3IOGyW6nk=";
    };
    homepage = "https://github.com/PKief/vscode-material-icon-theme";
    license = "mit";
    description = "Material Design Icons for Visual Studio Code";
  };
  vscode-extensions-ms-vscode-cpptools = {
    pname = "vscode-extensions-ms-vscode-cpptools";
    version = "1.7.1";
    src = fetchurl {
      url = "https://github.com/microsoft/vscode-cpptools/releases/download/1.7.1/cpptools-linux.vsix";
      sha256 = "sha256-LqndG/vv8LgVPEX6dGkikDB6M6ISneo2UJ78izXVFbk=";
    };
  };
  vscode-extensions-nix-env-selector = {
    pname = "vscode-extensions-nix-env-selector";
    version = "1.0.7";
    src = fetchurl {
      url = "https://open-vsx.org/api/arrterian/nix-env-selector/1.0.7/file/arrterian.nix-env-selector-1.0.7.vsix";
      sha256 = "sha256-ifFIB+JxgujvLpr9zUV0D1jhihxIefvyDZkbPwW7EZU=";
    };
    homepage = "https://github.com/arrterian/nix-env-selector";
    license = "mit";
    description = "Allows switch environment for Visual Studio Code and extensions based on Nix config file.";
  };
  vscode-extensions-nix-ide = {
    pname = "vscode-extensions-nix-ide";
    version = "0.1.18";
    src = fetchurl {
      url = "https://open-vsx.org/api/jnoortheen/nix-ide/0.1.18/file/jnoortheen.nix-ide-0.1.18.vsix";
      sha256 = "sha256-GoCzYLkp6p+Oe1G3ilxNnXhtyRG3XQ8gUVy5lYd85cM=";
    };
    homepage = "https://github.com/nix-community/vscode-nix-ide";
    license = "mit";
    description = "Nix language support with formatting and error report.";
  };
  vscode-extensions-nixpkgs-fmt = {
    pname = "vscode-extensions-nixpkgs-fmt";
    version = "0.0.1";
    src = fetchurl {
      url = "https://B4dM4n.gallery.vsassets.io/_apis/public/gallery/publisher/B4dM4n/extension/nixpkgs-fmt/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-vz2kU36B1xkLci2QwLpl/SBEhfSWltIDJ1r7SorHcr8=";
    };
    license = "mit";
  };
  vscode-extensions-output-colorizer = {
    pname = "vscode-extensions-output-colorizer";
    version = "0.1.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/IBM/output-colorizer/0.1.2/file/IBM.output-colorizer-0.1.2.vsix";
      sha256 = "sha256-xa14/fZfj61NQI+4WqAkZVYq2E9cAgu4C5/AMua1SSY=";
    };
    homepage = "https://github.com/IBM-Bluemix/vscode-log-output-colorizer";
    license = "mit";
    description = "Syntax highlighting for log files";
  };
  vscode-extensions-pascal = {
    pname = "vscode-extensions-pascal";
    version = "9.4.0";
    src = fetchurl {
      url = "https://alefragnani.gallery.vsassets.io/_apis/public/gallery/publisher/alefragnani/extension/pascal/9.4.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-8JlDWLPfx7biBVOsnYkw0c8F70tTT0Lr3n637gVtMnI=";
    };
    license = "mit";
  };
  vscode-extensions-pascal-formatter = {
    pname = "vscode-extensions-pascal-formatter";
    version = "2.6.0";
    src = fetchurl {
      url = "https://alefragnani.gallery.vsassets.io/_apis/public/gallery/publisher/alefragnani/extension/pascal-formatter/2.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-Hmde76DAiHJSHDN60q6hGs9U6nKTrGdeR+xm4W2kj6g=";
    };
    license = "mit";
  };
  vscode-extensions-prettier = {
    pname = "vscode-extensions-prettier";
    version = "9.0.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/esbenp/prettier-vscode/9.0.0/file/esbenp.prettier-vscode-9.0.0.vsix";
      sha256 = "sha256-LenRtP7I1uv/lZRYJHw55TdYgez5ndHRRhUtsjDy0EM=";
    };
    homepage = "https://github.com/prettier/prettier-vscode";
    license = "mit";
    description = "Code formatter using prettier";
  };
  vscode-extensions-pubspec-assist = {
    pname = "vscode-extensions-pubspec-assist";
    version = "2.3.2";
    src = fetchurl {
      url = "https://open-vsx.org/api/jeroen-meijer/pubspec-assist/2.3.2/file/jeroen-meijer.pubspec-assist-2.3.2.vsix";
      sha256 = "sha256-FwP1Eu7aASOSlb9NuVUOFyeFNPh+avLjLpwdsZYsNEs=";
    };
    homepage = "https://github.com/jeroen-meijer/pubspec-assist";
    license = "mit";
    description = "Easily add and update dependencies to your Dart and Flutter project.";
  };
  vscode-extensions-python = {
    pname = "vscode-extensions-python";
    version = "2021.12.1559732655";
    src = fetchurl {
      url = "https://open-vsx.org/api/ms-python/python/2021.12.1559732655/file/ms-python.python-2021.12.1559732655.vsix";
      sha256 = "sha256-hXTVZ7gbu234zyAg0ZrZPUo6oULB98apxe79U2yQHD4=";
    };
    homepage = "https://github.com/Microsoft/vscode-python";
    license = "mit";
    description = "Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.";
  };
  vscode-extensions-react-native = {
    pname = "vscode-extensions-react-native";
    version = "1.8.1";
    src = fetchurl {
      url = "https://msjsdiag.gallery.vsassets.io/_apis/public/gallery/publisher/msjsdiag/extension/vscode-react-native/1.8.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-pJ9brxXIsC6cTZ+08RWweQrakEVTkpklCV4pcF3q2hk=";
    };
    license = "mit";
  };
  vscode-extensions-rest-client = {
    pname = "vscode-extensions-rest-client";
    version = "0.24.6";
    src = fetchurl {
      url = "https://open-vsx.org/api/humao/rest-client/0.24.6/file/humao.rest-client-0.24.6.vsix";
      sha256 = "sha256-rtKfCn5QW74f5YM3zOg/sxU6gX2PLFYmItdwjSMizRU=";
    };
    homepage = "https://github.com/Huachao/vscode-restclient";
    license = "mit";
    description = "REST Client for Visual Studio Code";
  };
  vscode-extensions-rust = {
    pname = "vscode-extensions-rust";
    version = "0.7.8";
    src = fetchurl {
      url = "https://open-vsx.org/api/rust-lang/rust/0.7.8/file/rust-lang.rust-0.7.8.vsix";
      sha256 = "sha256-5nur1zFsqudAzP5mQS/7r4rmgkbwY7+ONi0qM/3Ftwo=";
    };
    homepage = "https://github.com/rust-lang/rls-vscode";
    license = "[ \"mit\", \"asl20\" ]";
    description = "Rust for Visual Studio Code (powered by Rust Language Server/Rust Analyzer). Provides lints, code completion and navigation, formatting and more.";
  };
  vscode-extensions-svelte = {
    pname = "vscode-extensions-svelte";
    version = "105.8.0";
    src = fetchurl {
      url = "https://open-vsx.org/api/svelte/svelte-vscode/105.8.0/file/svelte.svelte-vscode-105.8.0.vsix";
      sha256 = "sha256-EEsEBnE71JRJmgTJLxateZiktCNCCMJAHj12sEDgrr0=";
    };
    homepage = "https://github.com/sveltejs/language-tools";
    license = "mit";
    description = "Svelte language support for VS Code";
  };
  vscode-extensions-tailwindcss = {
    pname = "vscode-extensions-tailwindcss";
    version = "0.7.4";
    src = fetchurl {
      url = "https://open-vsx.org/api/bradlc/vscode-tailwindcss/0.7.4/file/bradlc.vscode-tailwindcss-0.7.4.vsix";
      sha256 = "sha256-AtveBpiAlsVSEjEUvpPA07ku4N29ZSi5d7fAy8gs2y8=";
    };
    homepage = "https://github.com/tailwindlabs/tailwindcss-intellisense";
    license = "mit";
    description = "Intelligent Tailwind CSS tooling for VS Code";
  };
  vscode-extensions-versionlens = {
    pname = "vscode-extensions-versionlens";
    version = "1.0.9";
    src = fetchurl {
      url = "https://open-vsx.org/api/pflannery/vscode-versionlens/1.0.9/file/pflannery.vscode-versionlens-1.0.9.vsix";
      sha256 = "sha256-cPESnrSnCurVUEgPh6g4Tk7PY3K4du6w9pcOZUYf1bM=";
    };
    homepage = "https://gitlab.com/versionlens/vscode-versionlens";
    license = "isc";
    description = "Shows the latest version for each package using code lens";
  };
  waydroid = {
    pname = "waydroid";
    version = "d03e10c132de8e03dff781868b3e37b7f7c7128a";
    src = fetchFromGitHub ({
      owner = "waydroid";
      repo = "waydroid";
      rev = "d03e10c132de8e03dff781868b3e37b7f7c7128a";
      fetchSubmodules = false;
      sha256 = "sha256-y2+rRwxZ4jrnWDEYruzjOQlLF2ERB4v+sGchPK5mrTU=";
    });
  };
  wgcf = {
    pname = "wgcf";
    version = "ecf3b62ea61eabe483625fd1cbd476a8fd994952";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "ecf3b62ea61eabe483625fd1cbd476a8fd994952";
      fetchSubmodules = false;
      sha256 = "sha256-Dz19SlBTTCn73rnnU4PpZUbwcIpA6j2ODFYVAwTn7wI=";
    });
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "9b15add1354dba65b107573de8c4ef406bae7bf8";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-gtk-theme";
      rev = "9b15add1354dba65b107573de8c4ef406bae7bf8";
      fetchSubmodules = false;
      sha256 = "sha256-lVZXx8fXVOutJtg8BMEFFf8BYnnzvUnl+NB1cFKXHF0=";
    });
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "e99fedc45bae0e830a4a31eddb8080a37054fde3";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "whitesur-icon-theme";
      rev = "e99fedc45bae0e830a4a31eddb8080a37054fde3";
      fetchSubmodules = false;
      sha256 = "sha256-4CEay1n///ZRKGnzOFF6B8mZ3J1swNSp2pa+PdBIG5g=";
    });
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2391.0";
    src = fetchurl {
      url = "https://dl.google.com/widevine-cdm/4.10.2391.0-linux-x64.zip";
      sha256 = "sha256-7gH808C67m/s09e4rQUQHb/t+iGVdzW+YzrB1ZxGIdo=";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
    src = fetchFromGitHub ({
      owner = "ToadKing";
      repo = "wii-u-gc-adapter";
      rev = "fa098efa7f6b34f8cd82e2c249c81c629901976c";
      fetchSubmodules = false;
      sha256 = "sha256-wm0vDU7QckFvpgI50PG4/elgPEkfr8xTmroz8kE6QMo=";
    });
  };
  xdg-desktop-portal = {
    pname = "xdg-desktop-portal";
    version = "6241c5e8bfb60502ac3c7bc3babede22d35f3b1c";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal";
      rev = "6241c5e8bfb60502ac3c7bc3babede22d35f3b1c";
      fetchSubmodules = false;
      sha256 = "sha256-1fc3LXN6wp/zQw4HQ0Q99HUvBhynHrQi2p3s/08izuE=";
    });
  };
  xdg-desktop-portal-gtk = {
    pname = "xdg-desktop-portal-gtk";
    version = "b09453a7b580946ad98b10c21a0458c865389e09";
    src = fetchFromGitHub ({
      owner = "flatpak";
      repo = "xdg-desktop-portal-gtk";
      rev = "b09453a7b580946ad98b10c21a0458c865389e09";
      fetchSubmodules = false;
      sha256 = "sha256-QbH/qcYGH/7gQnQY7UuSGImZjVcFIyxtpYayjQYdDm0=";
    });
  };
  xorg-libxcvt = {
    pname = "xorg-libxcvt";
    version = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/xorg/lib/libxcvt";
      rev = "6fe840b9295cfdc41bd734586c5b8756f6af6f9b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qKKb/i67QY/NxZFkJaVRc3hGPjjnRfgpMqGqZ0YNQE8=";
    };
  };
  xorgproto = {
    pname = "xorgproto";
    version = "914d8f5e0f469cd0416364dd008e9eea752bf703";
    src = fetchFromGitHub ({
      owner = "freedesktop";
      repo = "xorg-xorgproto";
      rev = "914d8f5e0f469cd0416364dd008e9eea752bf703";
      fetchSubmodules = false;
      sha256 = "sha256-XJtYZYbmwCrkbB7a533kkI/CcawkmHHSEu4zSznVvEY=";
    });
  };
  xwayland = {
    pname = "xwayland";
    version = "38291fa86c00e1d3ee37612c9215b0c15da89051";
    src = fetchgit {
      url = "git://anongit.freedesktop.org/xorg/xserver";
      rev = "38291fa86c00e1d3ee37612c9215b0c15da89051";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-a1xz8MpKKL9yQqwBpafOu4+jgllsafia20S2W77xrbg=";
    };
  };
  ydotool = {
    pname = "ydotool";
    version = "e1334aee314c25a795ed3a60463a1b4b129409b5";
    src = fetchFromGitHub ({
      owner = "ReimuNotMoe";
      repo = "ydotool";
      rev = "e1334aee314c25a795ed3a60463a1b4b129409b5";
      fetchSubmodules = false;
      sha256 = "sha256-/3V2rVMwXi6+qEtPgPK/8mozveEhFtvop9mZAxBf71M=";
    });
  };
  zoom-us = {
    pname = "zoom-us";
    version = "5.9.1.1380";
    src = fetchurl {
      url = "https://cdn.zoom.us/prod/5.9.1.1380/zoom_x86_64.pkg.tar.xz";
      sha256 = "sha256-3HuVCDaOnepGMiRaQ78QcCdgNzI60egbPGfoOfwIPGQ=";
    };
  };
}
