name: Auto update flake.lock

on:
  workflow_dispatch:
  schedule:
    # Update every 1 hour
    - cron: "0 * * * *"

jobs:
  update_pkgs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install latest nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://dan-cfg.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= dan-cfg.cachix.org-1:elcVKJWjnDs1zzZ/Fs93FLOFS13OQx1z0TxP0Q7PH9o=
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup nix drv cache
      uses: cachix/cachix-action@v10
      with:
        name: dan-cfg
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Quick eval
      run: nix develop --show-trace --print-build-logs .#x86_64-linux.nixpkgs.devshells.default --command evalnix

    - name: Setup git cred for github actor
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        push: false

    - name: Update flake.lock
      run: nix flake update --commit-lock-file

    - name: Push changes to main
      run: git pull --rebase --autostash && git push
