name: Auto update minecraft mods

on:
  push:
    paths:
      - cells/fog/pkgs/misc/minecraft-mods.toml
  workflow_dispatch:
  schedule:
    # Update every 1 hour
    - cron: "0 * * * *"

jobs:
  update_pkgs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: Cache nvfetcher
      uses: actions/cache@v3
      with:
        path: ~/.local/share/nvfetcher
        key: ${{ runner.os }}-nvfetcher

    - name: Install latest nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://fog.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fog.cachix.org-1:FAxiA6qMLoXEUdEq+HaT24g1MjnxdfygrbrLDBp6U/s=
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup nix drv cache
      uses: cachix/cachix-action@v10
      with:
        name: fog
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Quick eval
      run: nix develop --show-trace --print-build-logs --command evalnix

    - name: Create fog cache
      run: nix develop --show-trace --print-build-logs --command fog makeFogCache

    - name: Clean up old nvfetcher extracts
      run: nix develop --show-trace --print-build-logs --command fog nvfetcher-cleanup minecraft-mods

    - name: Update all minecraft-mods extensions
      run: nix develop --show-trace --print-build-logs --command fog updateSources misc/minecraft-mods

    - name: Push changes to main
      run: git pull --rebase --autostash && git push
